### ISSUE TITLE
Do you have any recomendations to configure brigade-k8s-gateway to listen differents namespaces

### ISSUE THREAD

**Issue by nestajah** [brigadecore/brigade#1001]
Initially the gateway listens in the namespace that is configured for brigade but I would like to have the best scheme to allow it to listen to events from several namespaces.

Thanks for your time.

`brig version`: v1.2.0
`kubectl version`: v1.15.3
Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by radu-matei** [comment]
Hi, @nestajah!
If you take a look at the chart for the Kubernetes gateway, in the values file there is a key for `namespace` - https://github.com/brigadecore/charts/blob/8708d0dfc8f46e2705516b866a85e7e76464d57a/charts/brigade-k8s-gateway/values.yaml#L43-L45

This ends up setting the `GATEWAY_NAMESPACE` environment variable in the actual gateway - https://github.com/brigadecore/brigade-k8s-gateway/blob/fb7cdf8497d47981bbdbf97375b6bc933f775bee/cmd/k8s-gateway/main.go#L276

**Comment by nestajah** [comment]
Hello, @radu-matei 

Do you need the gateway to listen to events in multiple namespaces at the same time?
(I'm also curious for the use case of listening on multiple namespaces.)

Yes, I want to establish some actions both for namespaces with functional microservices and also those that are part of the infrastructure of kubernetes (by default, kube-system) for additional resistance devices in addition to having life and disposition. My first question arose because although I make the change in the configmap does not read any event. Should I generate the role and link for this case associated with namespaces?

**Comment by nestajah** [comment]
Sorry very bad english:

Yes, I want to establish some actions both for namespaces with functional microservices and also those that are part of the infrastructure of kubernetes (default, kube-system) for additional resilience devices in addition to having life and disposition. My first question arose because although I make the change in the configmap does not read any event. Should I generate the role/rolebinding and link for this case associated with namespaces?

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
