### ISSUE TITLE
Update Node version for worker

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#1002]
Currently, we're basing our worker image on Node 8, whose deprecation is coming at the end of the year ([source](https://nodejs.org/en/about/releases/))

![image](https://user-images.githubusercontent.com/13103165/67835087-55a67c00-faa6-11e9-8ead-35db92061cdb.png)

I think it makes sense to migrate to a stable LTS - 10 or 12.

https://github.com/brigadecore/brigade/blob/2218bcf12b4005256713c4caa0ca9e5cb87e89ab/brigade-worker/Dockerfile#L1

**Comment by veeramarni** [comment]
Any update on this request? We have some dependencies to add to worker that uses node 10version
