### ISSUE TITLE
CI: KinD-based E2E failure

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1015]
Although our KinD-based [E2E job](https://github.com/brigadecore/brigade/blob/master/brigade.js#L53-L71) has proven pretty reliable, we've noted a few instances of failures, with one main symptom, KinD's etcd server timing out.  For example:

```
...
-----Creating a test project-----
Project ID: brigade-5b55ed522537b663e178f751959d234fd650d626f33f70557b2e82
-----Checking if the test project secret was created-----
-----Running a Build on the test project-----
Error: etcdserver: request timed out
exit status 1
```

from https://brigadecore.github.io/kashti/jobs/test-e2e-01drz1kaybhqprs33c1v357h22

Let's see if we can access the etcd image logs and/or otherwise find out the cause of the failure.  Perhaps resource limits on the job pod itself?  Any leads on if this is a general KinD issue?

**Comment by vdice** [comment]
One thought I had today: let's audit this e2e job/script to be sure more than one instance can run at the same time on the same k8s cluster.  As always, a prime candidate for the cause here could be interactions between one or more parallel run.

**Comment by vdice** [comment]
Another symptom: https://github.com/brigadecore/brigade/pull/1010/checks?check_run_id=291378917
```
Release "brigade-server" does not exist. Installing it now.
NAME: brigade-server
LAST DEPLOYED: Wed Nov  6 17:44:24 2019
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
Brigade is now installed!

To find out about your newly configured system, run:

  $ helm status brigade-server
make[1]: Leaving directory '/go/src/github.com/brigadecore/brigade'
-----Waiting for Brigade components' deployments-----
Waiting for deployment of brigade-server-brigade-api in namespace default with a timeout 60 seconds
Expected generation for deployment brigade-server-brigade-api: 1
Currently observed generation: 
Currently observed generation: 
Currently observed generation: 
... (repeats for many lines)
Currently observed generation: 
Timeout 60 exceeded
Terminated
make: *** [Makefile:252: e2e] Error 143
Deleting cluster "kind" ...
```

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
