### ISSUE TITLE
Guidance for OSS projects managing their brigade definition

### ISSUE THREAD

**Issue by carolynvs** [brigadecore/brigade#1016]
@vdice asked me to open this so apologies if it's in the wrong place! 😀 

When I'm an open source project and want every maintainer to be able to support the project equally, do you have a recommendation for how to do that when I'm using brigade? For example, my team right now puts our brigade definition/repo into keybase. Not all of the maintainers on our projects have access to this though, just some. Managing separate repos and auth lists is overhead that always ends up out of date.

Is there a best practice or guide for an OSS project for how to setup brigade in such a way that everyone who is a maintainer can also maintain their project's CI? How do you do it for your own CI for Brigade?

**Comment by technosophos** [comment]
Are you mainly asking where to put the secrets that are stored in your `project` definition? I imagine they can be stored in any shared secret storage.

All other stuff can be stored in a regular repo, I'd imagine.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
