### ISSUE TITLE
Refactor - Create/use RunOpts to send info from brig run cmd to pkg

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1021]
Brig's `run` and `rerun` cmds have a lot of their own variables defined, e.g. as seen here in [run](https://github.com/brigadecore/brigade/blob/master/brig/cmd/brig/commands/run.go#L15-L25).  Both to reduce passing a lengthy number of arguments to `pkg` function calls and to make sure `run` and `rerun` stay in parity in terms of args/opts they support, we should create and use a `RunOpts` struct containing these shared args/opts and pass this to subsequent `pkg` function calls.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
