### ISSUE TITLE
Kubernetes 1.16 incompatibility

### ISSUE THREAD

**Issue by edavidmv** [brigadecore/brigade#1028]
It seems that brigade charts are not compatible yet with Kubernetes 1.16, trying to install on such platform results in errors due to deprecation of _extensionts/v1beta1_ for deployments.

Error:
`Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"]`

Tried to modify the deployment charts locally but then another error showed up:
`missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec`

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
microk8s - Kubernetes 1.16.2

**Comment by radu-matei** [comment]
cc @vdice - we should probably update all Brigade.

**Comment by vdice** [comment]
Thanks for filing @edavidmv .  I've created a ticket in the charts repo to track updates there: https://github.com/brigadecore/charts/issues/54

Perhaps we save this ticket for vendor/code updates among the applicable Brigade components themselves?

**Comment by vdice** [comment]
https://github.com/brigadecore/charts/pull/55 has been issued and approved; should be good to merge and cut charts first thing next week.

In my testing, normal Brigade functionality seems to continue unaffected on a k8s cluster >= 1.16.0 (minikube v1.16.2).  Worker and job pods are scheduled fine, vacuum pods are scheduled and run fine... anything else I'm missing and/or we should check?

Of course, the k8s APIs that Brigade uses should perhaps still be upgraded, but I'm not sure if it is strictly necessary for the next 1.3 release.  What do we think?

**Comment by vdice** [comment]
The original issue has been fixed by the chart updates and as mentioned, I didn't see any immediate/obvious failures during Brigade runtime on a v1.16.x k8s cluster, so I'm going to close this issue.  We can create specific issue(s) when/if encountered.
