### ISSUE TITLE
Plans for supporting CloudEvents 1.0?

### ISSUE THREAD

**Issue by jakobehn** [brigadecore/brigade#1029]
Hi team!

The CloudEvents specification reached v1.0 a month ago, and Azure EventGrid just announced support for v1.0 as well
https://azure.microsoft.com/en-us/updates/azure-event-grid-now-supports-cloudevents-v1-0-for-greater-interoperability/

Are there any ongoing work to support v1.0 in the generic gateway? 

Thanks!

**Comment by radu-matei** [comment]
Hi, Jakob!
Sure, we should update the generic gateway to support v1.0 - the initial generic gateway had support for v0.2 - and accepted requests at `/cloudevents/v02/:projectID/:secret` - we should _add_  a `v1` path to that URL and continue to support `v02`, so we maintain backwards incompatibility.

We should plan this for Brigade 1.3, so pinging @dgkanatsios, who initially added the CloudEvents support, but I don't expect the update process to be significantly  difficult.

Thanks a lot!

**Comment by jakobehn** [comment]
Excellent! Since Azure EventGrid now supports CloudEvents v1.0, this would be a welcome addition.

Thanks!

**Comment by vdice** [comment]
Removing from 1.3; we can consider for a future milestone if/when PRs appear.

**Comment by krancour** [comment]
I'm closing this due to staleness, but I am happy to report that we have a CloudEvents 1.0 gateway for v2.

https://github.com/brigadecore/brigade-cloudevents-gateway
