### ISSUE TITLE
pods crash-loop in default OpenShift cluster

### ISSUE THREAD

**Issue by joshgav** [brigadecore/brigade#1032]
Hi team, hope you're well! Wanted to let you know that extra configuration is required to run Brigade on OpenShift. This seems to be because the Brigade containers expect to run as a specific user/UID and OpenShift's default policy is to assign a UID of its choosing (links follow for reference). 

Specifically, after I deploy the Brigade chart I have to run `oc adm policy add-scc-to-group anyuid system:serviceaccounts:brigade` to allow its containers to use their chosen UID (`brigade` is the namespace where I deployed brigade). Note that requires a cluster admin.

Assuming that config is indeed required in OpenShift it would be great to document it, and even better if you could arrange for Brigade's containers to run with arbitrary UIDs so no exceptional policy would be needed - info on that in the links. Thanks for the consideration.

If that policy isn't applied you'll see CrashLoopBackOffs for the pods and errors like the following in the logs:

```
kubectl logs deployment/brigade-brigade-ctrl
    W1204 20:54:32.937750       1 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
    log: exiting because of error: log: cannot create log: open /tmp/brigade-controller.brigade-brigade-ctrl-5874b54cd5-zpd2p.unknownuser.log.WARNING.20191204-205432.1: permission denied
kubectl logs deployment/brigade-brigade-api
    W1204 20:55:42.609026       1 client_config.go:533] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
    log: exiting because of error: log: cannot create log: open /tmp/brigade-api.brigade-brigade-api-696b6c89fd-cr4qd.unknownuser.log.WARNING.20191204-205542.1: permission denied
kubectl logs deployment/brigade-kashti
    2019/12/04 20:55:40 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
    nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
    2019/12/04 20:55:40 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
    nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
```

Links re UIDs in OpenShift:

* <https://docs.openshift.com/container-platform/4.1/openshift_images/create-images.html#use-uid_create-images>
* <https://www.softwarewithjeff.com/blog/running-pods-with-particular-uids-scc-exploration-with-openshift>
* <https://medium.com/bitnami-perspectives/running-containers-in-openshift-629af79945b5>

----

Output of `brig version`:

```
v1.2.1
```

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+dea7fb9", GitCommit:"dea7fb9", GitTreeState:"clean", BuildDate:"2019-11-19T17:18:37Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Output of `oc version`:

```
Client Version: unknown
Server Version: 4.2.8
Kubernetes Version: v1.14.6+dea7fb9
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

CodeReady Containers: <https://github.com/code-ready/crc>

**Comment by radu-matei** [comment]
Hi, Josh,
First of all, thanks a lot for the detailed report!

I think an immediate action would be to add a general documentation page about running Brigade on OpenShift, and document this as a _temporary_ workaround until we explore a fix that would work across Kubernetes and OpenShift.

Given that I think none of the core maintainers have that much experience with OpenShift, would you consider contributing to the docs, or at least reviewing the changes?

Thanks!

**Comment by joshgav** [comment]
Hi @radu-matei, sure. In addition to the UID issue, OpenShift uses [routes](https://github.com/openshift/api/blob/master/route/v1/types.go), approximately equal to ingresses but not quite, so I couldn't use the ingresses in the Brigade charts and configured my own routes instead.

All up and running now :+1: so I'll document these couple items when I have a chance and find a place to submit them here. If you all document before let me know, happy to review.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
