### ISSUE TITLE
[proposal]: do not use k8s as an event/message bus

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1036]
Related to #1034 

Currently, Brigade gateways emit events into Brigade in the form of Kubernetes secrets. Brigade uses a controller to watch all such secrets. In effect, Kubernetes is being used as an event/message bus. Make no mistake-- this _works_, but better options likely exist.

* Along with project configuration, contributes to Brigade's "control plane" being unnecessarily constrained to running only in Kubernetes.

* The current approach "clutters" the Kubernetes cluster quite significantly over time.

    * Custom solution for automated cleanup is possible, but deleting an event's underlying secret removes _all_ record of the event. Your practical choices are between accepting the clutter in your cluster or losing your papertrail (which may not be an option for certain in use cases in many regulated industries).

    * It's not known how well this scales to very large event volumes.

* Proper event/message buses offer options we don't currently have-- things that would be, at least difficult to implement when relying on secrets as the underlying event/message bus.

    * Delivery order
    * Throttling
    * Retries
    * Persistence
    * Backup/restore

Considerations worth noting:

* To maintain a papertrail of events (for those who need it), events should probably be persisted somewhere so that our only record of each event isn't the transient one on the bus.

*  Presuming that we _might_ create an appropriate abstraction such that different buses could be pluggable, this could put a burden on gateways to be able to integrate with multiple buses. To remediate that, we should probably remove _all_ responsibility for putting messages directly on the bus(es) from the gateways and instead have gateways communicate with Brigade _only_ through its API. The API server can put events on the bus.

**Comment by vdice** [comment]
This all sounds reasonable and my only real input here is to pose the question on priority of this endeavor.  In other words, besides the issues of clutter (secrets) and constraint to k8s, are there/have there been persistent issues stemming from this approach?

Anyhow, even if there aren't truly pressing concerns, I would agree this work should be considered if/when we agree in 2.0 that we'd like to de-couple Brigade from K8s as much as feasible.  This indeed would fit nicely in with that overarching goal.

**Comment by krancour** [comment]
This is well covered by the [2.0 proposal](https://github.com/brigadecore/brigade/tree/master/2.0-PROPOSAL), which has been ratified and is now guiding the 2.0 development effort. It probably doesn't make sense to track this as a discrete issue anymore.
