### ISSUE TITLE
[proposal] Generic Gateway: use Authorization HTTP Header instead URL Path

### ISSUE THREAD

**Issue by danmx** [brigadecore/brigade#1040]
Right now Generic Gateway's secret is send in a [path](https://docs.brigade.sh/topics/genericgateway/#using-the-generic-gateway). It could be logged by proxies. Common approach is to use [Authorization HTTP Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization).

**Comment by krancour** [comment]
Completely agree, but this would be a breaking change. Labeling it as something we will look at for 2.0.

**Comment by radu-matei** [comment]
Oh, this is a really good catch!
A little bit of context for this - when we initially designed the gateway, one of the services we were testing the CloudEvents integration required the handshake to happen by passing a validation code in the path, so we used the same approach here.

That being said, we should absolutely change this.

I'm also thinking at a non-breaking change way of handling this - we have in place versions for both types of events in the generic gateway, and we can simply add a new path that would accept the secret in the header, while still keeping the original path.

**Comment by krancour** [comment]
> I'm also thinking at a non-breaking change way of handling this - we have in place versions for both types of events in the generic gateway, and we can simply add a new path that would accept the secret in the header, while still keeping the original path.

That seems reasonable.

**Comment by vdice** [comment]
+1. Sounds like this issue is ready to be prioritized, the proposal having been greeted w/ approval.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
