### ISSUE TITLE
VCS-Sidecar intermittently failing fetch

### ISSUE THREAD

**Issue by gfrankel97** [brigadecore/brigade#1045]
This `vcs-sidecar` failure has happened 3 times in recent memory, but very intermittently. 
Has anyone experienced this or knows of steps to prevent this failure? Thanks in advance.

Output of `kubectl logs <BRIGADE_CONTAINER_NAME> -c vcs-sidecar`:
```+ : 
+ : refs/heads/master
+ : /vcs
+ refspec=refs/heads/master
+ git ls-remote --exit-code <COMPANY_NAME>@vs-ssh.visualstudio.com:v3/<COMPANY_NAME>/<TEAM_PROJECT_NAME>/Kube-Brigade-Script refs/heads/master
+ cut -f2
Warning: Permanently added 'vs-ssh.visualstudio.com,20.44.80.98' (RSA) to the list of known hosts.
remote: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 13.86.38.60:22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
+ full_ref=
+ git init -q /vcs
+ cd /vcs
+ retry git fetch -q --force --update-head-ok <COMPANY_NAME>@vs-ssh.visualstudio.com:v3/<COMPANY_NAME>/<TEAM_PROJECT_NAME>/Kube-Brigade-Script refs/heads/master
+ local 'n=1'
+ local 'max=5'
+ local 'delay=5'
+ true
+ git fetch -q --force --update-head-ok <COMPANY_NAME>@vs-ssh.visualstudio.com:v3/<COMPANY_NAME>/<TEAM_PROJECT_NAME>/Kube-Brigade-Script refs/heads/master
Warning: Permanently added 'vs-ssh.visualstudio.com,20.44.80.98' (RSA) to the list of known hosts.
+ break
+ retry git checkout -q --force refs/heads/master
+ local 'n=1'
+ local 'max=5'
+ local 'delay=5'
+ true
+ git checkout -q --force refs/heads/master
error: pathspec 'refs/heads/master' did not match any file(s) known to git.
+ test 1 -lt 5
+ echo 'Command failed. Attempt 1/5. Waiting for 5 seconds before retrying.'
+ sleep 5
Command failed. Attempt 1/5. Waiting for 5 seconds before retrying.
+ n=2
+ true
+ git checkout -q --force refs/heads/master
error: pathspec 'refs/heads/master' did not match any file(s) known to git.
+ test 2 -lt 5
+ echo 'Command failed. Attempt 2/5. Waiting for 10 seconds before retrying.'
+ sleep 10
Command failed. Attempt 2/5. Waiting for 10 seconds before retrying.
+ n=3
+ true
+ git checkout -q --force refs/heads/master
error: pathspec 'refs/heads/master' did not match any file(s) known to git.
Command failed. Attempt 3/5. Waiting for 15 seconds before retrying.
+ test 3 -lt 5
+ echo 'Command failed. Attempt 3/5. Waiting for 15 seconds before retrying.'
+ sleep 15
+ n=4
+ true
+ git checkout -q --force refs/heads/master
error: pathspec 'refs/heads/master' did not match any file(s) known to git.
+ test 4 -lt 5
+ echo 'Command failed. Attempt 4/5. Waiting for 20 seconds before retrying.'
+ sleep 20
Command failed. Attempt 4/5. Waiting for 20 seconds before retrying.
+ n=5
+ true
+ git checkout -q --force refs/heads/master
error: pathspec 'refs/heads/master' did not match any file(s) known to git.
+ test 5 -lt 5
+ fail 'The command has failed after 5 attempts.'
+ echo The command has failed after 5 attempts.
The command has failed after 5 attempts.
+ exit 1
```

Output of `brig version`: v1.0.0-23-g1b849be

Output of `kubectl version`: Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AKS

**Comment by radu-matei** [comment]
Hello, and thanks for filing this issue!

It appears you are using Azure DevOps to host the repository - just to make sure, I would re-check that you have access to the repository (but given that the error is intermittent, this is highly unlikely).

The error message seems to indicate the error is on the Azure DevOps side:

> remote: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond <IP-ADDRESS>
fatal: Could not read from remote repository.

> Please make sure you have the correct access rights
and the repository exists.

This could also be an issue with your cluster network. If you get repo credentials, can you reproduce the issue in a simple pod with `git`? 

There is also some initial work for an Azure DevOps (well, VSTS..) gateway - https://github.com/brigadecore/brigade-vsts-gateway - thought it might be worth checking out.

**Comment by gfrankel97** [comment]
We still see this issue very intermittently, like maybe once every 3 months. I have not found time to dig into using the brigade-vsts-gateway as suggested. Frankly, I think its an issue coming from Azure DevOps, not sure that Brigade can or should be accounting for it. You already put retry logic in there. Closing as I don't think it's Brigade's fault.
