### ISSUE TITLE
Enable setting default storage at the Brigade level, not merely at the project level

### ISSUE THREAD

**Issue by squillace** [brigadecore/brigade#1046]
Currently, Brigade requires ReadWriteMany: https://docs.brigade.sh/topics/storage/#supporting-brigade-storage. 

However, `helm3 inspect brigade/brigade` indicates that there is no way to set the `kubernetes.buildStorageClass` or `kubernetes.cacheStgorageClass` as a server wide default, though it IS a required feature for Brigade all up.

I suggest we enable that at the Brigade server installation to improve UX.

**Comment by krancour** [comment]
This was already added in #908 and https://github.com/brigadecore/charts/pull/12

I think you're looking at the wrong configuration options, perhaps.

Use `worker.defaultBuildStorageClass` and `worker.defaultCacheStorrageClass`.

These will apply if and only if build storageclass and cache storageclass are left undefined at the project level-- which is an option that the `brig project create` process _does_ give you.

Please ping me tomorrow if this doesn't do the trick for you.

**Comment by squillace** [comment]
yup. both `helm inspect` and `helm show` do not indicate these possible values because in the chart they're commented out. Is there a specific place in docs for all the POSSIBLE values that isn't in the chart code itself?

**Comment by krancour** [comment]
As I know (via out-of-band discussion) you've already determined, `helm inspect values brigade/brigade` will give you what you're looking for. Just leaving this hear for anyone else who happens across this thread.
