### ISSUE TITLE
Setting job.env causes "Cannot read property 'secretRefKey'"

### ISSUE THREAD

**Issue by brennancheung** [brigadecore/brigade#1050]
When creating a `Job` and setting `env` it will cause the job to fail with the error message:

`Cannot read property 'secretKeyRef' of undefined`

I'm trying to run the example in the tutorial for integrating with the GitHub Checks API.

Example:

```javascript
// This Check Run image handles updating GitHub
  const checkRunImage = "brigadecore/brigade-github-check-run:latest";

  // Common configuration
  const env = {
    CHECK_PAYLOAD: e.payload,
    CHECK_NAME: "Brigade",
    CHECK_TITLE: "Run Tests",
  };

  // For convenience, we'll create three jobs: one for each GitHub Check
  // stage.
  const start = new Job("start-run", checkRunImage);
  start.imageForcePull = true;
  start.env = env;
  start.env.CHECK_SUMMARY = "Beginning test run";
  start.run()
```

This fails with the error:

`Cannot read property 'secretKeyRef' of undefined`

If I comment out anything that sets `start.env` it won't have the error but obviously that won't have the intended effect.

**Comment by brennancheung** [comment]
I narrowed down the problem to setting some of the other keys in the env to `undefined`.  Not sure why it would display an error about secretRefKey, but removing some of the keys with no values solved the problem for me.  Closing this issue.

**Comment by krancour** [comment]
I haven't dug too deep, but at just a glance, you've done something that isn't valid afaik. You've used a variable (`e`) in defining the value of a constant (`env`). I'm surprised that is even allowed, but the result is certainly _not_ what you were looking for, as `e` would be undefined at the time the value of `env` is determined.

**Comment by krancour** [comment]
And I see that mistake seems to come straight out of our docs... so either I am wrong or the docs are. I'll take a closer look as soon as I have a chance.
