### ISSUE TITLE
Feature request: pass custom data to a job's vcs sidecar

### ISSUE THREAD

**Issue by bogatuadrian** [brigadecore/brigade#1053]
Some use cases might require a custom vcs sidecar instead of the one provided with brigade. In those cases, it would be nice if we could also pass custom data to the job's sidecars (through env vars, for example).

Some possible solutions are:
1. Pass all the environment variables from the job's secret to the sidecar
2. Add an extra `vcsEnv` field on `Job` that contains env vars that will be passed _only_ to the sidecar spec

If you think this would be a nice feature to have in brigade, I'm willing to make a PR with the implementation after we discuss the best approach.

**Comment by radu-matei** [comment]
ref #477, which asks for setting environment variables in the worker.

One solution I proposed in #477 was to extend the usage of `brigade.json` (which we use for custom packages that are supposed to be installed in the worker) for environment variables.
However, that wouldn't handle the case where you would want to pass a secret / a value that you don't want stored in plain text.

**Comment by bogatuadrian** [comment]
Sorry for not being clear enough. I wasn't referring to static hardcoded values, but more to dynamically provisioned data. Also, I was talking about passing env vars to the vcs-sidecar of a job, not to the worker.

Maybe an example would help: I want to modify my vcs sidecar to also perform `git merge` before the job starts. For that, I would like to pass some environment variables from the worker to the vcs-sidecar of the job. Env vars could be something like `MERGE_FROM`, `MERGE_TO` that would set based on the event payload (so dynamically).

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
