### ISSUE TITLE
Multiple brigade.js in the same repository

### ISSUE THREAD

**Issue by gavD** [brigadecore/brigade#1058]
*Output of `brig version`:*
v1.2.1

*Output of `kubectl version`:*
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-c0eccc", GitCommit:"c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2", GitTreeState:"clean", BuildDate:"2019-12-22T23:14:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

*Cloud Provider/Platform (AKS, GKE, Minikube etc.):*
EKS (Amazon)

I have several different pipelines (`brigade.js` files) that I want to serve from the same repo.

I have put them in pipelines/environment-create/brigade.js and pipelines/environment-delete/brigade.js

I tried setting brigadejsPath to a base 64 encoded string e.g. `brigadejsPath: cGlwZWxpbmVzL2Vudmlyb25tZW50LWRlbGV0ZS8K` (pipelines/environment-delete/) but it seems to have no effect at all... Nothing happens unless brigade.js is in the root of the project.

I have tried every variation I can think of (e.g. pipelines/environment-delete/brigade.js, /pipelines/environment-delete/brigade.js ...)

There may well be something I am missing here... Am I working against the tool?

Please help!

**Comment by krancour** [comment]
Script locations in order of precedence:

https://github.com/brigadecore/brigade/blob/master/brigade-worker/src/index.ts#L47-L63

What you're looking to do seems reasonable, however. I believe we're likely to sort this out in the 2.0 timeframe. I'm currently drafting a 2.0 proposal and the proposal includes the ability for a project to have multiple "builds" triggered by a single event (though that term "build" has widely been judged too-CI-centric and is likely to be replaced with something more generic). Necessarily, then, that includes some mappings. e.x.: An event looks like this triggers _this_ `brigade.js` whilst an event that looks like _that_ triggers _that_ `brigade.js`. This seems as if it would have you covered.

**Comment by gavD** [comment]
thanks for getting back to me :-)

Just to clarify; `brigadejsPath` has no affect in the current version, is that correct?

So to get my desired behaviour, the easiest way would be to set `process.env.BRIGADE_SCRIPT` ?

**Comment by krancour** [comment]
@gavD first, my apologies. I have 2.0 on the brain and it was too easy for me to look at this through a lens of how this can all be improved in 2.0. I zeroed right in on the "multiple brigade.js" aspect and overlooked that you're not necessarily trying to make one project use different ones for different events. _You're just looking to use one specific one._ Have I go that right? (Or this is your _immediate_ problem, at least? If you plan to create more brigade projects to run your _other_ `brigade.js` scripts from the same repo, I know you're going to run into other problems... but I digress.) At any rate... my sincere apologies for overlooking and failing to answer the specific question about `brigadejsPath`.

I can confirm that setting that _does_ have an effect, and I've even double-checked that just now.

To troubleshoot your issue further, can you take a peek at the worker pod and see if/how `BRIGADE_SCRIPT` environment variable has been defined?

**Comment by gavD** [comment]
Thank you for getting back to me so promptly :-)

My use case is that I have an API in front of Brigade.

The API has two operations at the moment:
1. Request a new K8s environment (via Helm, etc)
2. Delete an environment

Both operations I have created as separate Brigade projects, and their code is in the same git repository.

So, I wanted to have a second `brigade.js`, effectively.

The solutions I came up with are:

1. Pass a parameter to Brigade so it can load different tasks (I don't like this)
2. Multiple git repos (I really don't want to do this)
3. Multiple "`brigade.js`" files, specified via `brigadejsPath` on the secret that represents the Brigade projects (which is what I was trying to do here). I'm fairly sure I implemented it correctly but no matter what I did it would not load any file except `./brigade.js` in the root of the repo.

I hope this makes sense!

**Comment by krancour** [comment]
> My use case is that I have an API in front of Brigade.

This is useful information. It means some of the problems I was anticipating you'd run into aren't going to come up. Namely, the github gateway emits events for projects with a name matching the repo name. This makes it impossible for the gateway to selectively emit events from one repo for n brigade projects. But, it seems as if the github gateway isn't in play for you. _Your API is acting as a gateway by emitting events into Brigade_ and github is only being used to _store_ your scripts and is not directly the source of your events. This is useful context. 👍 

Can you tell me if the "vcs sidecar" (really it is an init container) seems to be running, and running successfully for your workers?

**Comment by krancour** [comment]
Amending my previous post-- I am asking because if cloning the repo isn't working as expected before the worker executes, then the reason the script you specified isn't executing is because it simply doesn't exist within the pod.

**Comment by gavD** [comment]
the sidecar works perfectly, as far as I can tell.

So long as I only want to run `brigade.js` in the root, and not from any other location, it's all fine, I have no problems

**Comment by krancour** [comment]
And the value of the `BRIGADE_SCRIPT` in the worker's main container is what you expect?

**Comment by gavD** [comment]
`BRIGADE_SCRIPT:                       /vcs/pipelines/environment-delete/brigade.js`

And the container basically no-ops
```
prestart: installing jsonschema@^1.2.5
[brigade] brigade-worker version: 1.2.1
[brigade:k8s] Creating PVC named brigade-worker-01e1cj1n1tcj9w3w91yvse3163
[brigade:app] no-after: fired
[brigade:app] beforeExit(2): destroying storage
[brigade:k8s] Destroying PVC named brigade-worker-01e1cj1n1tcj9w3w91yvse3163
```

**Comment by gavD** [comment]
I don't know if this is relevant, but I'm using a `ref` also, the sidecar logs show `refspec=delete-env-v2` (I am working in a branch)

**Comment by krancour** [comment]
`BRIGADE_SCRIPT` doesn't look right. It's supposed to be relative to the root of the repo.

**Comment by gavD** [comment]
OK. The script I want to run is in `pipelines/environment-delete/brigade.js` in my repository.

This script looks a bit like:

```javascript
const { events, Group } = require('@brigadecore/brigadier');

events.on('simpleevent', (e, project) => {
  // business logic redacted....
  const group = new Group();
  group.add(slackNotifyFinished);

  // run the jobs
  group.runEach();
});
```

**Comment by krancour** [comment]
Standby... checking something...

**Comment by krancour** [comment]
I stand corrected... you probably _did_ specify a relative path. The controller adds in the leading `/vcs`, so an absolute path gets passed to the worker...

I'm having trouble spotting why this isn't working...

You said that you think the vcs "sidecar" is doing its job. Can we check that somehow?

If `brigade.js` at the root of your project works, can you put a script there that just lists the contents of vcs (_without launching a job to do so_). i.e. Just use JS to list `/vcs` contents.

This would tell us more about what the worker is seeing and how it might differ from what was expected.

**Comment by gavD** [comment]
This code

```
const { events, Group } = require('@brigadecore/brigadier');
const fs = require('fs');
events.on('simpleevent', (e, project) => {
  console.log(fs.readdirSync('/vcs'));
  console.log(`Dir name ` + __dirname);
  console.log(`Dir name ` + process.cwd());
});
```

outputs the list of files in the root of my VCS project, so that is behaving exactly as I would expect it to.

- the folder `pipelines` is visible in the list of files.
- `__dirname` is `/vcs`
- `process.cwd()` is `/home/src`

**Comment by krancour** [comment]
Interesting... this is looking stranger and stranger.

Can you try this, please?

```
console.log("process.env.BRIGADE_SCRIPT: " + process.env.BRIGADE_SCRIPT);
console.log("exists: " + fs.existsSync(process.env.BRIGADE_SCRIPT));
console.log("able to read: " + (fs.readFileSync(process.env.BRIGADE_SCRIPT, "utf8") != ""));
```

**Comment by gavD** [comment]
```
process.env.BRIGADE_SCRIPT: /vcs/pipelines/environment-delete/brigade.js
exists: false
[brigade:app] {   [0m[97m[41mError[0m[90m:[0m[37m [0m[97mENOENT: no such file or directory, open '/vcs/pipelines/environment-del[0m  [0m[97mete/brigade.js[0m
```

I can't understand why it can't see it... If I change the brigadejsScript to 'pls.js' I get a similar result:

```
process.env.BRIGADE_SCRIPT: /vcs/pls.js
exists: false
[brigade:app] {   [0m[97m[41mError[0m[90m:[0m[37m [0m[97mENOENT: no such file or directory, open '/vcs/pls.js
```

however this might be telling:

``` 
errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/vcs/pls.js\n'
```

Notice the `\n`

If I add `trim()` calls then the code you supplied works fine, ergo *my brigadejsScript has a trailing newline*, but I can't see where it's coming from

**Comment by gavD** [comment]
*Ahh I finally got it working!!*

```
$ echo 'pls.js' | base64
cGxzLmpzCg==
$ echo -n 'pls.js' | base64
cGxzLmpz
```

The latter works correctly. I'm sorry for taking up so much of your time, and thank you so much for helping me to diagnose this.

It may be worth doing a `trim` on the supplied values, particularly as they're base64 encoded so I didn't spot the newlines I was introducing using `echo`.

**Comment by krancour** [comment]
No worries at all. I'm glad you got this working!
