### ISSUE TITLE
brigade does not support other than the master branch

### ISSUE THREAD

**Issue by kenotsolutions** [brigadecore/brigade#1063]
**Brigade does not support other than the master branch**

Developers can work on different branches and they might need to use the brach pipeline. For example, 3 developers can work on a project and they can work on dev1 to dev3 git branch and might create 3 different namespaces with to test their code. But brigade gets the code from the master branch. We could use "git pull" after vsc-sidecar works but it would increase the building time adding extra steps in the next job.  brig should accept a parameter that allows us to use the branches 

Output of `brig version`: v1.2.1

Output of `kubectl version`: v1.15.6

**Comment by krancour** [comment]
I am unopposed to a more immediate fix for this being explored if someone wants to take it on, but I did want to mention that this limitation _will_ be addressed by the forthcoming Brigade 2.0 proposal.

**Comment by kenotsolutions** [comment]
brig run -r is solved the problem
