### ISSUE TITLE
Brigade generic gateway should return build id

### ISSUE THREAD

**Issue by TheTFo** [brigadecore/brigade#1064]
Output of `brig version`: v1.2.1

Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
AWS EKS

My team identified a drawback of using brigade via http, which was that they weren't able to get the build id from the response. This makes it hard to interrogate data about the running build.

From the code linked below, it looks like that information is swallowed up, and only the error is considered:

https://github.com/brigadecore/brigade/blob/936c4e8eca0269ebd7fb8382be569fea4a8784d8/pkg/storage/kube/build.go#L86

Is there any objection to returning that value, and possible add the build id as a response header? This seems reasonable, and should be backward compatible.

Thanks!

**Comment by krancour** [comment]
Overall-- a reasonable ask.

> Is there any objection to returning that value

Minor objection to _returning it from the store, specifically..._ the storage code referenced above is part of a stable API used by all existing gateways. Modifying what it returns would be a breaking change...

But that function takes a pointer as an argument, so the UUID it assigns to the build should be accessible after the call to `CreateBuild(...)`.

> add the build id as a response header?

This or something like it (I might prefer a new field in the response) seems reasonable, but isn't supported by this gateway's current implementation. For some reason, I'm not familiar with, the generic gateway _always_ responds with a 200 and carries on, asynchronously, with the business of creating the build. This means we don't have the build ID before the response is sent-- and worse, this seems it may be error prone... you could be told a build was created successfully, when in fact build creation has failed or hasn't completed yet.

I'm not sure why it was done this way. Maybe another maintainer can provide some historical context. I will assume there was a reason for this that I am not aware of.

I do think the feature request is doable, but let's get a handle on the above before we decide how to proceed.

cc @radu-matei  @vdice @technosophos

**Comment by FreakTheMighty** [comment]
Any updates on this? @TheTFo, we have a very similar need, did you find a work around?

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
