### ISSUE TITLE
Missing ref fails are hard to trace through Kashti

### ISSUE THREAD

**Issue by gavD** [brigadecore/brigade#1065]
Via an API layer, our users post `simpleevent`s to Brigade. They can specify `ref` to select a custom branch (for feature testing).

However, if they make a typo in the branch name, the `vcs-sidecar` fails after 5 attempts, which is fine, but on Kashti I see:

![image](https://user-images.githubusercontent.com/205245/77051354-0ca68400-69c3-11ea-8dc6-16a83e841dd3.png)

- the first event (the one with the red X) is not clickable
- the date shows 2019 for some reason

So, unless our users have access to Kubectl and know about how Brigrade works, they cannot diagnose this case.

Is this an error that could be exposed via Kashti?

Output of `brig version`: `v1.3.0`

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
AWS EKS

**Comment by krancour** [comment]
@gavD you mentioned an "API layer." If you are using a custom API to create events, there are `shortTitle` and `longTitle` fields present on events in the last few releases of Brigade. Most gateways don't set them yet, but they're there.

If you set those, they'll show up in Kashti in place of the long, opaque (and not-so-useful) build IDs.

Is that a useful option you can possibly take advantage of?

**Comment by gavD** [comment]
Thanks @krancour , that sounds like a great idea 👍 

I posted an event that contained :

```json
{
  "shortTitle": "My short title",
  "longTitle": "My long title",
```

but unfortunately it didn't get set. I checked the underlying worker secret and I see:

```
payload:         541 bytes
short_title:     0 bytes
```

I am running `brigade-1.5.0` chart with app version `v1.3.0` . 1.3.0 definitely contains the code for the  shortTitle field. I don't see it documented, am I missing something?

**Comment by gavD** [comment]
Ah, I see these fields are intended to go on the `event`, not on `event.payload`. How could I set those fields? (sorry if I'm missing something obvious!)

**Comment by krancour** [comment]
@gavD, it depends... how are these events entering the system? You mentioned an "API layer."

**Comment by gavD** [comment]
My API layer is in AWS API Gateway using Lambda. Lambda makes an HTTPS post to Brigade

It looks like this:

```javascript
            const response = await post(
                `/simpleevents/v1/${process.env.BRIGADE_PROJECT}/${brigadeSecret}`,
                params // params is the payload we are sending to Brigade
            );
```

(`post` is just a wrapper around https)

```javascript
const post = (path, payload) => new Promise((resolve, reject) => {
    const options = { ...defaultOptions, path, method: 'POST' };
    const req = http.request(options, res => {
        let buffer = '';
        res.on('data', chunk => buffer += chunk);
        res.on('end', () => {
            resolve(JSON.parse(buffer));
        });
    });
    req.on('error', e => reject(e.message));
    req.write(JSON.stringify(payload));
    req.end();
});
```

**Comment by krancour** [comment]
@gavD  is that a cloud event headed for the generic gateway?

**Comment by gavD** [comment]
Looking at Looking at https://docs.brigade.sh/topics/genericgateway/ I'd say that yes I think it is using the "generic gateway". I'm using v1, so I'm using SimpleEvent. If I use v02 could I perhaps get the behaviour you're describing here?

**Comment by gavD** [comment]
I've set up cloudevent listener:

events.on('cloudevent', (e, p) => { // handler for a CloudEvent
    console.log('cloud event e is');
    console.log(e);
    console.log('cloud event p is');
    console.log(p);
});

I'm posting this to it with:

```bash
curl --header "Content-Type: application/json" --request POST --data '@testdata-create-cloud.json' https://<redacted>/cloudevents/v02/brigade-<redacted>/<redacted>
{"status":"Success"}%
```

`testdata-create-cloud.json` contains:

```json
{
  "type":   "com.example.file.created",
  "source": "/providers/Example.COM/storage/account#fileServices/default/{new-file}",
  "id":     "ea35b24ede421",
  "shortTitle": "m-s-t",
  "longTitle": "m-long-t",
  "short_title": "m-s-t-two",
  "long_title": "m-l-t-two",
  "specversion": "0.2",
  "data": {
    "ref": "gateway-changes",
    "commit": "63c09efb6eb544f41a48901a6d0cc6ddfa4adb28",
    "key1": "value1",
    "key2": "value2"
  }
}
```

I get the results:

```
cloud event e is
{ buildID: '01e46a<REDACTED>',
  workerID: 'brigade-worker-<REDACTED>',
  type: 'cloudevent',
  provider: 'GenericWebhook',
  cloneURL: '<REDACTED>',
  revision: 
   { commit: '<REDACTED>',
     ref: '<REDACTED> },
  logLevel: 1,
  payload: '{  "type":   "com.example.file.created",  "source": "/providers/Example.COM/storage/account#fileServices/default/{new-file}",  "id":     "ea35b24ede421",  "shortTitle": "m-s-t",  "longTitle": "m-long-t",  "short_title": "m-s-t-two",  "long_title": "m-l-t-two",  "specversion": "0.2",  "data": {    "ref": "gateway-changes",    "commit": "63c09efb6eb544f41a48901a6d0cc6ddfa4adb28",    "key1": "value1",    "key2": "value2"  }}' }
cloud event p is
......
```

so it seems this doesn't help me - setting longtitle/shortTitle (or any variation thereof) doesn't work for me at this level.

**Comment by krancour** [comment]
@gavD ok... got it. So, as you've already noted, the `shortTitle` and `longTitle` fields that might help you out by making things more human-identifiable are event-level fields and _not_ fields of the event payload.

If you're submitting events through the generic gateway (which, I believe does use Cloud Events; it's an area of the system I am less familiar with) there is not opportunity for you to set those `shortTitle` or `longTitle` fields there.

If you're interested in setting those fields, what you can do is create your own "gateway." This is a _lot_ less complicated than it sounds. Fundamentally, all Brigade 1.x events are simply Kubernetes secrets. Whatever code you are using to submit the Cloud Event to the generic gateway can, in a sense, become a "gateway" itself by simply writing event secrets _directly_ to Kubernetes-- bypassing the generic gateway completely.

All you would need to do is make sure the code in question has credentials for your cluster with permissions to create secrets in the Brigade namespace. If you happen to be using Go, there's a "storage" package that should make it a snap to actually write the event secret out to Kubernetes and it should let you set those fields.

**Comment by gavD** [comment]
thanks! I follow that. Thank you for explaining :-)

**Comment by krancour** [comment]
@gavD glad that made sense. Do let me know how it turns out!
