### ISSUE TITLE
Brig project create on v1.18.2

### ISSUE THREAD

**Issue by kenotsolutions** [brigadecore/brigade#1076]
Hi,
We use brigade on v1.15.6 cluster and we would like use also on Kubernetes v1.18.2 the brig commands work without any problem on v1.15.6 but we get errors onv1.18.2

**brig project create test -n brigade**
 
E0505 15:28:58.693842   17603 reflector.go:205] github.com/brigadecore/brigade/pkg/storage/kube/apicache/liststore.go:36: Failed to list *v1.Pod: v1.PodList: Items: []v1.Pod: v1.Pod: ObjectMeta: v1.ObjectMeta: readObjectFieldAsBytes: expect : after object field, parsing 1167 ...:{}

> brigade-api uses image: brigadecore/brigade-api:v1.4.0
> brigade-ctrl uses image: brigadecore/brigade-controller:v1.4.0

Output of `kubectl version`:
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", 
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2"

Output of `brig version`:v1.2.1

Cloud Provider/Platform (AKS, GKE, Minikube etc.): custom

```

briagde-api logs 
W0505 15:11:00.543098       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
2020/05/05 15:11:00 Get the API using :7745/apidocs.json
   XXX - - [05/May/2020:15:11:03 +0000] "     GET  /healthz HTTP/1.1"  200  4
   XXX - - [05/May/2020:15:11:04 +0000] "     GET  /healthz HTTP/1.1"  200  4
   XXX - - [05/May/2020:15:11:13 +0000] "     GET  /healthz HTTP/1.1"  200  4
   XXX - - [05/May/2020:15:11:14 +0000] "     GET  /healthz HTTP/1.1"  200  4
   XXX - - [05/May/2020:15:11:23 +0000] "     GET  /healthz HTTP/1.1"  200  4
    
brigade_ctrl logs 
W0505 15:05:16.090535       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
main.go:61: Listening in namespace "brigade" for new events
controller.go:146: Starting Secret controller
informer.go:32: Adding to workqueue:  brigade/brigade-wXXX
controller.go:108: Executing on Secret: brigade-worker-0XX

```

**Comment by vdice** [comment]
Please try again after also upgrading the `brig` CLI to `v1.4.0` (the CLI binary can be downloaded from the release page https://github.com/brigadecore/brigade/releases/tag/v1.4.0, or built from source)

The k8s client libraries that the CLI uses needed updating for compatibility with v1.18.x.

**Comment by kenotsolutions** [comment]
Yes, It fixed the issue,

Thanks @vdice
