### ISSUE TITLE
worker with private repo

### ISSUE THREAD

**Issue by kenotsolutions** [brigadecore/brigade#1077]
Hi,

This is my class for it. It works with a public repository ("alphine:latest") but I would like to use it a private repo.  But it fails because of the private repository credentials. I could not find where to add it. I have a secret for it. The secret is vaild.

I get "pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" error. 

Where should I set the secret for the private repository? 

brig project get test -n brigade
secrets: '{"docker_harbor":"base64 secret"

       ```
class test extends Job {
    constructor(JOB_NAME, event, project) {
      GLB_REPOSITORY_NAME="harbor.test.com/imagename:V96184"

      super(JOB_NAME, GLB_REPOSITORY_NAME);
      this.storage.enabled = false
      this.imagePullSecrets=project.secrets.docker_harbor
      this.privileged = true
      this.streamLogs=true
      this.tasks = [

```
Output of `brig version`:
943d43e
Output of `kubectl version`:
1.15.6

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Bare metal custom.

**Comment by vdice** [comment]
Hi @kenotsolutions .  I think the ability to add image pull secrets to a given job is functioning correctly, but there are a couple points to double-check:

1. The secret(s) assigned to `job.imagePullSecrets` are the _names_ of the Kubernetes secrets expected to already exist in the cluster.
2. When creating the Kubernetes secret in the cluster, be sure to assign a value to the `--docker-server`.  (This tripped me up when vetting this functionality just now; if not set, `https://index.docker.io/v1/` will be the registry used and thus auth will fail).

For example:
```shell
$ kubectl create secret docker-registry my-registry-secret \
  --docker-email=myemail \
  --docker-password="${DOCKER_PW}" \
  --docker-username=myusername \
  --docker-server=myprivateregistry
```
And then we would assign this registry secret name to the job like so:
```javascript
myjob.imagePullSecrets = ["my-registry-secret"];
```

Can you please re-try when convenient?

**Comment by kenotsolutions** [comment]
myjob.imagePullSecrets = ["my-registry-secret"]; solved the problem

**Comment by tomfotherby** [comment]
Also, make sure your `docker-registry` secret is in the correct **namespace**. For me I had to create it for the `brigade` namespace ([ref](https://github.com/brigadecore/brigade/issues/566#issuecomment-691107010)).
