### ISSUE TITLE
brig: Use kube-context instead of default namespace 

### ISSUE THREAD

**Issue by waveywaves** [brigadecore/brigade#1083]
When running `brig check`, `brig project list` etc. `brig` should take in consideration the current kube context we are running in so that we don't have to provide the `-n` flag for namespace everytime
## Actual Output

```
$ brig check
Info: Brigade API Server Deployment not foundError: Brigade Controller Deployment not found                                                                                      
Info: Kashti deployment not found
```
```
$ brig project list
NAME    ID      REPO
```

## Expected Output

```
$ brig check
(Reaally loong output)
```
```
$ brig project list
NAME                            ID                                                              REPO                                                                             
waveywaves/brigade-hacks        brigade-xoxo  github.com/waveywaves/brigade-hacks
```

Output of `brig version`:
v1.2.1
Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
Minikube

**Comment by vdice** [comment]
It would be neat to defer to the namespace set on a current kube context.  I've added the enhancement label for this.

In the meantime, you can export an env var value for `BRIGADE_NAMESPACE`.  `brig` will use this as a namespace override.  This is a handy way to use a non-default ns for a terminal session with `brig` without having to (re-)specify via the `-n` flag, etc.

**Comment by krancour** [comment]
I agree this could be a convenient change for some, but since it would change the default behavior when the `-n` flag is not specified, wouldn't it amount to a breaking change?

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
