### ISSUE TITLE
Not able to trigger push event

### ISSUE THREAD

**Issue by d46** [brigadecore/brigade#1087]
Hello everyone, thank you for your great product! I several times tried to use brigade but stuck every time at the same step. The issue is about not triggering push events in brigade.js. I've set up Github hooks successfully then able to receive events on `gh-app` and `brigade-ctrl` pods. `brigade-ctrl` start workers but push events are not triggering on `brigade-worker`. I have tested on different versions but didn't success to trigger push event over Github flow. When I'm trying to do that by using `brig-cli` and adding `-e push` it is easily accomplishing push events. 

After creating a project I'm running.
```bash
brigade run project-name -f brigade.js
```
```js
// brigade.js
const { events } = require("brigadier");

events.on("push", function(e, project) {
  console.log("received push for commit");
});

events.on("exec", function(e, project) {
  console.log("received Exec");
});
```
Logs on the `brigade-ctrl`
```bash
main.go:64: Listening in namespace "brigade" for new events
controller.go:139: Starting Secret controller
informer.go:31: Adding to workqueue:  brigade/brigade-worker-01e938vjh8cw4kv9re3r1gv4xq
controller.go:101: Executing on Secret: brigade-worker-01e938vjh8cw4kv9re3r1gv4xq
handler.go:43: EventHandler: type=exec provider=brigade-cli commit=
handler.go:67: Started brigade-worker-01e938vjh8cw4kv9re3r1gv4xq for "exec" [] at -62135596800
```

Everything looks fine. The worker starts and dumps as it supposed to be.
```bash
prestart: no dependencies file found
[brigade] brigade-worker version: 1.2.1
[brigade:k8s] Creating PVC named brigade-worker-01e93a4yxh3943e82e0chrr31n
received Exec
[brigade:app] after: default event handler fired
[brigade:app] beforeExit(2): destroying storage
[brigade:k8s] Destroying PVC named brigade-worker-01e93a4yxh3943e82e0chrr31n
```
It is logging the `received Exec`.

Now I'm trying to run with brigade passing with event push
```bash
brigade run project-name -f brigade.js -e push
```

It is also responding well
```bash
informer.go:31: Adding to workqueue:  brigade/brigade-worker-01e93a715y163hmjc244j84k3j
controller.go:101: Executing on Secret: brigade-worker-01e93a715y163hmjc244j84k3j
handler.go:43: EventHandler: type=push provider=brigade-cli commit=
handler.go:67: Started brigade-worker-01e93a715y163hmjc244j84k3j for "push" [] at -62135596800
```

But when I'm pushing a new commit to the repo. `brigade-ctrl` dumps

```bash
controller.go:101: Executing on Secret: brigade-worker-01e93accafva0cfk2zz9mtcb7c
handler.go:43: EventHandler: type=push provider=github commit=278c90115459c22392bba54a5e63f35b47c2c894
handler.go:67: Started brigade-worker-01e93accafva0cfk2zz9mtcb7c for "push" [278c90115459c22392bba54a5e63f35b47c2c894] at -62135596800
```

and worker dumps

```bash
prestart: no dependencies file found
[brigade] brigade-worker version: 1.2.1
[brigade:k8s] Creating PVC named brigade-worker-01e93accafva0cfk2zz9mtcb7c
[brigade:app] no-after: fired
[brigade:app] beforeExit(2): destroying storage
[brigade:k8s] Destroying PVC named brigade-worker-01e93accafva0cfk2zz9mtcb7c
```

I can't see the log `received push for commit`. The only difference in the values.yml (ylms between executed from CLI and Github) is provider field ` github <-> brigade-cli `.  What am I missing? Why push is not triggering?

Output of `brig version`: 1.4.0

Output of `kubectl version`:  server 1.17 - client 1.15

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
Digitalocean

**Comment by krancour** [comment]
@d46 I notice that every time you trigger an event using the CLI, you're including the -f option and pointing it at a local `brigade.js` file whose contents then become part of the event and get used by the worker.

When you have the _actual_ push event coming from GitHub, no such thing happens. In that case, the `brigade.js` file is supposed to be retrieved _from_ GitHub.

So my two questions for you:

1. Does your GitHub repository in question include an appropriate `brigade.js` file?
2. Is your Brigade project properly configured as a "VCS project" and configured with the correct details for your repository-- clone URL, etc., etc.?

**Comment by d46** [comment]
Thanks a lot. Adding `brigade.js` to the repository solved my issue. I was thinking that the `brigade.js` storing somewhere in the secrets. Also missed out the info at docs. [create-a-brigade-js-file](https://docs.brigade.sh/intro/tutorial04/#create-a-brigade-js-file)
