### ISSUE TITLE
brigade build-id fetch/set api for cloudevent

### ISSUE THREAD

**Issue by mathnitin** [brigadecore/brigade#1089]
brig version: v1.1.0

kubectl version: v1.14.10

Cloud Provider/Platform (AKS, GKE, Minikube etc.): AWS

We are trying to find a way to customize/set/fetch the build-id for the worker per run. We are sending a cloudevent request using curl and it does not return the build-id. This is needed as we want to identify which worker is attached to which post request. 

We do see a Build level environment variable "BRIGADE_BUILD_ID", but could not find an example to set this from curl post request.

Can someone please help with this. 

FYI, we do see there is a similar open issue to return the build-id for generic events. https://github.com/brigadecore/brigade/issues/1064

**Comment by mathnitin** [comment]
Thanks. Any other way we can link curl post to worker pod created?

**Comment by krancour** [comment]
I think the changes proposed in #1064 seem reasonable. I don't have the bandwidth to implement that, but I would prioritize reviewing it if anyone wanted to work on it.

**Comment by mathnitin** [comment]
Dupe of https://github.com/brigadecore/brigade/issues/1064
