### ISSUE TITLE
Missing BRIGADE_REMOTE_URL env var in vcs-sidecar

### ISSUE THREAD

**Issue by phsteve** [brigadecore/brigade#1091]
Hello! Overall my team is really enjoying Brigade, so thanks for the great work on the project. Occasionally we see Brigade job pods fail with `Init:Error`. It appears that it's because the `vcs-sidecar` initContainer has `BRIGADE_REMOTE_URL` unset. Usually, other job pods that get triggered in the same run do have it set, but sometimes multiple job pods are missing the `BRIGADE_REMOTE_URL` env var. I have not been able to reproduce it reliably but it happens enough that we see it multiple times per day. These jobs are getting triggered via the Brigade GitHub app.

Some output showing the issue:

```
$ kubectl get po -n brigade my-cool-job-name-01eajat0gfssdw4rj709j5vf8z -o yaml | grep -C2 BRIGADE_REMOTE_URL
    - name: BRIGADE_PROJECT_ID
      value: brigade-f3ca51b565106d4e10880035523a5d8926c6ad8dd1af7a18017f97
    - name: BRIGADE_REMOTE_URL
    - name: BRIGADE_WORKSPACE
      value: /src
```

which causes the script that `vcs-sidecar` runs to error (note the missing parameter to `git ls-remote`, which is also missing in subsequent snipped `git` commands):

```
$ kubectl logs -n brigade my-cool-job-name-01eajat0gfssdw4rj709j5vf8z -c vcs-sidecar
+ : 46db47e605d899725da46a29f4b0f5a60703a8c7
+ : brigade_test_alpha
+ : /src
+ refspec=brigade_test_alpha
+ cut -f2
+ git ls-remote --exit-code  brigade_test_alpha
fatal: No path specified. See 'man git-pull' for valid url syntax
+ full_ref=
+ git init -q /src
+ cd /src
<snip>
```

Any tips on where to go next to debug this or ideas of what could be going wrong?

Output of `brig version`: v1.2.1

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-879c36", GitCommit:"879c3621692a32b5d77a951ca0e61ee55aefc80f", GitTreeState:"clean", BuildDate:"2020-02-21T18:09:01Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): EKS

**Comment by krancour** [comment]
> Output of `brig version`: v1.2.1

@phsteve the above is just the client version. Would you also be able to tell me the version of the cluster-side components?

[This is where that env var gets set.](https://github.com/brigadecore/brigade/blob/579d22e235303704379e8438ab291bf419162919/brigade-worker/src/k8s.ts#L848-L855)

The value for the `BRIGADE_REMOTE_URL` env var comes from the `cloneURL` field on the event. If that's not set, it falls back to the value of the project-level `cloneURL`.

Can you please check whether this information is present or absent in each of those places?

**Comment by phsteve** [comment]
> Would you also be able to tell me the version of the cluster-side components?

We have the `brigade-1.5.0` chart deployed with app version `v1.3.0`.

> check whether this information is present or absent in each of those places?

Sure thing! `cloneURL` is set on the project secret to the correct URL, and the brigade-worker pod's `vcs-sidecar` container has it set as an env var as well. One of the job pods' `vcs-sidecar` does not have it set but the others do. Also, I see the payload from github in the `brigade-worker` secret has `clone_url` set to the correct URL.

**Comment by krancour** [comment]
@phsteve great info. Thanks! I can dig a little deeper into this tomorrow morning. Something does seem fishy here.

**Comment by krancour** [comment]
@phsteve out of curiosity, I'm wondering if you see any correlation at all between those failures and the node(s) those failures are occurring on.

**Comment by jeffrom** [comment]
Just chiming in to say we are waiting to see this issue again to get some context on node state, but in lieu of that, here are a few potential variables (waving hands profusely):

- we've noticed that the missing env vars seem to be correlated with kube cluster autoscaler scale up/down (we use pretty default autoscaler settings). 
- around the time we noticed this issue, we were using our ebs burst balance frequently on kube workers, causing disk io failure and throttling.
- we recently upgraded the cluster from 1.13 to 1.14.9 (managed eks) around the time we noticed the env var issue.

hopefully we'll catch this bug in the act soon and can give more specific information (we're scaling up to support brigade and various scalability issues are being exposed at the moment).

**Comment by krancour** [comment]
@jeffrom interesting observations-- all of which would point to a comparatively more disturbing Kubernetes bug. (Though I don't want to jump to conclusions.)

On my end, I've scoured the code and don't see how two jobs started by the same worker could ever have `BRIGADE_REMOTE_URL` set for one's init container and not the other.

**Comment by jeffrom** [comment]
I agree the code looks pretty straightforward here. I don't have a systematic view of this, but i did just get a chance to check on a node where an env var was missing (it was for the BRIGADE_COMMIT_REF on a worker 😬), and the node was afaict in a good state, not recently created or being drained by cluster autoscaler... I'm wondering if there's a consistency issue hiding somewhere, but in general i'm pretty stumped :)

**Comment by krancour** [comment]
Fast forward seven months and I have finally witnessed this personally and remain every bit as stumped now as I was when this was first reported.

**Comment by krancour** [comment]
Ok... I don't have the final answer, but I have some good data points...

We fall back on `project.repo.cloneURL` only when `e.cloneURL` is `""`. Well-- sometimes `e.cloneURL` is `undefined`. `undefined != ""`. In this case, the fallback doesn't happen and we proceed with launching a job with a git initializer container that receives undefined as the remote URL.

How does this happen?

So far, I have _only_ seen it happen when there are _other_ unhandled failures (code errors) in my `brigade.js` script.

So I am inclined to infer that something in the worker's own error handling code, which I have not identified yet, is mutating the event and wiping out the value of the event's `cloneURL` field.

**Comment by krancour** [comment]
Encountered this about a dozen times more today. In every case, there was something wrong with the script. In most cases, the error that precipitated it was obvious if I studied the stack trace just a littler longer. This behavior, however, is still unexpected and wrong, even in the event of an error.

**Comment by jeffrom** [comment]
@krancour that tracks w/ what i've seen, with that caveat that i've also (mostly) seen it when my brigade.js is error-free. my theory was that something about our k8s cluster config (we've got a relatively old cluster, migrated from kubeadm to eks, long story short there are some twists and turns). we added a workaround to our git sidecar to fall back to the project secret clone url, which is fine for our needs, so apologies, i haven't thought about this too much since then, though i'm still curious about it :)

**Comment by krancour** [comment]
@jeffrom, I'm reasonably sure I pinned it down...

Something unrelated jogged my memory and I now recall that somewhere in the worker code there's a _global_ `currentEvent` variable that is set whenever an event is dispatched. _If an error occurs, a new error event is dispatched and it overwrites the previous value of that variable._

If, concurrent with the error handling, a new Job is being launched, there's a race condition. Your new job can end up with a git init container with the `BRIGADE_REMOTE_URL` env var set to the value of a field that's _undefined_ on the new error event in `currentEvent`.

I haven't looked at this code recently, so I don't know off the top of my head what's involved in fixing it. I just wanted to make sure this new insight was at least documented.

(Aside: The worker in the `v2` branch, like like everything else in that branch, is a complete rewrite and doesn't suffer from this issue.)

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
