### ISSUE TITLE
VACUUM_AGE

### ISSUE THREAD

**Issue by kenotsolutions** [brigadecore/brigade#1092]
I see newly created running workers are being deleted by vacuum cronJob.  Do you have any idea about it?  VACUUM_SKIP_RUNNING_BUILDS I could not find a document about it.  Is it related to the behaviour?

    `obTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: brigade-vacuum
        spec:
          containers:
          - env:
            - name: VACUUM_AGE
              value: 360h
            - name: VACUUM_MAX_BUILDS
              value: "3"
            - name: VACUUM_SKIP_RUNNING_BUILDS
              value: "false"
            - name: BRIGADE_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            image: brigadecore/brigade-vacuum:v1.4.0
            imagePullPolicy: IfNotPresent
            name: brigade-vacuum
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: brigade-vacuum
          serviceAccountName: brigade-vacuum
          terminationGracePeriodSeconds: 30
  schedule: '@hourly'`

`kubectl get pods  -n brigade brigade-worker-XYZ`
brigade-worker-XYZ   0/1     Completed   0          16m

kubectl logs -n brigade brigade-vacuum-abc|grep brigade-worker-XYZ

2020/06/22 22:00:09 Deleting pod "brigade-worker-XYZ"
2020/06/22 22:00:10 Deleting secret "brigade-worker-XYZ"

brigadecore/brigade-vacuum:v1.4.0 

Output of `brig version`: 1.40

Output of `kubectl version`: 1.8

Cloud Provider/Platform (AKS, GKE, Minikube etc.):

**Comment by krancour** [comment]
@kenotsolutions, the chart seems to have `false` as a default value when `vacuum.skipRunningBuilds` is not defined. imo, that's not a great default, but it would be a breaking change to reverse that default.

Reference:

https://github.com/brigadecore/charts/blob/6509b48e9321e1358d0decb4e33f46b8b1cab5b5/charts/brigade/templates/vacuum-cronjob.yaml#L35-L36

At any rate, you can fix this using `--set vacuum.skipRunningBuilds=true` on your next `helm upgrade`. Or set that value in your `values.yaml` file if you have one.

**Comment by kenotsolutions** [comment]
looks like it solved the problem. thanks
