### ISSUE TITLE
Ability to decide where to schedule a Job

### ISSUE THREAD

**Issue by stafot** [brigadecore/brigade#1104]
Proposal
------------
Add the ability to be able to decide where to run a job/pod of the brigade pipeline.
I had in mind something like `nodeSelector` ability to be able to be declared like the follow.
```js
    const { events, Job, Group } = require("brigadier");
    events.on("exec", () => {
    console.log("Starting");
    var job = new Job("job");
    job.image = "alpine:3.12";
    job.tasks = ["echo lala; echo lolo;"]
    job.node = "pipeline-worker" //or an alternative more similar to k8s syntax could be job.nodeSelector = "pipeline-worker"

    job.run();
    console.log("Finished");
    })
 
```

Background
---------------
This could help to workaround to some provider-wise limitations on sharing storage. For example this way you might be able to  bypass the `AWS-EBS` `accessMode` limitation which doesn't support `ReadWriteMany` access.

Also this way you can schedule different workloads with different resources needs to different instance types and be more cost efficient.

**A use-case scenario:** Run a powerful "pipeline-worker" that could co-host all the pipelines avoiding cause churn to other cluster workloads.

**Comment by krancour** [comment]
Hmmm... this might not have been adequately documented, but it can already be done.

https://github.com/brigadecore/brigadier/blob/master/src/job.ts#L124

Also, there's an open PR (#1095) aimed at letting operators specify this as well so that they can enforce worker/job placement across the board without every `brigade.js` author having to be cognizant of _where_ their jobs should run.

**Comment by krancour** [comment]
@stafot I see the heart. Did that link get you moving?

**Comment by krancour** [comment]
> Anyway, I should check the code next time before opening feature request.

You shouldn't have to. I'm going to close this issue, but open a new one to get the docs fixed.

**Comment by stafot** [comment]
Agree.
