### ISSUE TITLE
Document job placement options using node selectors

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1105]
This is supported, but absent from the documentation.

**Comment by stafot** [comment]
Is it ok to try to propose a PR for this @krancour? I am seeing it as opportunity to see all options offered by `Job` brigade resource.

**Comment by krancour** [comment]
By all means. btw... credit goes to @stafot for the discovery that this wasn't documented to begin with.

**Comment by stafot** [comment]
@krancour 
While my addition looks fine on the `.md` [file](https://github.com/brigadecore/brigade/blob/master/docs/content/topics/javascript.md) is ugly and a bit unreadable on the site. Looks as inconsistency between github's md syntax and site's. 
**Check attachments.**
Good:
![fine_on_github](https://user-images.githubusercontent.com/2853082/87762943-8ee17080-c81c-11ea-9990-a2a264d1de3a.png)
Bad:
![ugly_unreadable_on_site](https://user-images.githubusercontent.com/2853082/87762939-8e48da00-c81c-11ea-9365-560f4ed34c3d.png)
