### ISSUE TITLE
brig export project and create from it fails with the version 1.40

### ISSUE THREAD

**Issue by kenotsolutions** [brigadecore/brigade#1111]
Hi,

I created a VCS project with `brig version`: 1.40  It is a kind of template project. I exported the project as a yaml file and made the changes and tried to create a new project from the yaml file.

`brig project get temp-project -n brigade -o yaml  >brig.yaml`

 I changed below parameters with the  new one
projectName: 
name: brigade-XYX. ( I know what will be the project name)
repository: 

`brig project create -f brig.yaml -n brigade `

I was able to create the brig project version brigade v1.2.1 with the same method but now I get

Error: secret in brig.yaml is missing required name field

`brig project replase -f brig.yaml -n brigade ` also doesn't work.

Can you please check it?

Output of `brig version`: 1.40

Output of `kubectl version`: 1.18.2

Cloud Provider/Platform (AKS, GKE, Minikube etc.): bare metal

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
