### ISSUE TITLE
Brigade worker times out periodically during start up

### ISSUE THREAD

**Issue by FreakTheMighty** [brigadecore/brigade#1117]
After upgrading kube to `1.16.10` we started to get periodic timeouts when a brigade worker starts up. It happens very frequently, but not all the time. Any help resolving this would be much appreciated.

![image](https://user-images.githubusercontent.com/247092/93099143-5075ff80-f66d-11ea-9cf9-ef181950e0dc.png)

### Output of `brig version`:

`1.3.0`

### Brigade Helm Chart Version
`brigade         default         1               2020-07-14 15:19:52.45275796 +0300 EEST         deployed        brigade-1.6.0           v1.4.0`

### Output of `kubectl version`:

v1.16.10

### Cloud Provider/Platform (AKS, GKE, Minikube etc.):

Azure

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
