### ISSUE TITLE
ci: authentication required prior to pulling images from DockerHub

### ISSUE THREAD

**Issue by bacongobbler** [brigadecore/brigade#1124]
Starting November 1, 2020, Docker Hub will impose rate limits based on the originating IP. Since Brigade pulls down images from DockerHub when Jobs are invoked, it is highly recommended to use authenticated Docker pulls with Docker Hub to avoid rate limit problems.

https://docs.docker.com/docker-hub/download-rate-limit/
https://www.docker.com/pricing

By default, DockerHub limits anonymous pull access to 100 pulls per hour, per IP. When logged in with a free account, it's bumped to 200 per hour. Pro/Team accounts allow unlimited pulls.

https://github.com/brigadecore/brigade/blob/66dfceb3de22d5a735615d82d31077bf6a512a12/brigade.js#L23
https://github.com/brigadecore/brigade/blob/66dfceb3de22d5a735615d82d31077bf6a512a12/brigade.js#L39
https://github.com/brigadecore/brigade/blob/66dfceb3de22d5a735615d82d31077bf6a512a12/brigade.js#L68
https://github.com/brigadecore/brigade/blob/66dfceb3de22d5a735615d82d31077bf6a512a12/brigade.js#L151

There are two solutions:

1. migrate to another "hub" without this rate limit like [Github Container Registry](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/about-github-container-registry)
2. log in to DockerHub before starting the job, using the same credentials used to push images during `buildAndPublishImages`:

https://github.com/brigadecore/brigade/blob/66dfceb3de22d5a735615d82d31077bf6a512a12/brigade.js#L75

I'd also highly recommend reviewing any other projects consuming a brigade.js and audit for any images pulled from DockerHub.

**Comment by krancour** [comment]
@bacongobbler thanks for the heads up on this.

Seems a third alternative would be to use a pro account for the pulls. My account happens to be pro.

@vdice when you're back, let's work together on adding an image pull secret to our cluster with my Docker Hub creds.

**Comment by vdice** [comment]
@krancour and I worked together to update Brigade's dogfood cluster with an image pull secret using an account with unlimited pulls.  Thank you for the issue, @bacongobbler !
