### ISSUE TITLE
Login confirmation splash page

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1131]
In 2.0, with OpenID Connect enabled, the login workflow for a CLI user is this:

1. `brig login --server https://location`
2. API server sends back unactivated token and URL to third party identity provider
3. User completes authentication in their browser using the provided URL
4. Identity provider redirects to API server-- token gets activated
5. API server redirects user to page that confirms their login-- informs them they may resume using the CLI

Currently, no. 5 above is plain text, but it deserves to be spruced up.

This issue requests an attractive "splash page" to confirm login and inform the user they may resume using the CLI.

Near term, assets like HTML, CSS, and JS (if applicable) can be dropped in project path `v2/apiserver/assets`. Longer term, a separate PR can incorporate those assets into the API server.

**Comment by vdice** [comment]
Looks like this was addressed in https://github.com/brigadecore/brigade/pull/1449; closing!
