### ISSUE TITLE
Implement new git init image

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1134]
The Brigade 2.0 prototype reused the Brigade 1.x git init image. (Erroneously known previously as the "vcs sidecar".)

That image is configured by setting a _lot_ of environment variables. That's not entirely ideal because it makes it somewhat onerous to implement a custom image. More to the point, a lot of those env vars are pretty specific to git. Supposing we someday wanted to add support for a different VCS, like Mercurial, many of those env vars wouldn't be used, and new ones would be needed. Documenting all of this would be somewhat of a nightmare.

I'd prefer to take a cue from how the 2.0 (prototype) worker works. Instead of receiving configuration as environment variables, the entire event JSON is mounted into the container and the worker (or VCS init container in this case) can extract whatever information it needs from the event-- simple.

The existing git init image ("vcs sidecar") is implemented as a bash script that uses the git cli. Unmarshaling the event JSON in a bash script might be doable with something like `jq`, but it might be easier to switch from using bash to implement this image to using Go, TypeScript, or JavaScript instead. (Go would produce the smallest image, which might be desirable here.)

**Comment by vdice** [comment]
Implemented in https://github.com/brigadecore/brigade/pull/1238; closing.
