### ISSUE TITLE
pending and running "child" jobs should get appropriate status updates when a running worker is aborted

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1191]
When a running worker is canceled, its status changes to aborted.

A running worker could have associated jobs that are either pending or running.

We _do_ already kill these on the substrate when the worker is canceled, but we're not currently doing any status updates on those jobs in the db to reflect that they were canceled (if pending) or aborted (if running).

This should be fixed.

**Comment by vdice** [comment]
This is closed by https://github.com/brigadecore/brigade/pull/1275
