### ISSUE TITLE
k8s resource name length limits

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1195]
Because we incorporate UUIDs into things like namespace names, secret names, and pod name, and because UUIDs are rather long, we might be flirting with bumping up against resource name length limits (if they exist) in cases where users choose long project names, job names, etc.

Research is required.

Once the limits are understood, we can adjust the apiserver's JSON schemas to enforce length limits on thing like project names, job names, etc. such that we avoid any issues.

**Comment by krancour** [comment]
For reference: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/

It would seem even with the current (generous) length limits we have placed on projects, job names, etc., we're not in any danger of running over the limit (253 characters) by appending those to a UUID.

**Comment by krancour** [comment]
This does mean, we can possibly entertain larger length limits.

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1392
