### ISSUE TITLE
Add clone command

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1196]
1.x had `rerun`. I've always envisioned something similar in 2.0 like `brig event clone --id <event id>`.

**Comment by vdice** [comment]
Here are the current options for v1's `brig rerun`:
```
  brig rerun BUILD_ID [flags]

Flags:
  -b, --background       Trigger the event and exit. Let the job rerun in the background.
  -c, --commit string    A VCS (git) commit
      --config string    The brigade.json config file
  -e, --event string     The name of the event to fire
  -f, --file string      The JavaScript file to execute
  -h, --help             help for rerun
  -l, --level string     Specified log level: log, info, warn, error (default "log")
      --no-color         Remove color codes from log output
      --no-progress      Disable progress meter
  -p, --payload string   The path to a payload file
  -r, --ref string       A VCS (git) version, tag, or branch
  ```
  
For this first implementation, which of these do we want to ensure we have?

I'd propose `-c/--commit`, `-r/--ref` and `-f/--file`.  (Where `-e/--event/-i/--id` is the given/necessary flag to designate the event id to clone)

**Comment by krancour** [comment]
What's the utility in -c, -r, and -f? i.e. If someone is looking to _clone_ an event, why do they want to change details of the event? Is it that really a clone even if they are _changing_ details? Or is it simply a brand new event at that point?

To a certain extent, I have reservations about this functionality. I proposed it for some kind of "parity" with v1.x, but I guess I'm still generally skeptical of the notion of users creating events (other than cli:exec).

Painting a scenario for you:

Imagine that an event from system X comes into Brigade via an X-gateway. The X-gateway legitimately produces an event with certain values in the source and type fields. Should an end-user really be _allowed_ to copy the event and mutate details in the process, producing what is essentially an entirely new event that looks like it came from a particular gateway, but didn't?

I'm not arguing anything one way or the other here, but I do think we need to think through these things and have a clear position on them. If, for instance, we were to begin allowing what's described above, I think we need to add new fields to record the progeny of an Event. i.e. This event's source _says_ it's from X-gateway, but another field denotes that really vdice created it. Just thinking out loud.

**Comment by vdice** [comment]
Good thoughts for sure.  I know I've found it really helpful to re-run an event with a different file (brigade.js) after discovering a bug in the brigade.js file used for the original event.  Say, the original event was a tag push that kicked off various release pipelines, but it failed due to an aforementioned bug somewhere in the pipeline.  It was really handy to re-use that event (and all of the GH webhook's payload) and re-run with bug fixed (hopefully!) via a new brigade.js.  I can't immediately come up with an example regarding changing commit/ref -- but the ethos behind those on v1's `brig rerun` was to have flag parity with `brig run` as I recall (which doesn't necessarily address any of the reservations you've just mentioned, of course.)

However, since we don't have any of those flags on v2's `brig event create`, I can be persuaded to punt on this discussion until we start considering whether to even add them to `event create`.  In that case, shall we just move forward with a vanilla `brig clone -e/--event/-i/--id <event id>` that clones the event from the original and runs with latest battle plan (most recent WorkerTemplate per the project)?

**Comment by krancour** [comment]
> I know I've found it really helpful to re-run an event with a different file (brigade.js) after discovering a bug in the brigade.js file used for the original event.

Greate insight into the utility of this. I'm wondering if there is possibly a better way to troubleshoot those scenarios in v2.

One thing that springs to mind is that we recently added the requirement of a line like `events.process();` at the end of your `brigade.js` to kick off event-handling. The reason for the change was to separate your script from the rest of the worker so that they're two separate, standalone processes that can each have their own distinct set of dependencies. One of the incidental benefits of that was that it's possible to "smoke test' a `brigade.js` (or `brigade.ts`) by executing it locally. This may make the class of bug you're talking about less likely to occur in the first place, and may also make it easier to troubleshoot such issues they do occur.

Here's a real, already working example of how you can do this kind of troubleshooting:

```
$ cd $BRIG/examples/10-kitchen-sink/.brigade
$ cat event.json # An event in a file
{
  "id": "d1c9a284-8cb0-47b0-b367-b77230925c6a",
  "source": "brigade.sh/cli",
  "type": "exec",
  "project": { "id": "e30b668a-0d1c-4604-a969-800b2ee92676", "secrets": {} },
  "payload": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "worker": {
    "apiAddres": "https://brigade2.example.com",
    "apiToken": "7ae81bbe-2d27-45ee-ad51-18b7f81994dd",
    "configFilesDirectory": ".brigade",
    "defaultConfigFiles": {}
  }
}
$ yarn install
$ tsc brigade.ts
$ BRIGADE_EVENT_FILE=$(pwd)/event.json node brigade.js
```

**Comment by krancour** [comment]
Tangentially related... I found some bugs in the above that I'll address through separate PRs.

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1362
