### ISSUE TITLE
Add retry command

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1199]
Add a `brig event retry` command, where the actual retry logic is handled by the backend EventsClient.

Bubbling up some notes from discussion below:

I'm not tracking down related issues until after I've had my coffee, but we've seen requests before for a "retry" command that skips jobs that succeeded already and retries those that didn't. We've always said that's near impossible to do because our shared storage isn't a layered file system (which seems it would be a tough hill to climb) and that means we don't have the capacity to restore shared state to what it was prior to a job's failure before a job is retried. I think a compromise that we arrived at that did make it into the v2 proposal doc was that we could implement this sort of "retry" specifically for workers/jobs that don't use a volume to share state.

An Event struct has a Worker field and that is its blueprint for how the Event will be processed-- a battle plan if you will. It's constructed from the associated Project's WorkerTemplate. The Event's Worker also aggregates Job states.

We could think of retry as "copy the event and, provided there is no shared state involved, copy the battle plan also; clear the state on failed jobs." We could then amend the logic for Job creation to short circuit when a "new" job is created, but it already exists and is already in a success state.

**Comment by vdice** [comment]
@krancour how does this command differ from the `clone` command in https://github.com/brigadecore/brigade/issues/1199 ? 

This would be for retrying an event run, right?  e.g. `brig event retry --id <event id>`

**Comment by krancour** [comment]
I think we need to talk and map out clone, retry, etc.

I have thoughts, but nothing firm. Video chat tomorrow?

**Comment by krancour** [comment]
We can still chat later, but here are some thoughts that came to me last night.

"Retry" and "clone," in my mind, are perhaps backed by different intentions.

"Clone" is, perhaps, "make a copy of this event and process it."

I'm not tracking down related issues until after I've had my coffee, but we've seen requests before for a "retry" command that skips jobs that succeeded already and retries those that didn't. We've always said that's near impossible to do because our shared storage isn't a layered file system (which seems it would be a tough hill to climb) and that means we don't have the capacity to restore shared state to what it was prior to a job's failure before a job is retried. I think a compromise that we arrived at that _did_ make it into the v2 proposal doc was that we could implement this sort of "retry" specifically for workers/jobs that don't use a volume to share state.

An Event struct has a Worker field and that is its blueprint for how the Event will be processed-- a battle plan if you will. It's constructed from the associated Project's WorkerTemplate. The Event's Worker also aggregates Job states.

So, we could think of "clone" or "copy" as "copy the event, but not the battle plan." It's like a brand new event and gets a brand new battle plan constructed from the Project's WorkerTemplate. Supposing the Project's WorkerTemplate had changed between the creation of the original event and the execution of the "clone" command, the new Event might have a different battle plan.

We could think of retry as "copy the event _and_, provided there is no shared state involved, copy the battle plan also; clear the state on failed jobs." We could then amend the logic for Job creation to short circuit when a "new" job is created, but it already exists and is already in a success state.

Again, we should still put our heads together. I just wanted to capture these thoughts.

**Comment by vdice** [comment]
That delineation between clone and retry does make sense to me.  It sounds like clone is the more straightforward of the two, so I can start on that effort (https://github.com/brigadecore/brigade/issues/1196) while we think about the nuances of retry.

**Comment by krancour** [comment]
That sgtm.

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1376
