### ISSUE TITLE
project deletes aren't cascading to include deletion of project events

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1202]

**Comment by krancour** [comment]
@vdice would you mind taking this one?

I think you just need to make the project service invoke a delete-many on the event store when a project is deleted.

Preferably, delete the project's events _first_ and _then_ the project. If we did it the other way around and there were a failure, we'd be left with orphaned events, but if we delete events first, we can avoid that.

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1254
