### ISSUE TITLE
Enhancement: Support adding secrets to a project via a file

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1213]
For Brigade V2, users can currently add a secret to a project via `brig project secrets set`.

It may be handy to bulk-add multiple secrets to a project via one command.  To do this, @krancour and I were thinking of adding a `--file/-f` flag to the `brig project secrets set` command such that, when provided, the cli would read and iterate through the provided file and add all parsed key/value pairs as secrets to a given project.  The file would be expected to be a simple text file where each line consists of one `key=value` pair.

As an example, if I have a file `secrets.txt` like the following:

```
foo=bar
baz=true
```

I would then specify it via `brig project secrets set -p myproj -f secrets.txt`.

(Added the label 2.0 just to signify this is for v2.  It could easily be bumped to a later release depending on priorities.)

**Comment by krancour** [comment]
Agree completely, but note `--set` flag can be used multiple times. imho, we should handle this similarly to how Helm handled `--values` and `--set` flags. `--file` applied first, and then `--set` can amend/override.

**Comment by krancour** [comment]
I believe this can be accomplished without breaking changes to the API, so I'm kicking this to beta.1 so that alpha stays focused on things that really need to be in alpha.

**Comment by krancour** [comment]
This was closed by #1397
