### ISSUE TITLE
bug: following logs isn't working

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1228]
I've noticed _recently_ that log streams seem to hang when they reach the end of the currently available data and don't continue streaming new entries as they are created, even when the follow option is specified.

**Comment by vdice** [comment]
@krancour is this dependably reproducible?  Should occur when following any event logs?  Or intermittent?

**Comment by krancour** [comment]
Yes... reproducible every time. You can add `-f` to `brig event logs ...` and you'll see it dump everything it has _so far_, and then it stalls. If you ctrl+c and enter the same command again, you'll see new stuff came through.

**Comment by krancour** [comment]
This was closed by #1249
