### ISSUE TITLE
Expand E2E tests

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1231]
This is a general placeholder around the effort to expand e2e tests for Brigade where applicable.  As usual, the more coverage we have at lower levels, the better -- but there will always be a need for some amount of e2e coverage.

Currently - or as of https://github.com/brigadecore/brigade/pull/1229 - we'll have a small suite of E2E tests.  These were written with GitHub-backed Brigade projects specifically in mind, as the motivation was to test the newly-written git initializer component.  As a first order of expansion, then, it would be prudent to add other types of non-VCS Brigade projects (see the `/examples` dir for some inspiration).

We should also decide on a preferred test harness.  Right now, the tests are in the form of a DIY golang script, run via a make target that assumes the local kube context is already pointing to a cluster w/ Brigade running.  We might want to automate the whole shebang: stand up a k8s cluster, deploy Brigade, run the tests, teardown, etc.

Definitely prudent to reference the v1 e2e tests for inspiration: https://github.com/brigadecore/brigade/blob/master/e2e/run.sh

**Comment by vdice** [comment]
https://github.com/brigadecore/brigade/pull/1297 added running the integration to CI, which was a major goal of this ticket.

The other goal was to expand the tests to cover more scenarios.  I'm thinking this can be done in an organic, as-needed basis, rather than tackling it all here/now, but I'll leave this ticket open in case we want to keep this issue for tracking said effort.  However, I'll be moving this out of alpha.2 and into beta.1 at this juncture.

**Comment by vdice** [comment]
Issued a small re-org PR for these tests in https://github.com/brigadecore/brigade/pull/1446

Still struggling on coming up with a grand plan on how these should look and/or be structured.  Unless we feel urgency on doing so, I'd say we close this one out and let the tests expand organically...

**Comment by krancour** [comment]
Organic SGTM
