### ISSUE TITLE
Git Initializer tests: add ssh url/private repo case

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1233]
Add a test case with an ssh clone url associated with a private repo... something along the lines of:

```
{
	name:          "GitHub - Private Repo - ssh",
	project: core.Project{
		ObjectMeta: meta.ObjectMeta{
			ID: "private-ssh",
		},
		Spec: core.ProjectSpec{
			WorkerTemplate: core.WorkerSpec{
				Git: &core.GitConfig{
					CloneURL: "git@github.com:brigadecore/private-test-repo.git",
					Commit: "a292c2ffe0226f702519ec2833054953e82a816e",
				},
				DefaultConfigFiles: map[string]string{
					"brigade.js": defaultBrigadeJS,
				},
			},
		},
	},
	terminalPhase: core.WorkerPhaseSucceeded,
},
```

The tricky part will be how we want to wire in a private ssh key for use with the corresponding test repo.

See also the following idea for adding the ssh key as a secret to the test project: https://github.com/brigadecore/brigade/pull/1229#discussion_r561962839

Follow-up from https://github.com/brigadecore/brigade/pull/1229

**Comment by vdice** [comment]
I understand how we can wire up a secret (the private ssh key for an existing private test repo) for running these in CI, but I also want these tests to always be runnable by devs locally.  What do we think about _only_ running this private repo test case when CI is running (on GitHub PR or merge/tag events)?

**Comment by krancour** [comment]
Seems reasonable. Can there just be a boolean field in the test case struct that's something like `skipLocally`, and we can set that to `true` for tests of this nature?

**Comment by vdice** [comment]
Added in https://github.com/brigadecore/brigade/pull/1383
