### ISSUE TITLE
Git Initializer: Add Retry

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1235]
Add retry logic to the git initializer component added in https://github.com/brigadecore/brigade/pull/1229

cc @krancour who mentioned a retry lib candidate

**Comment by krancour** [comment]
https://github.com/brigadecore/brigade/blob/v2/v2/internal/retries/retries.go#L14-L40

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1296
