### ISSUE TITLE
Make ttl on root and user tokens configurable

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1251]
There should, however, probably be some kind of ceiling on both of these.

Use of the root user should be discouraged, so a short ttl ceiling is probably called for. I think it's hard-coded as 1 hr right now, and I think that's a reasonable default. 8 hrs might be a good ceiling.

Something like 1 week might be an appropriate default ttl and ceiling for authenticated user sessions.

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1308
