### ISSUE TITLE
SDK should not retry 500 errors

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1255]
Our SDK for go does automatic retries for certain types of error. This seems to _include_ 500 (internal server error).

I'd prefer that 500s didn't automatically get retried.

Retrying something that is quite probably a transient network fault (like a 502 or 503) makes all the sense in the world to me.

If the server is self-reporting that something went wrong on its end, I don't believe that should be retried automatically as the probability of continued failure is high and could even compound the issue.

__EDIT:__ Example of an issue being compounded:

Due to a coding error, I have observed a 500 that was thrown toward the very tail end of a project create operation. When this is automatically retried, the project already exists and a 409 (conflict) is returned stating that the project already exists. This sweeps the original issue under the rug.

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1314
