### ISSUE TITLE
cloudevent attributes in project object

### ISSUE THREAD

**Issue by shekharHPE** [brigadecore/brigade#1259]
More of a question than an issue. 
    
   events.on("cloudevent", (e, p) => {
      console.debug ("Starting cloudevent on brigade for project id: "+ p.id)
      console.debug("Version of the app ID ")
    });

How to get the version of the project-id installed in the kube

**Comment by krancour** [comment]
> How to get the version of the project-id installed in the kube

@shekharHPE, my apologies, but it's not quite clear what you're asking us.

Any chance you can elaborate?

**Comment by shekharHPE** [comment]
Hi @krancour, thank you for the prompt response.
It seems like I found a different way to extract the installed version of the brigade-project-id. 
Please ignore my question. 
Thanks :)
