### ISSUE TITLE
Cool logs have extra line breaks that warm logs don't have

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1261]
Cool logs (stored in MongoDB) seem to be stored with a trailing `\n`

We can either attempt to strip that on the fluentd (log agent) side or we can strip it as cool logs are streamed out of the db.

I think the former is preferable, but a quick search and a glance at docs didn't yield an _obvious_ way to do this, although it's probably possible.

The latter approach is certainly acceptable near term.

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1295
