### ISSUE TITLE
Integration tests: Generate new, unique project name for each test

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1265]
Non-blocking, but should we consider generating new, unique project names each time through the loop so that we don't have to deep six the project from the previous test case in order to create the project for the current test case?

As I said... non-blocking.

_Originally posted by @krancour in https://github.com/brigadecore/brigade/pull/1263#discussion_r570503389_

Perhaps in tandem we change the order as well.  Currently we: delete project, create project, run tests.  We could move to: create project (unique name), run tests, delete project.

**Comment by krancour** [comment]
I thought we had a random string generator somewhere in our code base, but I just checked and it's pretty specifically oriented toward creating large, unique tokens.

Something like [technosophos/moniker](https://github.com/technosophos/moniker) would be cute, but there's no option to constrain string length. Projects (currently) have a max name length of 18 chars.

[thanhpk/randstr](https://github.com/thanhpk/randstr) isn't as cute, but looks like it would do the trick.

These names would be random, but not guaranteed unique... but a collision in a single run through the test suite would be nothing short of extraorindary.

**Comment by krancour** [comment]
Closed by #1382
