### ISSUE TITLE
Don't use tailable cursor when streaming logs from cool storage

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1270]
Our cool log storage currently uses a tailable cursor. This was necessary at one time, because before we divided the logs into warm (k8s) and cool (mongo) storage, we could be streaming new log lines _out_ of mongo as they were written _to_ mongo by the log agent.

This can't happen anymore, because we only ever stream logs out of cool storage when warm storage doesn't exist anymore (i.e. the worker or job pod has been cleaned up and no longer exists). That means that for any given worker or job, every log line that gets stashed in cool storage is there _before_ we ever start streaming from there.

If we ditch the tailable cursor, we can also ditch the requirement that the underlying log collection be a capped collection. _This is the real improvement we want._ With that assumption undone, we clear one impediment (possibly of several) to utilizing cosmos as a drop-in replacement for mongo. Cosmos doesn't support capped collections.

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1274

(Spoiler alert around the note on the capped collection for logs -- we're intending to indeed move away from this type in the near future, most likely in a PR to close https://github.com/brigadecore/brigade/issues/1271.)
