### ISSUE TITLE
disallow transition out of a terminal phase

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1276]
For both workers and jobs, it may sometimes be possible that post-cancellation of a running worker or job (abortion) the observer will see the corresponding pod come down with a non-zero exit code and attempt to transition the worker or job to a failed phase-- when in fact the pod came down only because it was deliberately terminated _by_ the cancel/abort process...

As a general rule, we should simply disallow any phase changes to a worker or job that has already entered a terminal phase.

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1344
