### ISSUE TITLE
CD for windows log agent image might need attention

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1277]
We used a github action to do CI for the windows log agent. We couldn't accomplish it with Brigade itself because neither Kaniko nor the Docker-in-Docker pattern work on a Windows node.

I'm about 90% sure we still don't have any _CD_ in place for that image.

I would settle for resolving this prior to alpha.2. I don't want this holding up alpha.1.

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1472
