### ISSUE TITLE
Job creation errors are inadequately descriptive

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1291]
When the worker gets a non-200 response code from the API when creating a new Job, the error message isn't adequately descriptive.

For example:

```
2021-02-19T16:39:30.507Z DEBUG: writing default brigade.ts to /var/vcs/.brigade/brigade.ts
2021-02-19T16:39:30.511Z DEBUG: no existing package.json found at /var/vcs/.brigade/package.json
2021-02-19T16:39:30.511Z DEBUG: creating a minimal package.json
2021-02-19T16:39:30.511Z DEBUG: writing package.json to /var/vcs/.brigade/package.json
2021-02-19T16:39:30.512Z DEBUG: installing dependencies
2021-02-19T16:39:33.871Z DEBUG: compiling brigade.ts
2021-02-19T16:39:36.599Z INFO: brigade-worker version: 5be6835-dirty
2021-02-19T16:39:36.608Z [job: job1] INFO: Creating job job1
2021-02-19T16:39:36.610Z [job: jobA] INFO: Creating job jobA
2021-02-19T16:39:36.729Z ERROR: Error creating job "jobA": Request failed with status code 400
2021-02-19T16:39:39.153Z [job: job1] DEBUG: Current job phase is SUCCEEDED
2021-02-19T16:39:39.154Z [job: job2] INFO: Creating job job2
2021-02-19T16:39:41.755Z [job: job2] DEBUG: Current job phase is SUCCEEDED
```

I happen to know that the problem here is that `jobA` is invalid because it contains an uppercase character. (Job names are supposed to be lower alphas, numerals, and hyphens only.)

But the error message that _was_ included in the response from the server has been obscured.

**Comment by krancour** [comment]
I think this can be corrected by making the worker use the brigade-sdk-for-js.

That had not existed that the time the new worker code was written.

**Comment by itowlson** [comment]
I had a brief look at this.  Taking a dependency on the Brigade SDK is conceptually ideal, because it means that _all_ clients of the API (including Brigade's own internal components) go through the same paths.  But it also means that we have to coordinate across two repositories and means that we can't do a release of Brigade until _after_ the release of the SDK - a reversal of the normal order of releases - unless we have a mechanism for doing local builds of the JS SDK and pulling those into Brigade (and taking them out again before committing).  That might be worth it but it would be a faff (unless we found and implemented a good refactoring of dependencies).

We could probably improve error reporting in the existing code by casting the caught exception to an `AxiosError` and including `response` fields such as `statusText` and/or `headers` though I am not sure whether the `data` field will give us response error details.  There must be some way though!

**Comment by krancour** [comment]
> But it also means that we have to coordinate across two repositories

@itowlson, like you, I am generally opposed to scenarios that force us to coordinate changes across multiple repositories.

Having said that, I was nevertheless open to using the brigade-sdk-for-js here since the worker communicates with the API server for only three specific things-- all of which are pretty stable interactions that aren't likely to change much. i.e. If the dependency on brigade-sdk-for-js ever did force us to carefully coordinate changes across repos, I would expect it to be a very rare event.

> and means that we can't do a release of Brigade until after the release of the SDK - a reversal of the normal order of releases

That doesn't have to be true if we don't assume versioning of the sdk-for-js has to be in lock-step with the versioning of Brigade itself. I haven't been assuming they would be, as I've been assuming that we will eventually, at times, release bug fixes to the sdk-for-js completely independently of any Brigade release.

Now, having said all _that..._

I'm also entirely unopposed to your other approach also. fwiw, I _think_ for any non-2xx response, you could just parse the response body and throw it and it would contain a reasonable amount of detail.

I defer you your judgement on how you'd like to approach this.

**Comment by vdice** [comment]
Wondering if we might reach consensus on how to tackle this bug, as it's one of the last items for the current milestone.  Ping @krancour and @itowlson

**Comment by krancour** [comment]
@vdice I see pros and cons here, but I wouldn't have any reservations about kicking this down the road to the next release. Even if this isn't solved until beta, it would be fine as no breaking changes should be required to solve for it.

**Comment by vdice** [comment]
I'm pulling this in as the lack of error messaging in these scenarios has bit me often.

I'll first be looking at the simplest approach mentioned above, e.g. `fwiw, I think for any non-2xx response, you could just parse the response body and throw it and it would contain a reasonable amount of detail.`

**Comment by vdice** [comment]
Actually, I'm thinking I favor using the [sdk](https://github.com/brigadecore/brigade-sdk-for-js) here, as initially suggested by @krancour.  For the specific case of getting a better error message when attempting to create a misconfigured job, use of the sdk gets us the full error details with no changes needed around printing/parsing the caught error:

```
2021-06-14T20:58:45.551Z [job: my/first/job] INFO: Creating job my/first/job
2021-06-14T20:58:45.642Z ERROR: Error creating job "my/first/job": Bad request: Request body failed JSON validation
  0. name: Does not match pattern '^[a-z][a-z\d-]*[a-z\d]$'
```

My current confusion lies around the overlap/interplay between brigadier and the sdk.  For instance, brigadier has a concept of a Job and its spec is represented as a Container... which is close but not quite equivalent to the sdk's concept of a Job and its spec (JobContainerSpec).  So, when we translate the brigadier objects to sdk objects for making api calls, there currently exists some tension/inefficiencies.  Anyways, I'll pair with @krancour soon to hash things out...

**Comment by krancour** [comment]
The SDK was a straight port of the Go SDK, so I admittedly didn't build it with brigadier interop in mind. We'll work around it somehow...

**Comment by vdice** [comment]
Fixed in https://github.com/brigadecore/brigade/pull/1447
