### ISSUE TITLE
Regex for validating event creator role's scope needs to be relaxed

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1301]
Currently it does not permit a source that looks like a URL (for instance `github.com/brigadecore/brigade-github-gateway/v2`), but that should be allowed, as the most realistic value that gateways can use to identify themselves as an event source _without_ colliding with other gateways is to use a domain or URL controlled by the project that produced the gateway in question.

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1302
