### ISSUE TITLE
Trying brigade2

### ISSUE THREAD

**Issue by d46** [brigadecore/brigade#1335]
I would like to try brigade 2. I have followed some parts but did not able to be successful while using GitHub events.

For example,  What is the URL telling about in the part of this file
https://github.com/brigadecore/brigade/blob/v2/examples/git/github-demo.yaml

`- source: github.com/brigadecore/brigade-github-gateway/v2` there is no brigade GitHub for v2.

**Comment by krancour** [comment]
There's a pending PR that reworks a number of examples, including removing that one. There _is_ is v2-compatible GitHub gateway in a very early / prototyping phase right now. That example was committed very prematurely.

**Comment by d46** [comment]
Is it possible to use that gateway? I would like to go with brigade 2. I think, that is the only missing part for building the pipeline with brigade 2.

**Comment by krancour** [comment]
You're welcome to try anything, of course. Have a look at krancour/brigade-github-gateway, but buyer beware... in this prototype phase, I'm force pushing to master, docs aren't up to snuff, and it is _definitely_ not a production grade solution or anything we'd offer any support for. Except for the force pushing but, all of that goes for Brigade 2 itself as well.
