### ISSUE TITLE
Bug: Jobs are failing on Kubernetes 1.19 (v2)

### ISSUE THREAD

**Issue by d46** [brigadecore/brigade#1337]
https://github.com/brigadecore/brigade/blob/66dfceb3de22d5a735615d82d31077bf6a512a12/brigade-worker/src/k8s.ts#L539 

The client does not return correct response from k8s API by so jobs are failing

Output of `brig version`:
1.4.0
Output of `kubectl version`:
1.19

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
EKS

**Comment by krancour** [comment]
I vaguely recall us having taken action some time ago to ensure compatibility with newer versions of k8s.

1.4.0 is the version of your client. Can you please specify what version of Brigade is running _in the cluster_?

Also, additional information on the error you're encountering would be helpful. "does not return correct response" is too vague for us to understand what might be going on here.

**Comment by d46** [comment]
@krancour, sorry for the late response. I have been issuing this error because the wrong models were coming from Kubernetes 1.19 inside this resolver. I think the errors have been coming from `createNamespacedSecret` or `createNamespacedPod` methods. I was not able to debug the running pods. I'm sorry about the weak feedback. I'm not reminding the error, certainly. I rolled back to v1.

**Comment by krancour** [comment]
@d46... I just noticed you changed the title of this issue to include "(v2)"

I think it wasn't initially clear to me that you were test-driving v2 (which is in an alpha state right now).

You said you were using 1.4.0 client. The 1.4.0 client is definitely not compatible with v2.

So idk if your issues may have stemmed entirely from mismatching a 1.x client with a v2 backend.

Happy to help you further if you have more information. For now, I'm going to close this.

**Comment by d46** [comment]
It is not a v2 problem. Sorry for the wrong guidance. I was using v1 with 1.19, and I rolled back to 1.18. FYI.
