### ISSUE TITLE
errors occur if you try to get logs from a worker or job that isn't yet in a running state

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1371]

**Comment by vdice** [comment]
Thanks for filing.  I wonder if this was a regression that snuck in.  I just hit it and wanted to paste in the apiserver logs for tracing down:

`2021/04/21 18:57:29 error retrieving log stream for event "cb69a8cb-4f3b-4761-89cf-d066d31652ad": error opening log stream for pod "cb69a8cb-4f3b-4761-89cf-d066d31652ad" in namespace "brigade-simple-pipeline-83f2ae00-5b12-4dfb-af95-c9e7bfddd698": container "worker" in pod "cb69a8cb-4f3b-4761-89cf-d066d31652ad" is waiting to start: ContainerCreating`

**Comment by krancour** [comment]
I think somewhere when making the decision to go after warm v cool logs, we do a check (or a de-facto check) that the pod exists. I guess if, for instance, a pod is _starting_ but not fully running yet (maybe the git-initializer is running, for instance) then the pod exists but the _container_ we're looking for doesn't.

**Comment by krancour** [comment]
This was closed by #1373
