### ISSUE TITLE
enforce timeouts on workers and jobs

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1378]
Currently, nothing enforces timeouts on workers and jobs.

This should be the observer component's duty.

**Comment by vdice** [comment]
The job object in brigadier looks to have a default timeout of 15 mins and is configurable via `job.timeout`.  Enforcement still needs to be added in the observer.

For the worker, is there a default timeout already defined?  If not, what should it be?  Do we want this value to be configurable by users (via the chart)?

**Comment by krancour** [comment]
> For the worker, is there a default timeout already defined?

Doesn't look like we have that yet. (iirc, Brigade v1 didn't have it either?)

imho, we should make it user-configurable by adding it to the `WorkerSpec`, but also allow operators to set a max allowable ceiling. We should probably let operators set a max allowable ceiling for jobs also. Many operators might not be tolerant of their end-users submitting workers or jobs that run for days.

**Comment by krancour** [comment]
@vdice you're working on this, right? What's the rough plan of attack? Can I assume it involves the observer starting a timer the first time it observes a new worker or job and using the api to forcefully terminate that worker or job if the timer goes off before it observes completion?

**Comment by vdice** [comment]
@krancour I can switch things up to work that way.  My first approach was to run a calculation each time sync[Job|Worker]Pod was called: check the pod's start time plus timeoutSeconds value -- if less than current time, consider timed out and go from there.  Perhaps this is too naive and or costly?  https://github.com/vdice/brigade/blob/feat/worker-and-job-timeouts/v2/observer/jobs.go#L189-L208

**Comment by krancour** [comment]
@vdice what you just described was actually my first thought as well, but I think there's the potentials for a worker or job to run quite long past the specified timeout if the corresponding pod goes a while without syncing.

**Comment by vdice** [comment]
https://github.com/brigadecore/brigade/pull/1411 adds Job timeout enforcing.

Going to start work on adding the ability to specify a worker timeout (using the same `timeoutDuration` approach agreed-upon in #1411 ) plus operator defaults and of course logic to enforce these values.

**Comment by vdice** [comment]
@krancour When the observer is enforcing a timeout on a worker pod, in addition to updating the worker status and deleting worker resources, what do we want to do about the worker's jobs, if anything?  Do we want to iterate through all of them and if a job has a non-terminal phase, update its status with JobPhaseTimedOut?

**Comment by krancour** [comment]
> When the observer is enforcing a timeout on a worker pod, in addition to updating the worker status and deleting worker resources...

Related to a comment I left on #1411, but I think the observer shouldn't do that. I think the observer should just invoke a new job timeout operation on the API and let the API take it from there.

So now to answer the question of

> Do we want to iterate through all of them and if a job has a non-terminal phase, update its status with JobPhaseTimedOut?

I think so (although maybe the jobs should be JobPhaseAborted, because the jobs won't have timed out, rather the worker that was orchestrating them would have). And in fact, I consider this a salient reason for moving timeout logic to the API. I'm pretty sure there's existing logic we can use since timing out a running worker should be pretty similar to _aborting_ a running worker and we've already got all that worked out.

**Comment by vdice** [comment]
👍 Sounds good, thanks for the feedback and guidance.  I'll update the PRs to suit.

**Comment by vdice** [comment]
Worker timeout and enforcement PR staged here: https://github.com/brigadecore/brigade/pull/1419

Last item on the list: allow for operator config of max timeout ceiling for worker and job execution per https://github.com/brigadecore/brigade/issues/1378#issuecomment-841479775.

**Comment by krancour** [comment]
@vdice the ceiling will come in a separate follow-up to #1419, ya?

**Comment by vdice** [comment]
Last task completed (https://github.com/brigadecore/brigade/pull/1442); closing!
