### ISSUE TITLE
On smaller viewports, sidebar overlaps with main content

### ISSUE THREAD

**Issue by grelas** [brigadecore/brigade#1385]
On the https://docs.brigade.sh/ site, when the viewport is < ~1200px, the fixed sidebar overlaps with the main content view. Here is a screenshot when the viewport is 700px:
![image](https://user-images.githubusercontent.com/993698/116456406-3f5eb500-a830-11eb-9e9e-2f2fab628b4f.png)

I'm able to reproduce this on Chrome (v90.x) and Safari.

One quick fix would be to wrap the `.sidebar.fixed nav` class with a media query 

```
@media only screen and (min-width: 1200px) {
  .sidebar.fixed nav {
      position: fixed;
      max-width: 300px;
      left: 0;
      top: 0;
      bottom: 0;
      z-index: 1500;
      overflow-y: scroll;
   }
}
```

I'm not sure if brigade docs use some template or theme so feel free to close if this is not the right place for this issue.

**Comment by krancour** [comment]
Adding a datapoint here. The reported behavior only exhibits itself if you have scrolled down the page far enough that the top bar is out of view.

**Comment by a-muk** [comment]
@krancour this problem arises when we zoom in a lot. Can the site have a hamburger menu or something for both the sidebar and the top menu when the user zooms in?

**Comment by krancour** [comment]
> Can the site have a hamburger menu or something for both the sidebar and the top menu when the user zooms in?

Ideally, yes, but it probably means swapping to a totally different Hugo theme. I am open to that, but there are other aspects of the documentation that I want to get resolved before we start messing with alternative themes.

In the meantime, we can at least stop the undesired overflow by eliminating the "sticky" factor on sidebar. It's a fixed element and being removed from the normal page flow is the cause of this issue.

**Comment by a-muk** [comment]
Is this issue still open?

**Comment by krancour** [comment]
@a-muk #1843 solves it.

**Comment by a-muk** [comment]
Okay @krancour
