### ISSUE TITLE
Dial in Brigade + ingress + tls

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1398]
Dial in (and document?!) standing up Brigade with ingress and tls.  We've done this with cert manager in the past (and that's what our v1 setup uses).  This general approach will be a pre-req to introducing a third-party auth strategy (GitHub or OpenID Connect provider).

**Comment by krancour** [comment]
fwiw, ingress + TLS is probably "advanced." The API server can support TLS all on its own without the involvement of an ingress controller. Even with an ingress controller in play, additionally using the API server's native TLS is still a good idea for the sake if securing requests that originate _within_ the cluster, such as requests from the scheduler, the observer, or a worker.
