### ISSUE TITLE
improve job creation logic for retried events

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1402]
As a follow-up to https://github.com/brigadecore/brigade/pull/1376, we should improve what happens when an event is a retry of another and a job is created for the new event with configuration that differs from the job that was inherited from the original event.

Currently this results in a 409, but we could, instead, discard the inherited job and create the job as requested.

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1422
