### ISSUE TITLE
improve error handling when jobs logs are inherited and not found

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1403]
As a follow up to https://github.com/brigadecore/brigade/pull/1376, in the case where an event is a retry of another and someone goes looking for specific jobs on the new event that should be inherited from the original, but the original event has been deleted in the meantime, we should return a more informative error than the 500 that currently surfaces.

**Comment by vdice** [comment]
I'm trying to recall, do we want to update [this](https://github.com/brigadecore/brigade/blob/v2/v2/apiserver/internal/core/logs.go#L181) to return an ErrConflict-typed error?  How about the error message as currently written?

**Comment by krancour** [comment]
You're remembering correctly. Initially, I thought conflict might be our best option, for lack of a better one.

An alternative I just thought of would be to go with a 404, which I initially resisted, but only if we amend the `ErrNotFound` error type with a new field that allows for an (optional) detailed explanation. We'd eat any `ErrNotFound` we get when retrieving the original event (so the end user doesn't get a weird message about something they weren't directly looking for not being found) and issue a new `ErrNotFound` with a detailed explanation.

Any thoughts on that?

**Comment by vdice** [comment]
I like that.  `ErrNotFound` indeed makes more sense in this context.  I'll look at what it might look like to add a new field to the current struct and how we can use it here...

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1410
