### ISSUE TITLE
v1/v2 doc site plans?

### ISSUE THREAD

**Issue by carolynvs** [brigadecore/brigade#1412]
Is there a plan for how to roll out docs for v2 while still preserving the existing documentation for v1 until v1 is deprecated? I would like to help contribute to documentation for v2, such as quickstarts or tutorials. If there isn't a spot for it yet, I'm happy to help figure out a transition plan.

cc @flynnduism

**Comment by krancour** [comment]
Great question and great instinct to cc @flynnduism. I wouldn't even try to answer this before hearing from him.

**Comment by flynnduism** [comment]
Great idea to get this organized, there's a bunch of different ways to do it. The process we followed for Helm v3 was pretty smooth, having clear branches and urls for things:

* spin off a branch of the docs for `dev-v2` or something, where Brigade 2 work in progress things go. I can easily deploy that via netlify and make it accessible
* have a banner on each version of the docs/sites that tells you which version you are looking at, and which one is considered 'latest' or recommended
* have some dedicated pages that explain to users what the differences are between `v1` and `v2`, support timelines, release schedule, why/when you should upgrade, how to migrate things, etc.

Once v2 is released, the `dev-v2` docs would become `main`, and the `v1` docs could be preserved at `v1.docs.briagade.sh`, swapping things around.

**Comment by krancour** [comment]
@flynnduism so a good way to get started then is to just emulate the v1 docs setup in our `v2` branch and you'll take it from there with netlify, etc?

**Comment by carolynvs** [comment]
I can help with that

**Comment by flynnduism** [comment]
I tried spinning up a `v2` starter site using the dev branch, but it won't deploy as is...
https://app.netlify.com/sites/v2-docs-brigade/deploys

It needs some scaffolding to setup the `/docs` dir with the basic Hugo config. @carolynvs it would be great to get your help!
The config and theme for [the v1 docs](https://app.netlify.com/sites/brigade-docs/overview) are ported from your work on Porter!

**Comment by carolynvs** [comment]
Sure I'll work on that today. 👍

**Comment by carolynvs** [comment]
Ok, ready for review.

**Comment by krancour** [comment]
Thanks to @carolynvs for getting us started on this and thanks to @vdice for ongoing efforts to flesh out v2 docs.

@vdice is currently tracking v2 doc progress in https://github.com/brigadecore/brigade/issues/1508, so I'm going to close this.
