### ISSUE TITLE
Skip build for doc only PRs

### ISSUE THREAD

**Issue by carolynvs** [brigadecore/brigade#1436]
It would save time, and avoid unnecessary builds if we detected if all of the changes are to the website content and skipped the build. That way PRs that are just for docs get speedy builds and don't waste your resources.

**Comment by krancour** [comment]
@vdice I don't yet have specific thoughts on how to achieve this. Do you?

**Comment by carolynvs** [comment]
In porter we use this [script](https://github.com/getporter/porter/blob/main/build/doc-only-build.sh) and skip the build if it's docs only.

**Comment by krancour** [comment]
@carolynvs your git-fu is better than mine, but at a glance, isn't that script only at the differences between HEAD and HEAD~1? What happens with PRs that are composed of multiple commits?

**Comment by carolynvs** [comment]
The way the git history looks for a lot of ci systems is this: 

* A- merge PR into master
* B - PR commit 2
* C- PR commit 1
* D- last commit on master

HEAD~ will diff between A and D, which will pick up all commits on your PR.

**Comment by krancour** [comment]
I misread the script! It clearly says `HEAD~` and I _read_ `HEAD~1`.

I'm still trying to wrap my head around everything you just said, but I believe you.

This seems reasonable.

**Comment by vdice** [comment]
Yup, the script @carolynvs added for Porter has worked great 👍

**Comment by carolynvs** [comment]
I spoke with Kent offline and it may not be as easy as we have it on Azure Pipelines because in brigade the check is run against the branch, and not the result of merging the branch into the target of the pull request. It would require a bit more work than what's in that script.

**Comment by krancour** [comment]
> because in brigade the check is run against the branch

I know that wasn't criticism, so this isn't defense. I just want to add some more context for anyone who reads this and wonders...

I don't think there's anything wrong with our approach, especially given two things:

1. GitHub gives us other controls that enforce a branch needing to be up to date with respect to the base before being merged.

1. Brigade isn't actually a CI system (it just happens to be useful for CI) and complicating the logic of our git initializer beyond the straightforward "you give us a ref and that's what we'll work with" muddies the waters a bit.

The current approach has never posed a problem until now, and I'm not sure this is impetus enough to revisit our git initializer logic.

I do, however, think we can and should (eventually) find a way to solve for this specific conundrum of bypassing tests for doc-only PRs.

In the meantime, I propose we maintainers find consensus among ourselves that tests are not required to pass or even run for a doc-only PR to be merged.

**Comment by carolynvs** [comment]
Sorry Kent, I really wasn't trying to imply "and Brigade _should_ do this", because I agree that it's not a CI system, it isn't really a feature that is wanted/needed in Brigade. I was just summarizing what we discussed about the behaviors that the script assume and what Brigade does, to give context into why we can't really use the script's logic.

**Comment by krancour** [comment]
I know. :) That's why I said I knew you weren't criticizing and I wasn't trying to be defensive.

**Comment by krancour** [comment]
I think it makes sense to close this.

We agreed this isn't a feature Brigade is getting.

It's a feature Brigade would like to _use_, but for now, maintainers have agreed that doc-only PRs don't require the full test suite to run before being merged.
