### ISSUE TITLE
Update README and other docs with minimum compatible kubernetes version

### ISSUE THREAD

**Issue by willie-yao** [brigadecore/brigade#1454]
We determined in issue #1441 that the minimum brigade2-compatible kubernetes version is 1.16.0, due to the addition of startup probes in that version. This is helpful information for any developer or user of brigade2, so this finding calls for some updates to the README and documentation

**Comment by krancour** [comment]
> due to the addition of startup probes in that version

Not that you were planning to, but in case you were... I don't think the updates to the docs will require that level of detail.

Just state that we're compatible with 1.16.0+ and leave it at that.

**Comment by willie-yao** [comment]
Opened a PR #1456 , let me know if it looks good

**Comment by vdice** [comment]
Looks like https://github.com/brigadecore/brigade/pull/1456 addresses this.  Thanks @willie-yao!  Closing.
