### ISSUE TITLE
Discussion: Do we need to allow arbitrary host mounts in jobs?

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1471]
Brigade 1.x allowed this (if project configuration allowed it).

On security grounds, Brigade 2 _doesn't_ permit this. Brigade 2, at present, only permits the host's Docker socket to be mounted into a job (if project configuration allows it; and I feel even this should be discouraged).

From a security standpoint, allowing arbitrary host mounts isn's something we should entertain lightly, but we also have to put some thought into what legitimate uses for this might exist. For instance, I know our Brigade 1.x-based integration tests made extensive use of that 1.x feature. We've, thus far, been unable to port that one job over to Brigade 2 since Brigade 2 lacks that feature. (So we allow Brigade 1.x to run that one job for us, while we use Brigade 2 for everything else.)

Ideally, we might find a better approach to the integration tests that doesn't rely on this.

**Comment by vdice** [comment]
Addressing the v2 integration test approach specifically (we may want a separate issue for this),

> For instance, I know our Brigade 1.x-based integration tests made extensive use of that 1.x feature. We've, thus far, been unable to port that one job over to Brigade 2 since Brigade 2 lacks that feature. (So we allow Brigade 1.x to run that one job for us, while we use Brigade 2 for everything else.)

Some alternate approaches we could entertain for running the k8s-based integration tests:
- Keep test setup (kind-based), etc. all the same but run via GH Actions (since we already supplement CI with this provider for building/pushing Windows logger agent images and will probably continue to do so for some time).  No fancy KinD-in-Docker needed here as we'd be running on a VM.
- Standup a minimal/cost-effective/non-ephemeral k8s cluster and provide the kubeconfig to the tests for deploying Brigade and running against
- Investigate other ephemeral/JIT k8s options that don't require host mounts?

**Comment by krancour** [comment]
> Stand up a minimal/cost-effective/non-ephemeral k8s cluster and provide the kubeconfig to the tests for deploying Brigade and running against

I was thinking of something like this also.

**Comment by radu-matei** [comment]
I would raise the point that this is not only useful for our use case.
Sure, a lot of people will be able to use GH Actions or another Kubernetes cluster for integration tests.

But there are definitely scenarios where the cluster where Brigade is running  _is_ the Kubernetes cluster intended to be used for this kinds of workloads.

Of course, no mounts should be done by default, but if the risks are properly documented, I don't see a reason not to allow cluster administrators the option to enable host mounts when creating a project.

**Comment by krancour** [comment]
@radu-matei agree on all points. There are definitely two conversations here, which I think @vdice was trying to call attention to also. I'd like to figure out how to integration test without this, but as you point out, it's not the _only_ use for host mounts.

Re-broadening the conversation to the general case, I'd like gain an understanding of whatever are alleged to be "legitimate" use cases for this. I harbor a vague suspicion that under scrutiny, there is almost always a safer alternative.

> besides a per-project setting, we can make this configurable when deploying Brigade as well, disabled by default

If we find there's no alternative but to allow host mounts, I love this idea. That puts the operator in control of this decision.

**Comment by radu-matei** [comment]
Here's a use case that might not be all that popular, but I can't think of a safer way to achieve this.

In my cluster I have a couple of nodes running on boards with GPIO access (like Raspberry Pis). I want to schedule Brigade jobs on them, and I want the jobs to have access to the underlying GPIO pins, which cannot be achieved without mounting `/sys/class/gpio/`.

**Comment by krancour** [comment]
Removing this from any milestone (for now) because I believe, given its implications, we shouldn't rush into this. If we elect to add this, I humbly suggest that we do it post GA and only if/when the community calls for it (or whenever we determine that we, ourselves, absolutely need it-- whichever comes first).

**Comment by krancour** [comment]
Closing this issue for now because it's pretty stale and a real-world need for this hasn't surfaced yet. Given the security implications, I'm happy to remove this from consideration for now, but equally happy to revive the conversation in the future there is sufficient demand for this.
