### ISSUE TITLE
Scaffolding/outline for Brigade v2 docs

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1483]
It's time to get serious about v2 docs!

For this ticket, work on a proposed scaffolding/outline for Brigade v2 doc layout.  Output should be the proposal and then collaborative discussion around the way forward.

We ported over the v1 layout untouched, but in chatting with @krancour, I believe we'd rather pursue a different structure for the docs in v2.

The initial idea is, at a high-level, splitting documentation into sections for Operators (Brigade cluster installers), Admins (Managers of users/roles/etc in Brigade) and Developers (Users of the system, creators of Projects, script writers, etc.)  Any ideas/feedback around this initial proposed breakdown?  cc @krancour @radu-matei @carolynvs

**Comment by carolynvs** [comment]
I like the idea of target doc sections towards different roles. 👍

**Comment by vdice** [comment]
Here's what an (initial) hierarchy of v2 docs could look like:

```
- Install

- Overview of Brigade (v2)
    - First mention of Operator/Admin/Developer roles?
    - Architecture
    - SDK(s)

- Quickstart (for devs doing it all; kicking the tires)
    - Probably can use what currently exists in the v2 `README.md` as the basis

- Operators
  - Overview/Definition of this role
  - Install/Manage system
  - Secure deploy (TLS, ingress, domain, Third-Party Auth)
  - Gateways

- Administrators
  - Overview/Definition of this role
  - SA/User/Role Management

- Developers
  - Overview/Definition of this role
  - Projects (brig init!)
  - Events
  - Brigterm (when available)

- Scripting guide
    - Brigadier overview
    - TBD scripts/examples walkthrough
```

Ideas on additional or different sections?

**Comment by carolynvs** [comment]
Don't forget that there is an updated quickstart for brigade 2. I hope that's what we want to use instead of the readme? https://v2--brigade-docs.netlify.app/intro/quickstart/

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1487
