### ISSUE TITLE
Question: Disable storage and cache for worker pod. or Delete it at the end.

### ISSUE THREAD

**Issue by mathnitin** [brigadecore/brigade#1488]
Question: Is there any configuration to disable PVC for the brigade-worker pod? For all the jobs created within the default script, I am setting the storage.enabled and cache.enabled to false. But I am not sure how I can do this for the worker pod. 

If we can not disable it, how can I make sure it is deleted at the end?

**Comment by krancour** [comment]
Hi @mathnitin great question.

The cache, for sure, is never enabled unless you ask for it. As for the build storage, the team's been very focused on Brigade 2, so I had to dig into the v1.x code to refresh my memory. Sadly, no... that cannot be disabled in v1.x. () Although it _should_ already always be cleaned up automatically. The worker is supposed to clean that up regardless of success or failure. If that's not happening, let me know.

If someone were to PR something to make the worker provisioning or not provisioning this storage conditional on some project-level configuration setting, I believe myself and other maintainers would enthusiastically be in favor of it.

fwiw, v2 is reaching a beta state within a few days from now and in v2, workers don't provision build storage (now called "shared storage"). Such storage is provisioned by other Brigade internals _before_ a worker even launches, and _only_ if configuration indicates the worker requires it. You may want to take a look.

https://github.com/brigadecore/brigade/tree/v2

**Comment by mathnitin** [comment]
@krancour That's what I am noticing, PVC is not getting deleted. As a workaround, I am deleting the PVC in the "after" event call.

Thanks for the v2 update. I will keep an eye on it.

**Comment by krancour** [comment]
> That's what I am noticing, PVC is not getting deleted.

@mathnitin if that's happening, that's something we'd certainly like to fix.

Are you able to share the `brigade.js` in question (or a sanitized version of it)?

Also, is your script completing successfully and still not cleaning up after itself? Or is it failing and not cleaning up after itself.

Any logs from the workers in question would be helpful.

Would love to fix this.

**Comment by krancour** [comment]
Closing due to staleness. Please reopen if it's still an issue.
