### ISSUE TITLE
Bug: Cannot login to remote cluster from Brigade 2 from within allowed organization

### ISSUE THREAD

**Issue by willie-yao** [brigadecore/brigade#1504]
I attempted to login to a remote cluster before joining an allowed organization, which resulted in an expected error. However, after being added to the organization, I am still unable to login, and I'm getting this error repeatedly:

`Could not authenticate the request: User is not a member of any allowed GitHub organizations`

This is the command I'm using to login:

`brig login -s https://api.brigade2.io -b`

There seems to be an issue with updating a login token after a user's organization has updated. I'm opening this issue now to track this bug.

**Comment by krancour** [comment]
I've determine that whether a user's membership in an allowed org is public or private is the determining factor in whether this works or not. Public works. Private doesn't.

I am unable to figure out why this matters. The API is accessed _as_ the user in question, and their private org memberships _should_ be visible to themselves.

**Comment by krancour** [comment]
fwiw, a user's private orgs can only be found this way:

https://docs.github.com/en/rest/reference/orgs#list-organizations-for-the-authenticated-user
