### ISSUE TITLE
there goes the neighborhood

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1513]
For lack of a better place to put this issue, I'm putting it here.

I want our dogfood cluster to have more activity than it currently does-- a lot more. We're making great use of it and using it for CI/CD on all sorts of stuff, but it's not even breaking a sweat, really.

I am proposing that we develop and deploy a "noisy neighbor" gateway, along with a project that's subscribed to that gateway's events, with intentions of discovering modes of failure that we don't know about yet, or currently know very little about--  things that may occur when the system is pushed hard for sustained periods of time. For example, what happens when MongoDB and Artemis disks fill up? Is the fair scheduler really fair?

This should lead to actionable insight. We may end up adding specific documentation for specific limitations we discover. We may end up discovering the need to develop a new component similar to 1.x's vacuum.

**Comment by willie-yao** [comment]
I will be working on this gateway in this [repo](https://github.com/willie-yao/brigade-noisy-neighbor)

**Comment by krancour** [comment]
This has moved to https://github.com/brigadecore/brigade-noisy-neighbor

I'm going to close this issue now since this work is well underway in its own repo with its own issue queue.
