### ISSUE TITLE
docs: Quickstart does not tell you Docker needs to be running

### ISSUE THREAD

**Issue by technosophos** [brigadecore/brigade#1532]
Output of `brig version`: N/A

Output of `kubectl version`: N/A

Cloud Provider/Platform (AKS, GKE, Minikube etc.): Kind on macOS

In the quickstart guide, it tells me to install Kind and then run `kind create cluster`. However, it doesn't say that Docker should be running locally. On Mac, this will cause an error:

```
$ kind create cluster
ERROR: failed to create cluster: failed to list clusters: command "docker ps -a --filter label=io.x-k8s.kind.cluster=kind --format '{{.Names}}'" failed with error: exit status 1
Command Output: Error response from daemon: dial unix docker.raw.sock: connect: connection refused
```

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1679
