### ISSUE TITLE
rename master to main/trunk

### ISSUE THREAD

**Issue by bacongobbler** [brigadecore/brigade#1542]
Many software projects that are managed and distributed using tools like `git` use master/dev terminology. The term master has extremely offensive connotations. We should encourage all software projects to adopt less offensive terminology.

Github now has a branch renaming process; any requests to `master` will be redirected to the new branch name.

I'm wondering if changing the branch name to `main` or `trunk` would be feasible for the project.

Helm recently went through this process so I'm happy to help with this.

https://github.com/brigadecore/brigade/settings/branches

**Comment by bridgetkromhout** [comment]
The directions at https://github.com/github/renaming have worked well for me.

**Comment by krancour** [comment]
I'd like to do this for all of our gateways.

For Brigade itself, I'd like to put this off until v2 goes GA because there are other branch renaming shenanigans that have to go on at that time anyway and I only want to deal with this once.

**Comment by krancour** [comment]
We've handled this almost across the board now, but not for this repo itself.

Before we undertake that, I want to be sure that renaming does not interfere with go package resolution for gateways and other integrations that consume brigade v1.x packages.

**Comment by krancour** [comment]
This was completed in conjunction with the v2.0.0 release.
