### ISSUE TITLE
Docs: Quickstart guide has broken "Read Next" link

### ISSUE THREAD

**Issue by technosophos** [brigadecore/brigade#1543]
Output of `brig version`: n/A

Output of `kubectl version`: n/a

Cloud Provider/Platform (AKS, GKE, Minikube etc.): n/a

![Screen Shot 2021-08-09 at 13 54 38](https://user-images.githubusercontent.com/89193/128766179-e1f5123e-0355-43a1-becd-5ccfe5fc7cb3.png)

In the text above, the "Read Next" is a broken link. It goes to: `https://v2--brigade-docs.netlify.app/readnext`

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1551
