### ISSUE TITLE
Docs: Link from Quickstart to the Authorization docs

### ISSUE THREAD

**Issue by technosophos** [brigadecore/brigade#1544]
Just as a matter of course, when I was reading through the quickstart and logged in using `--root`, I wondered how user accounts work. Adding a link to something like this from the [Log Into Brigade](https://v2--brigade-docs.netlify.app/intro/quickstart/#log-in-to-brigade) link would be good.
https://docs.brigade.sh/topics/administrators/authorization/

**Comment by CIPHERTron** [comment]
Would love to work on this. Can I get a bit more context on where to add the external link and what should be the external link?

**Comment by krancour** [comment]
@CIPHERTron we could lead of [this section](https://docs.brigade.sh/intro/quickstart/#log-into-brigade) with a disclaimer of sorts. Something like this:

> ⚠️ In this section, we'll be logging in as the root user. This option should typically be disabled in a production-grade Brigade deployment. Read more about user authentication [here](https://docs.brigade.sh/topics/administrators/authentication/).

**Comment by AnuragThePathak** [comment]
Can I work on this issue?

**Comment by krancour** [comment]
@AnuragThePathak it's yours.

**Comment by AnuragThePathak** [comment]
Thanks, I'll try to finish the task as soon as possible.
Btw I was using --root to log in while trying to replicate the issue in #1750 . Is that why I was not getting the inappropriate error?

**Comment by krancour** [comment]
@AnuragThePathak it might have been. I'll try that way. Thanks for mentioning.
