### ISSUE TITLE
brig CLI for arm64 architectures

### ISSUE THREAD

**Issue by thomastaylor312** [brigadecore/brigade#1546]
Right now there are only binaries for x86 Macs and people with newer macs will be forced to use rosetta for things. It would be nice if there were builds for ARM Macs. No need to build the server for it I think, but the CLI would be useful

**Comment by krancour** [comment]
> No need to build the server for it I think

We definitely need arm64 for the server side also, but that's a taller order.

We can start building and publishing arm64 CLI binaries _today_ however.

**Comment by krancour** [comment]
Let's also do arm64 CLIs for Windows and Linux.
