### ISSUE TITLE
add event summary field

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1590]
Events have a payload that bears _input_ from the source (upstream system, via gateway) to the worker/script that handles the event.

There's currently no complementary mechanism that allows a handler to "return" output.

This issue proposes adding a "summary" field to events.

Brigadier currently allows events to be handled like so:

```TypeScript
events.on("brigade.sh/cli", "exec", async event => {
  // Handle the event directly or delegate to jobs...
});
```

As you can see, the handler function receives an event as a param and returns nothing. i.e. Return type is `void`.

I'd like to propose that the return type be changed to `void` _or_ `string`. (I'm pretty sure TS/JS can do that.) Since void would still be supported, this would not be a breaking change.

If a `string` is returned by the handler, the worker can treat it as a summary and automatically use the API to persist this.

Gateways that monitor the status of events they have created for purposes of reporting status upstream may be able to make good use of information found in the summary.

My WIP in Slack gateway is a good example of a gateway that would get a lot of value out of this enhancement. This gateway translates Slack slash commands into events. Events are immediately ack'ed and then monitored for completion. Currently, upon completion, the gateway messages the channel from which the slash command originated to provide a status update. Knowing an event succeeded is often not sufficiently contextually useful for the human user who reads the status update message in slack. Users would likely derive more benefit if the status update messages included a use case specific summary created by the worker/script that handled the event.

cc @itowlson because this idea came via a chat I had with you. Thanks!

**Comment by vdice** [comment]
Sounds good to me, and I do like the backwards compatible approach.  Only thought: do we envision having a need for a more well-defined return type -- perhaps an object with the capacity for multiple fields?

**Comment by krancour** [comment]
@vdice that's a good thought, but I think I am resisting overcomplicating this.

The upstream originator of the event and/or the gateway have one chunk of free-form input that they pass _to_ the worker (payload). I think the symmetry of answering back with one chunk of free-form output makes this easy to understand.

fwiw... there's no reason the output string cannot contain json just like the payload might contain json.

**Comment by vdice** [comment]
Good point re: json possibility.  SGTM!
