### ISSUE TITLE
Revisit Helm chart install instructions, etc. with Helm 3.7.0

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1594]
Helm [3.7.0](https://github.com/helm/helm/milestone/111) is anticipated to ship with [changes to the experimental OCI support](https://github.com/helm/helm/pull/9782) that we rely on for installing Brigade (and all (?) Brigadecore Gateways).  Let's see what needs updating in docs, etc., once 3.7.0 is out.

**Comment by krancour** [comment]
Wow!

`helm install oci://example.com/charts/nginx --version 0.1.0`

That is great!!!

I can't wait for this!

**Comment by krancour** [comment]
We've tested this out on a "lesser" project in the Brigade 2 ecosystem.

See https://github.com/brigadecore/brigade-noisy-neighbor/pull/4

**Comment by krancour** [comment]
Just a quick update that _all_ v2 compatible gateways and other peripherals are now using Helm 3.7.0 (rc.1) for publishing charts and for installation.

It's working well, so we'll be sure to give Brigade itself the same treatment in conjunction with the beta.3 release.

**Comment by vdice** [comment]
🎉 [Helm v3.7.0](https://github.com/helm/helm/releases/tag/v3.7.0) is out!
