### ISSUE TITLE
Brigade Design: A high-level explanation of how Brigade is designed.

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1606]

**Comment by vdice** [comment]
I was thinking of giving @krancour first dibs on this, in honor of his vision for Brigade v2 starting with the very first prototype, etc.

**Comment by krancour** [comment]
Thanks @vdice. I'm happy to take this on, but I'll defer to you about where in the doc tree this belongs.

**Comment by vdice** [comment]
🎉 Looking forward to it!

The Design doc remains in the same place from v1 (under Topics) and just needs updating: https://github.com/brigadecore/brigade/blob/v2/docs/content/topics/design.md

(We can move it/re-org as well, if this makes sense.)
