### ISSUE TITLE
Securing Brigade: Securing Brigade via TLS, Ingress and Third-Party Auth

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1608]

**Comment by krancour** [comment]
Wondering if TLS and 3rd party auth should be completely separate sections of the documentation.

**Comment by vdice** [comment]
> Wondering if TLS and 3rd party auth should be completely separate sections of the documentation.

Yea, this issue title stems from the corresponding entry in the meta docs issue, which was written a while back.  Currently, TLS setup is described in the [Deployment doc](https://v2--brigade-docs.netlify.app/topics/operators/deploy/) and 3rd-party auth in the [Authentication doc](https://v2--brigade-docs.netlify.app/topics/administrators/authentication/).

**Comment by vdice** [comment]
Closed by https://github.com/brigadecore/brigade/pull/1609
