### ISSUE TITLE
Script dependencies via brigade.json not supported?

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1636]
It appears that use of a `brigade.json` file to declare dependencies for a project and its script is no longer supported, though this filename is still mentioned in various API documentation (e.g. in [workers.ts](https://github.com/brigadecore/brigade/blob/v2/v2/brigadier/src/workers.ts#L15)).

Indeed, the example projects that declare deps do so via a package.json file (e.g. the [npm example](https://github.com/brigadecore/brigade/tree/v2/examples/07-npm))

Assuming Brigade v2 now only works with package.json files and won't support brigade.json files, we should remove mentions of the latter.  I discovered this while updating the [Dependencies doc](https://github.com/brigadecore/brigade/issues/1634), so I can make updates there to reflect the current state of v2.

**Comment by krancour** [comment]
Good catch on the errant mention. That line of doc must have been written prior to the cut over to an package.json.
