### ISSUE TITLE
jobs.[volumes|volumeMounts] does not appear to work for existing persistentVolumeClaims (efs-sc)

### ISSUE THREAD

**Issue by harrylepotter-win** [brigadecore/brigade#1643]
Output of `brig version`:
v1.4.0

Output of `kubectl version`:
`
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
`
Cloud Provider/Platform (AKS, GKE, Minikube etc.):
`AKS`

---
I have a basic job that is attempting to mount an existing volume claim:
```
const { events, Job } = require("brigadier");
events.on("exec", () => {
  var job = new Job("do-nothing", "alpine:3.8");
  job.privileged = true;
  job.tasks = [
    "echo Hello",
    "echo World"
  ];

  var volume = {
    name: "some-content",
    persistentVolumeClaim: {
      claimName: "some-existing-claim"
    }
  };
  
  var volumeMount = {
    name: "some-content",
    mountPath: "/mypath"
  }
 
  job.volumes = [volume];
  job.volumeMounts = [volumeMount];
  job.run();
});
```

However, when running this, the job appears to timeout:
```
Event created. Waiting for worker pod named "brigade-worker-01fgnn3yqc7qcfa1fp444yvf33".
Build: 01fgnn3yqc7qcfa1fp444yvf33, Worker: brigade-worker-01fgnn3yqc7qcfa1fp444yvf33
prestart: no dependencies file found
[brigade] brigade-worker version: 1.2.1
[brigade:k8s] Creating PVC named brigade-worker-01fgnn3yqc7qcfa1fp444yvf33
[brigade:k8s] Creating secret do-nothing-01fgnn3yqc7qcfa1fp444yvf33
[brigade:k8s] Creating pod do-nothing-01fgnn3yqc7qcfa1fp444yvf33
[brigade:k8s] Timeout set at 900000 milliseconds
[brigade:k8s] Pod not yet scheduled
[brigade:k8s] brigade/do-nothing-01fgnn3yqc7qcfa1fp444yvf33 phase Pending
[  Error: time limit (900000 ms) exceeded
  
  - k8s.js:670 Timeout._onTimeout
done         
    /home/src/dist/k8s.js:670:24
  
  - timers.js:549 listOnTimeout
    internal/timers.js:549:17
  
  - timers.js:492 processTimers
    internal/timers.js:492:7
  
]
[brigade:app] error handler is cleaning up
[brigade:k8s] Destroying PVC named brigade-worker-01fgnn3yqc7qcfa1fp444yvf33
[brigade:app] [  Error: job do-nothing(do-nothing-01fgnn3yqc7qcfa1fp444yvf33): Error: time limi  t (900000 ms) exceeded
```

Not sure what's going on here. For reference, the existing claim (some-content) is in the same namespace, and is of type `efs-sc`

I'm working off information here: https://github.com/brigadecore/brigadier/pull/22
and off the brigade.sh documentation.

Many thanks

**Comment by harrylepotter-win** [comment]
closing. I think this might be on my kubectl storageClass config side

**Comment by krancour** [comment]
@harrylepotter-win I'll try to re-create this. In the meantime, are you able to do `kubectl details` on both the job pod and the PVC?

My gut says something (possibly lower level than Brigade) prevented the claim from succeeding, which ultimately led to the timeout.

**Comment by krancour** [comment]
Whooops. Our moat recent comments crossed.

Cool. Please do reopen if you need more help.
