### ISSUE TITLE
Expand Contributing doc

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1694]
We should have a dedicated Contributing doc that is much more inviting for potential contribs.  Currently, https://v2--brigade-docs.netlify.app/topics/contributing/ just links back to the community Contributing.md which is more around signing commits and formalities.

A few thoughts:

 - Add a link to issues in the main brigade repo tagged 'good-first-issue' (e.g. https://github.com/brigadecore/brigade/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
 - Mention/link to auxiliary repos that also are ripe for outside contributors (gateways? sdks?)
 - Link to the [QuickStart](https://v2--brigade-docs.netlify.app/intro/quickstart/) and/or [Developers](https://v2--brigade-docs.netlify.app/topics/developers/) docs
 - Other/more?

**Comment by hamees-sayed** [comment]
@krancour would love to work on this. Am I supposed to add all the links that might be useful for potential first-time contributors to the contributing doc in the main repo?

**Comment by krancour** [comment]
@hamees-sayed, I think there may be more to this issue than just adding those links. I think those were just one part of it.

I appreciate the enthusiasm and I really hate asking a volunteer _not_ to work on an issue, but I think the nature of this one is such that it should probably be handled by someone with extensive prior experience contributing to the project.

If you want, I can look for and recommend issue you might want to take on.

**Comment by hamees-sayed** [comment]
@krancour Understandable 👍
 Yes, you can definitely recommend me some other beginner issues to work on. I'll be glad
