### ISSUE TITLE
Auth & CORS on API server 

### ISSUE THREAD

**Issue by bacongobbler** [brigadecore/brigade#17]
<a href="https://github.com/technosophos"><img src="https://avatars1.githubusercontent.com/u/89193?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [technosophos](https://github.com/technosophos)**
_2017-09-13 17:00:59_

----

The API server currently allows any connections (via CORS) and has no auth. We should probably do a sing OAUTH2-based solution.

**Comment by technosophos** [comment]
Might be able to use this for the time being: https://github.com/bitly/oauth2_proxy

**Comment by radu-matei** [comment]
We're no longer recommending / exposing the API server.
If this is still an active request, feel free to re-open.
