### ISSUE TITLE
`brig term` freezes on refresh when not connected to a server

### ISSUE THREAD

**Issue by snprajwal** [brigadecore/brigade#1707]
Steps to reproduce:
- run `brig term` without being connected to a server
- hit `F5` or `r`, and then try to exit with `q`

The terminal freezes until the client completes 5 attempts to connect to the server. I think this situation can be handled a little more elegantly, like not launching term in the first place if a connection to the server is not established.

Unrelated to this, I also think it would be nice to display a message while trying to connect to the server, just so the user knows what is going on

**Comment by snprajwal** [comment]
>It's also possible that ~/.brigade/config exists, but the server is unreachable. That's where #1208 comes into play.

This is the situation I was referring to

>@snprajwal I assume you'd like to work on this one?

I will be on vacation until Thursday, so if the delay is not a problem, I'll work on it once I'm back 👍

**Comment by krancour** [comment]
> so if the delay is not a problem, I'll work on it once I'm back

@snprajwal sounds good. In the meantime, enjoy your time off!
