### ISSUE TITLE
bug: deleting a project that doesn't exist tells you you're unauthorized

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1750]
Instead, it should probably tell you the project doesn't exist.

**Comment by snprajwal** [comment]
When I try this locally, it says `project "project_name" not found`

**Comment by krancour** [comment]
I'll see if I can re-create the issue.

If I recall correctly, the circumstances might have bee that the project _did_ exist, I deleted it, then accidentally tried to delete a second time after it was gone and that is when I noticed this issue.

**Comment by AnuragThePathak** [comment]
> I'll see if I can re-create the issue.
> 
> If I recall correctly, the circumstances might have bee that the project _did_ exist, I deleted it, then accidentally tried to delete a second time after it was gone and that is when I noticed this issue.

I tried this way a few times but getting project <project-name> not found only.

**Comment by krancour** [comment]
This was easy to recreate with v2.3.1:

```
$ brig project delete -i hello-world

? This action cannot be undone. Are you sure? Yes

Project "hello-world" deleted.

$ brig project delete -i hello-world

? This action cannot be undone. Are you sure? Yes


The request is not authorized.

$
```

**Comment by krancour** [comment]
And what version of brigade?

**Comment by krancour** [comment]
New datapoint that has come to light is that this might be replicable only when you're not logged in as root.

**Comment by krancour** [comment]
@AnuragThePathak it works in local environments, too.

Episode 2 of Brigade in 5 Minutes covers it well -- and in a local environment.

https://www.youtube.com/watch?v=jCKf7YKiGjg

**Comment by AnuragThePathak** [comment]
I have found that in order to delete a project, we check for the Project Level role PROJECT_ADMIN.
Now, when we try to delete a project which doesn't exist, authorization fails as we are checking for project level roles.
Now will it be fine if I check for the system-level role ADMIN?

**Comment by krancour** [comment]
System `ADMIN` and `PROJECT_ADMIN` are different things-- the latter granting rights to do things like add and delete users and service accounts, and the former granting rights to administrative functions on a specific project.

I think the best thing to do here is to confirm the project's existence before checking permissions.

**Comment by krancour** [comment]
@AnuragThePathak were you interested in working on this one?

**Comment by AnuragThePathak** [comment]
> @AnuragThePathak were you interested in working on this one?

Yes I'm working on it, almost covered the doc part of brigade, now working on the codebase.

**Comment by AnuragThePathak** [comment]
> I think the best thing to do here is to confirm the project's existence before checking permissions.

Ok, I can do try that way. What I was thinking is that only PROJECT_ADMIN and ADMIN have the privilege to delete a project. So if someone else tries to delete an project we should simply tell them request unauthorized.
Because if we tell them project doesn't exist users who doesn't even have read access will be able to know what projects exists. That was my thought.

**Comment by AnuragThePathak** [comment]
@krancour to test the changes I've made in brigade api-server, I've ran `make hack-new-kind-cluster` followed by `export DOCKER_REGISTRY=localhost:5000` and `make hack` but I'm unable to figure out how can I apply custom values file.

**Comment by krancour** [comment]
@AnuragThePathak I usually edit the `values.yaml` directly when I'm hacking.

**Comment by AnuragThePathak** [comment]
@krancour I'm not getting how you edit values.yaml in case of hacking? Do you mean using of --set flag with upgrade?

**Comment by AnuragThePathak** [comment]
Moreover, I don't know what will be the repo name if I need to run helm upgrade. I have simply deployed it using make hack-deploy inlcuded in make hack

**Comment by krancour** [comment]
> I'm not getting how you edit values.yaml in case of hacking

Just edit `charts/brigade/values.yaml`

> Moreover, I don't know what will be the repo name if I need to run helm upgrade

There's an open issue [here](https://github.com/brigadecore/brigade/issues/1694) for developer workflow to be documented better.

The intention, however, is that you edit as you see fit and then `make hack`. Edit some more. `make hack` again.

**Comment by AnuragThePathak** [comment]
@krancour when I run make hack, almost equal amount of incoming and outgoing data transaction occurs. Where does the data gets uploaded?

**Comment by krancour** [comment]
Not sure I understand the question.

It builds every image, pushes each to a registry (which is ideally local) and then does a `helm upgrade`.

**Comment by AnuragThePathak** [comment]
If that's the only case, then fine but system monitor was showing some outgoing network which happens only if we upload some files.

**Comment by krancour** [comment]
@AnuragThePathak was it probably showing the images pushing to the registry?

**Comment by AnuragThePathak** [comment]
@krancour  Isn't it supposed to push images to local private registry only?

**Comment by krancour** [comment]
@AnuragThePathak it's whatever registry you define using `DOCKER_REGISTRY` and `DOCKER_ORG` env vars. Ideally it's local to save time and bandwidth, but it doesn't have to be. You may want to check.

**Comment by AnuragThePathak** [comment]
@krancour DOCKER_REGISTRY is localhost:5000 but I haven't defined DOCKER_ORG. Is it required when I've no intention to push outside?

**Comment by krancour** [comment]
Nope. I don't set it either.

As for the outbound data... idk what monitor you're using, but remember `localhost:5000` isn't really "local." That is to say, the local registry isn't actually _listening_ on the local network interface. It's listening on a Docker bridge network and `localhost:5000` just forwards to there. It's possible your monitor regards packets flowing between two network interfaces as outbound. I'm somewhat guessing here. I know just enough about Docker networking to get by.
