### ISSUE TITLE
v1 docs need nicer URL

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1758]
Currently, it's this: https://v1--brigade-docs.netlify.app/

That can obviously be improved.

**Comment by snprajwal** [comment]
Can't we just do something like `docs.brigade.sh/v1`?

**Comment by krancour** [comment]
I'd be fine with that except, what lives at `docs.brigade.sh` is the _static_ v2 docs site. There's really no way to do path-based routing from there to another site -- namely the static v1 docs site.

The easiest thing is probably `v1.docs.brigade.sh`. Sorry I've dragged my feet on that. Going to square it away right now.

**Comment by krancour** [comment]
This is all set.

https://v1.docs.brigade.sh exists now and I've opened #1778 to update the link from the v2 docs to the v1 docs.
