### ISSUE TITLE
Test data access code against a live database

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1811]
⚠️ __Important: This issue is currently reserved as a potential [Google Summer of Code](https://summerofcode.withgoogle.com/) project. No one should do any work on this without first being formally paired with our project for GSoC'22.__

Brigade is composed of many components. Among them, the API server could be considered the platform's brain and central nervous system. The API implements a clean abstraction over underlying services such as our database (MongoDB), our messaging system (Artemis), and our workload execution substrate (Kubernetes). All other Brigade components accomplish most of their work through API calls.

Where integration with the database is concerned, API server code is currently _unit-tested_ against mock implementations of MongoDB client interfaces. These tests have been adequate for asserting that queries and statements are constructed properly (look like we think they should) and that mock query and statement results can be unmarshaled without error into domain types, but this approach _cannot_ assert that DB queries and statement are logically correct and actually achieve the desired results, since a live database would be required to accomplish that. We do also have a suite of integration tests that run against a live instance of Brigade (database and all), but they are closer to end-to-end tests, so they do not isolate data access code. They may detect issues from time to time, but they're a poor way of pinpointing the root cause.

Given the importance of the data access code, we would like to develop a new suite of integration tests directly targeted at that code. These new tests should run against a live (and disposable) MongoDB database and assert that all queries and statements achieve the desired results. If the new suite of tests exposes bugs in the existing data access code, correcting those bugs is within the scope of this project as well.

No significant prior knowledge of Brigade or its codebase is required to work on this issue since the work is highly localized to a few discrete packages. The successful candidate will have _strong_ Go and git skills and at least a working knowledge of Docker, since containers are likely the easiest way to _quickly_ stand up and tear down a disposable test database. Prior knowledge of MongoDB would be an asset, but it is entirely possible that a successful candidate will be able to learn MongoDB as they go.

The expected outcome of this GSoC project is the new test suite merged into Brigade's main branch and fully integrated into our CI/CD processes.

This is estimated to be a low difficulty project that a qualified candidate can complete with roughly 175 hours of effort.

**Comment by a-muk** [comment]
Hello! I would like to contribute to this project for GSOC'22. Can you please guide me a bit more about it?

**Comment by krancour** [comment]
Hi @a-muk! Welcome!

Brigade has many components, but (similar to Kubernetes) the API server is the "brain" that does most of the real work. It's the only component that talks to the database (MongoDB) and the code and tests for that are all found under `v2/apiserver/internal/api/mongodb`.

My mind's not made up yet on whether we should supplement the existing tests in that package or _replace_ them, but either way, the goal would be to develop new tests that talk to a live database. These new tests should be [tagged](https://mickey.dev/posts/go-build-tags-testing/) so that they don't execute along with the the unit test suite, but execute only when explicitly requested. (The idea is that these tests _shouldn't_ run unless told a live DB is indeed available.)

The general shape of each test in the new suite would basically involve priming the database to put it in a known state, then asserting that all queries return the expected results and all statements make the expected modifications.

(Aside: If, in the course of developing these new tests, opportunities are discovered to improve the elegance or efficiency of data access code without changing the DB schema, those improvements can be part of this project as well.)

For CI, we use Brigade to build/test itself. Brigade can pretty easily make a live DB available during CI, so there would be minor modifications to our CI scripts (and maybe our `Makefile`) as part of this project as well.

Maintainers would be willing and available to pair/assist on any aspect of this project. If you want to discuss more, let's connect on Slack. We have a channel on the Kubernetes Slack and you can find it quickly using https://slack.brigade.sh.

**Comment by a-muk** [comment]
Thank you! Can I get an invite to the slack workspace? I tried using that link but I think that is only for those who are already there in it.

**Comment by krancour** [comment]
@a-muk you have to join the Kubernetes Slack workspace. Our channel is part of their workspace.

Try https://slack.kubernetes.io

**Comment by a-muk** [comment]
@krancour yes I tried that too, but still I wasn't able to join. Anyways, Thank you for the link🙂

**Comment by krancour** [comment]
@a-muk there was no "get my invite" button? I can contact people at CNCF this week to get it straightened out.

**Comment by a-muk** [comment]
It was actually asking to sign in or create an account.

**Comment by krancour** [comment]
> or create an account

☝️  Do that.

**Comment by a-muk** [comment]
@krancour Sorry I am very new to this. Thank you for helping 🙂

**Comment by meetguogengli** [comment]
Hey, @krancour  I would like to contribute to this issue since GSOC is approaching and the CNCF is one of the orgs I want to apply for. Can you please help me get started so that I can get familiar with the codebase and other things about the project

**Comment by krancour** [comment]
@meetguogengli please find me on the Kubernetes slack if you've got specific questions.

**Comment by meetguogengli** [comment]
Hi @krancour, I just added you on slack. Can you see my message?
