### ISSUE TITLE
README.md should mention cron event source

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1851]
The README.md currently lists other official brigade projects that are compatible with Brigade v2.

idk if we'll eventually get away from doing that, but for now, the cron event source is conspicuously absent from the page.

Let's add it: https://github.com/brigadecore/brigade-cron-event-source

**Comment by hamees-sayed** [comment]
Do we need to add cron-event-source as a bullet point under a new "Event Source" Heading?

**Comment by krancour** [comment]
Ah, yes. Gateways are a type if event source, but not all event sources are gateways. A new heading _after_ gateways would make sense. Let's have it say "Other Event Sources." The noisy neighbor could also be moved into that list.
