### ISSUE TITLE
docs: footer lacks a copyright notice

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1852]
Let's add a copyright notice to the footer. Let's also make sure we do _not_ remove attribution for Hugo and the theme we're using. Those should stay.

**Comment by hamees-sayed** [comment]
@krancour I would like to work on it, can I get more context on the copyright notice?! Am I supposed to link the apache-license to the footer?

**Comment by hamees-sayed** [comment]
@krancour can you please also point out the folder where the edit is required. I don't seem to find the specific directory

**Comment by felipeschulz** [comment]
@hamees-sayed I think its this index.html line 415 (right @krancour ?) 
https://github.com/brigadecore/brigade-www/blob/9eb7a902d8b901f96f24c0a627996c200a9866ed/index.html

**Comment by krancour** [comment]
@felipeschulz the brigade-www repo you're referencing is the landing page at https://brigade.sh. That's already got a copyright notice (although it could stand to be updated).

This issue's about the missing copyright notice on the docs site. All of that stuff is under `docs/` here in this repo.

**Comment by felipeschulz** [comment]
Ok, i understood. My fault. So @hamees-sayed , ignore my reply above 😅

**Comment by krancour** [comment]
No worries. Everyone's still learning their way around. 😄

**Comment by krancour** [comment]
@hamees-sayed refer to the `doc/` folder's own [readme](https://github.com/brigadecore/brigade/blob/main/docs/README.md#development) for details.

**Comment by hamees-sayed** [comment]
I went through the entire code but found nowhere the footer which has to be edited. I'll unassign this issue and let someone else work on it
