### ISSUE TITLE
Support for externally hosted MongoDb backing store

### ISSUE THREAD

**Issue by emilwangaa** [brigadecore/brigade#1876]
Currently Brigade doesn't support using a MongoDb hosted externally from Kubernetes like for instance MongoDb Atlas.

This would be a nice feature to add for people already having existing MongoDb infrastructure setup they would like to utilize.

**Comment by krancour** [comment]
Totally agree. I think I mentioned to you in a Slack convo that we supported this before v2 went GA and we took it out because of minor problems that weren't worth holding up the release for. I'm very happy to look at putting this back and working through the remaining issues with it.
