### ISSUE TITLE
bug: setting secrets on a non-existing project tells you're unauthorized

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1893]
This is only true if you're logged in as a real user and not as root.

The heart of the issue is the same as for #1750 and resolution should be the same as it was for #1884

cc @AnuragThePathak since you are already familiar with the fix, thanks to your great work on #1884, do you think you'd be willing to fix it here as well?

**Comment by AnuragThePathak** [comment]
Sure I would be happy to work on it, I might need 2-3 days to start working on it because I had to move from my home to hostel for the first time (as college opened) hence not getting time for a few days.

**Comment by krancour** [comment]
@AnuragThePathak no worries and no rush. Just happy to have you on the case.
