### ISSUE TITLE
components should dump important configuration to the logs at startup

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1918]
As I start my efforts to diagnose some outstanding bugs, I'm finding this would be extremely useful. It would be great to know when a component is perhaps not configured the way you thought it was.

Let's apply this to the apiserver, scheduler, and observer components for now.

Great care should be taken to only display _non-sensitive_ configuration -- no secretes.

**Comment by AnuragThePathak** [comment]
Should it be left for newbies or we can work as well?

**Comment by krancour** [comment]
Anyone. You want to tackle this @AnuragThePathak?

This should be relatively simple... maybe add a new function to each component's `main.go` that nicely formats the various config objects and that should do the trick.

**Comment by AnuragThePathak** [comment]
> Anyone. You want to tackle this @AnuragThePathak?

Actually I was looking for something to work on but among the recently created issues only the instrumentation one involving prometheus was neither assigned to anyone nor labeled as good-first-issue. But I am willing to learn prometheus now as I'm having college exams soon and I'm under-prepared for it. So interested in working with it if it's open for anyone.

**Comment by krancour** [comment]
@AnuragThePathak no one is restricted from taking issues that aren't labeled as good first issue. Those labels are just to help folks who are really new find easy issues to get started with.

I'll warn you, however, that the issue involving Prometheus is probably on the "very advanced" end of the spectrum. But please to try it if you feel confident!

**Comment by AnuragThePathak** [comment]
Are usernames considered as sensitive data? For example username in ReaderFactoryConfig?

**Comment by krancour** [comment]
I wouldn't say so, but I also am not sure that's a bit of info that will help much with troubleshooting. We want to focus on the things that will really help _us_ to sort out problems faster. Probably the most interesting bits of information would be options that the operator who installed Brigade selected such as limits to concurrency, refresh intervals -- things of this nature.

It was actually #1917 that inspired this issue because it would be convenient when troubleshooting an issue such as that one to be able to verify that the setting _is_ what I think it is. It helps distinguish between "something is wrong because the setting wasn't picked up correctly" and "something is wrong because the setting was picked up, but there's a bug that isn't honoring the setting."

**Comment by AnuragThePathak** [comment]
Makes sense.
