### ISSUE TITLE
Update homebrew formula for v2.4.0

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1938]
Our homebrew formula needs to be updated for v2.4.0.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/brigade-cli.rb

Really all that needs to be done is update the semantic version and the SHA (make the SHA match the version tag).

**Comment by karnatisrinivas** [comment]
Hello @krancour , Can i work on this??

**Comment by krancour** [comment]
Sure @karnatisrinivas. Thank you.

For reference, here's the PR from the last time this was bumped:

https://github.com/Homebrew/homebrew-core/pull/95974

**Comment by krancour** [comment]
v2.5.0 is out now, so skipping over v2.4.0.

https://github.com/Homebrew/homebrew-core/pull/101430
