### ISSUE TITLE
brig update -c fails if project doesn't exist and not logged in as root

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1947]
With `-c` set, the project should be created if it doesn't already exist, but instead there is an auth error.

This doesn't occur if you're root.

This may be a similar issue to #1893

cc @AnuragThePathak since you have experience fixing this exact sort of issue.

**Comment by AnuragThePathak** [comment]
Oh, the problem seems to exist in many of the actions. Should I try to find all possible places where that may exist and fix them?

**Comment by AnuragThePathak** [comment]
Btw can I work on this issue? I have end-semester exams throughout the next week, still can try to manage some time. If that doesn't get possible then shall fix it once it's over.

**Comment by krancour** [comment]
> the problem seems to exist in many of the actions. Should I try to find all possible places where that may exist and fix them?

That would be great. To help narrow it down, I think all such places would be project-related.

**Comment by AnuragThePathak** [comment]
Do I need to check for the READER role before informing that the project doesn't exist? I was thinking of doing that after project creation attempt fails only (i.e. towards the end of the function). 
I have observed that if opts.CreateIfNotFound is set to false, user is already being informed about non-existence of project without checking for READER role.

**Comment by AnuragThePathak** [comment]
By having a look at the Update function, it seemed to me that project-authorization attempt in case of a non-existing project is leading to authorization error. Haven't studied the Authorize function of project authorizer properly yet, as it involves principal and some other stuff which I am not aware at this moment.

**Comment by krancour** [comment]
Forgive me... I haven't looked yet, but is the root cause of the issue _not_ identical to https://github.com/brigadecore/brigade/issues/1893?

**Comment by AnuragThePathak** [comment]
Oh yeah, most probably they are indeed. I sadly was focusing on the -c flag.
Anyway will fix it within today.

**Comment by AnuragThePathak** [comment]
Btw I wanted to mention that use of tilt with ctlptl made the hacking experience really awesome.
