### ISSUE TITLE
Relocate brigade gateway microservices?

### ISSUE THREAD

**Issue by blimmer** [brigadecore/brigade#263]
Now that the brigade gateways are intended to be more "microservice"-y (see #99), I wonder if they should be relocated. A few thoughts:

## Individual Repos with a Common Repo Tag (Option 1)
In this option, both of the existing gateways (the container registry and the github registry) would get their own repos (e.g. `brigade-cr-gateway` and `brigade-github-gateway`). This option nicely splits out the logic, readmes, issue tracking, PRs, etc. into their own GitHub repositories. It also feels more "microservice-y" to me.

To aid in discoverability, we could utilize a common tag (`brigade-gateway`) on the repos. Then, the documentation could link to the officially supported gateways directly, but also allow for finding community built and maintained gateways. For an example, check out the [`ember-addon`](https://github.com/topics/ember-addon) tag.

## Monorepo (Option 2)
We could try using a monorepo that has all of the officially supported gateways inside it. For example, see the [kubernetes/charts](https://github.com/kubernetes/charts/) repo. This is nice from a discoverability perspective, but is painful for managing PRs, issues, maintainers, etc.

## Thoughts?
What are people's thoughts on this? This ticket also might make sense to do alongside #264 .

**Comment by technosophos** [comment]
So some ideas we've been discussing here:

- For official Azure Brigade projects, set up one repo per microservice, but have all issues go to Azure/brigade.
- Create one repository for all of the Helm charts, so that the user only needs to do one `helm repo add` But should this be the main brigade repo, or a separate repo?

**Comment by blimmer** [comment]
That sounds great to me - @technosophos how do you want to handle setting up those repos so folks can assist with the move?

**Comment by radu-matei** [comment]
Bumping this for visibility - `brigade-cr-gateway` and `brigade-generic-gateway` are still part of the main repo.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.

Note that in v2, all gateway source is separate from Brigade source-- each "official" gateway having its own repo in the brigadecore org.
