### ISSUE TITLE
Support git credentials in the default git-sidecar

### ISSUE THREAD

**Issue by brandon-bethke-neudesic** [brigadecore/brigade#270]
Please consider adding git credentials support in the default vcsSidecar, git-sidecar.

We do not use github.com and require credentials for our git access. If git-sidecar supported git-credentials, then we would not have to maintain our own vcs sidecar. Although, we do appreciate the option of overriding it.

Example:

```
.....
if [ "$VCS_GIT_CREDENTIALS_ENABLED" == "true" ]; then
    # Must set the credentials for access
    echo $VCS_PROTOCOL://$VCS_USERNAME:$VCS_PASSWORD@$VCS_DOMAIN > ~/.git-credentials
    git config --global credential.helper store
fi
git clone --depth=50 "${VCS_REPO}" "${VCS_LOCAL_PATH}"
.....
```

**Comment by technosophos** [comment]
We support SSH keys as credentials. We do this by overriding a few environment variables:

https://github.com/Azure/brigade/blob/master/git-sidecar/Dockerfile

So in your Git project you should be able to set up an sshKey value and use that. You can also use an auth token.

If neither of those are sufficient, I'll look into adding username/password. We just figured that the advantage of SSH keys and tokens is that it is easy to invalidate them if anything goes wrong.

**Comment by brandon-bethke-neudesic** [comment]
Understood. We do not use github.com. We created our own git host and at the moment we need the username/password support described above.
https://git-scm.com/docs/git-credential-store/1.7.12.1

**Comment by technosophos** [comment]
OK. Lemme see what I can do

**Comment by technosophos** [comment]
Now that the big sidecar rewrite is done, we might be able to try this again.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
