### ISSUE TITLE
brig CLI building and installation require simplification

### ISSUE THREAD

**Issue by pawelprazak** [brigadecore/brigade#330]
It took me a while to find this `make bootstrap brig` in https://github.com/Azure/brigade/blob/master/brig/README.md

Also the `bootstrap` target requires NPM, and there is no `install` target, so the actual steps are:
```
go get github.com/Azure/brigade
cd $GOPATH/src/github.com/Azure/brigade
dep ensure -v
go install -ldflags ' -X github.com/Azure/brigade/pkg/version.Version=v0.9.0-63-g1257f32' ./brig/cmd/brig
```
Expected behaviour:
- [ ]  `brig` installation instruction in the main readme
- [x]  `brig` binary available for download from the releases page
- [x]  `bootstrap` command should be refactored to not require NPM for everything
- [ ]  `install` target should be available for make: `make install brig`

**Comment by technosophos** [comment]
Good point. That would be a great feature to have. It will feel closer to the normal Make usage, too.

**Comment by pawelprazak** [comment]
`bootstrap` was addressed as a part of https://github.com/Azure/brigade/pull/329

**Comment by radu-matei** [comment]
And now we publish `brig` for Linux, Windows, and macOS as part of the releases.
Closing.
