### ISSUE TITLE
Support specifying the hostNetwork

### ISSUE THREAD

**Issue by smm190** [brigadecore/brigade#361]
Is there a way to specify 'hostNetwork: true' via brigade?  We are running into an issue where we can connect to our DB from the master and agent K8s nodes, but can't access it from pods running via Brigade.

Trying to see if something like this would fix the problem:

spec:
    **hostNetwork: true**

**Comment by technosophos** [comment]
On which pods? There's not a way to do this for workers and jobs, though I'd be open to adding something.

If you are mainly interested in hacking in support for testing, you can give this a shot:

- Clone the repo
- Edit `brigade-worker/src/k8s.ts` (Look for the `JobRunner`), and add `hostnetwork=true` where applicable
- Point your local `kubectl` to the cluster you want to test with
- Then execute something like this locally:

```bash
#!/bin/bash
export BRIGADE_EVENT_TYPE=exec
export BRIGADE_EVENT_PROVIDER=script
export BRIGADE_COMMIT_REF=master
export BRIGADE_PAYLOAD='{}'
export BRIGADE_PROJECT_ID=brigade-830c16d4aaf6f5490937ad719afd8490a5bcbef064d397411043ac  # Replace this
export BRIGADE_PROJECT_NAMESPACE="default"
export BRIGADE_SCRIPT=$(cat ./brigade.js | base64)
#export BRIGADE_SCRIPT="$(pwd)/brigade.js"

cd ../brigade-worker
echo "running $BRIGADE_EVENT_TYPE on $BRIGADE_SCRIPT for $BRIGADE_PROJECT_ID"
yarn brigade
```

That will run the worker locally, but execute the jobs in-cluster.

**Comment by smm190** [comment]
@technosophos I would like this setting to be applied to the node the job is running on...But maybe I am going down the wrong rabbit hole.  Looking through the k8s.ts file, where would I add hostnetwork=true?

The issue seems to be at the pod-layer because we can telnet to the DB IP & port from both our K8s master node and agent nodes, but when I include a ping or telnet in the tasks of the Brigade job, they can't connect to the DB IP.  Any insight on this?

Hav

**Comment by technosophos** [comment]
One easy way to debug it is to launch a simple pod into the cluster (I use something like Alpine:3.7) and then use `kubectl exec -it $THAT_POD /bin/sh` and then try debugging from inside that pod.

**Comment by smm190** [comment]
@technosophos I need a way to be able to specify "hostNetwork: true" under "spec", just like I would in the YAML file if I was launching the pod using kubectl.  Is there a way to do this so that when Brigade launches my pods, it sets hostNetwork to true so that the pods can assume the network of the host machine?

**Comment by technosophos** [comment]
Oh, I see. There is no way to do that currently. I'll mark this as a feature request.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
