### ISSUE TITLE
Idea for Simplifying Creation of Basic Gateways

### ISSUE THREAD

**Issue by blimmer** [brigadecore/brigade#406]
After talking with @technosophos , we started to notice that many of the gateways are very slight variations on the same basic concepts:

* draw a simple route
* expect some parameters
* create the secrets to trigger the job

I wonder if there's a way we could make this pattern a bit easier using by using a well-defined schema and allow users to provide their own middleware for custom logic handling. The first things that come to mind are [Express.js](https://expressjs.com/) for the server and [Convict](https://github.com/mozilla/node-convict) for a well-defined schema.

(the below is all psuedo code 😄 )

In the schema you could provide the routes you want to listen to (using convict as the example here):

```javascript
var config = convict({
  routes: {
    doc: "The routes for the express application to listen to",
    format: Array
  },
);
```

And then the user could provide various middlewares if they need to, like for auth, etc. Maybe the user then provides a `server.js` file that the gateway pulls in:

```javascript
import { server } from 'brigade-gateway'; // server "is an" Express app and reads in your config, draws your defined routes from the schema, etc.

server.use(function (req, res, next) {
  // do auth things!
  next();
});

server.listen(8000);
```

Under this pattern, distributing other gateways becomes simple configuration that lowers the barrier to entry. By using node, we don't have to compile everything like we do with the gin gateways. It also unlocks the ability for Brigade to make updates that should be included in all gateways (like changes to how secrets are created to trigger jobs, etc.)

**Comment by lukepatrick** [comment]
I like the concept. Agreed, at a high level gateways are rather similar. 

What makes them unique is how each does a simple auth with the request, interprets and processes the data that is sent to the secret.

If not a reusable gateway, encourage reusable components for your gateway. I'm using shared packages that handle the interactions/deserialization with GitLab/BitBucket (and could do GitHub) that others use outside of the scope of Brigade.

**Comment by radu-matei** [comment]
Additionally, we could consider template repositories for gateways in programming languages we already have support for.

- [ ] Go
- [ ] JavaScript (NodeJS)
- [ ] Rust (@technosophos recently built https://github.com/technosophos/buck)

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.

Note that in v2, this lead to the creation of the brigade-foundations project.
