### ISSUE TITLE
`yarn -s start` adds unneeded output on failures

### ISSUE THREAD

**Issue by jdotjdot** [brigadecore/brigade#418]
On errors and failures, the `brig` CLI produces unneeded and verbose error output. It looks particularly bad when used in conjunction with a slackbot (like we're doing).  Example at the bottom (not the mangled terminal colors, but the "An unexpected error occurred"):

![image](https://user-images.githubusercontent.com/1328961/38343079-e55a1728-384f-11e8-94a1-ee17e3ebc1eb.png)

It seems that this is coming from yarn, since `yarn -s start` is being run. 

Is there a way to silence this output or to run the script directly rather than via `yarn run`?

**Comment by radu-matei** [comment]
I think it is worth exploring changing the default start script to strip ANSI characters - see #801 

https://github.com/brigadecore/brigade/blob/2218bcf12b4005256713c4caa0ca9e5cb87e89ab/brigade-controller/cmd/brigade-controller/controller/handler.go#L84

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
