### ISSUE TITLE
Configurable Worker (via Controller)

### ISSUE THREAD

**Issue by technosophos** [brigadecore/brigade#449]
There are a number of requests for making the worker's pod definition more configurable. Is there a general way (like via  a template) that we could make the pod definition more configurable in the controller?

(This was asked at KubeCon EU 2018)

**Comment by Strandedpirate** [comment]
That may work. We basically just need to run some custom git commands against the src code (at least for now). This is what I have working so far in a custom worker. I haven't looked at the sidecar but it sounds like I can just move my git commands over there.

dockerfile
```
FROM deis/brigade-worker:latest

COPY . /

RUN apk update && apk add --no-cache \
    ca-certificates \
    git \
    openssh-client \
    && update-ca-certificates \
    && chmod 777 /start.sh \
    && chmod 777 /extractGitCommitFiles.sh
```

start.sh
```
#!/bin/sh

/extractGitCommitFiles.sh

# brigade needs this to run first
node prestart.js

# run brigade's main script
node --no-deprecation ./dist/index.js
```
extractGitCommitFiles.sh
```
#!/bin/sh

cd $BRIGADE_WORKSPACE
git diff-tree --no-commit-id --name-only -r $BRIGADE_COMMIT_ID > /home/src/gitFileList.txt
cat /home/src/gitFileList.txt
cd -
```

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
