### ISSUE TITLE
Worker possibly destroying PVC Early

### ISSUE THREAD

**Issue by smm190** [brigadecore/brigade#465]
I have a brigade script that spins up a bunch of containers who's processes take anywhere from 10-50min to complete.  After about 30 minutes, brigade apparently destroys the persistent volume all of the pods are using, and the ones that haven't completed yet fail.  I get a `"pod failed to run to completion" `error from the brigade output and see a `PersistentVolumeClaim is not bound: "brigade-worker-01ce45w7t0ssmq05ey4bmp9w1g" (repeated 5 times)
` error after 30 minutes of the pod running.

I tried setting the Job.timeout variable in my brigade.js, but it didn't have any effect.  This is the main logic of my brigade.js:

```
  for(i=0; i<20; i++) {
    console.log(servers[i])
    var jobName = "adltocsvadl-"+servers[i]
    jobName = jobName.substring(0,32).toLowerCase()
    var job = new Job(jobName, image)
    job.timeout = 10000000
    job.tasks = ["/app/datalakeToCSVDataLake.sh -y /mnt/brigade/share -s " + servers[i]  + " -d 20180417"]
    job.storage.enabled = true
    job.run()        

  }
```

```
 Error: Pod adltocsvadl-ch12abcdefg-01ce45w7t0ssmq05ey4bmp9w1g failed to run to completion
  
  - k8s.js:367 k.readNamespacedPod.then.response
    ./dist/k8s.js:367:32
  
 [brigade:app]   Error: job adltocsvadl-ch12labcdefg(adltocsvadl-ch12abcdefg-01ce45w7t0ssmq05e  y4bmp9w1g): Error: Pod adltocsvadl-ch12abdefg-01ce45w7t0ssmq05ey4bmp9w1g failed to run to completion
  
  - brigadier.js:56 jr.run.catch.err
    ./dist/brigadier.js:56:35
  
  
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
  
 [brigade:app] error handler is cleaning up
[brigade:k8s] Destroying PVC named brigade-worker-01ce45w7t0ssmq05ey4bmp9w1g
[brigade:k8s] default/adltocsvadl-ch12abcdefg-01ce45w7t0ssmq05ey4bmp9w1g phase Running
[brigade:k8s] default/adltocsvadl-ch12abcdefg-01ce45w7t0ssmq05ey4bmp9w1g phase Running
error Command failed with exit code 1.
```

When I run kubectl logs <podname>, I see an error indicating that the pod no longer can access the persistant volume it needs to process its files.  The first error I see after 30 minutes of running is a "PVC not bound" error, so I'm guessing brigade is spinning down the persistent volume after a 30 minute threshold.

```
$ kubectl logs adltocsvadl-ch12abcdefg-01ce45w7t0ssmq05ey4bmp9w1g
Datalake Metaverse to Datalake CSV Run Started at Tue May 22 15:01:11 UTC 2018
Processing the following servers for this run ->
PROCESSING RUNNING IN /mnt/brigade/share/tempdir_16309
Executing
python3 /app/datalakeToCSVDataLake.py -y /mnt/brigade/share -s ch12abcdefg -d 2                               0180417
20180417
Traceback (most recent call last):
  File "/app/datalakeToCSVDataLake.py", line 605, in <module>
    sys.exit(main(sys.argv))
  File "/app/datalakeToCSVDataLake.py", line 176, in main
    processFiles(argsDict['local_file_directory'], argsDict['rawEvent'], start_d                               ate, end_date, servers)
  File "/app/datalakeToCSVDataLake.py", line 423, in processFiles
    dtValue = dtValue.replace('T', ' ')
AttributeError: 'list' object has no attribute 'replace'
Return code from Python = 1
cat: *.log: No such file or directory
Run Ended at Tue May 22 15:30:22 UTC 2018
```

Is there another way to increase the amount of time the brigade job runs for?

**Comment by technosophos** [comment]
The PVC should not be destroyed until the worker pod itself is destroyed. It _shouldn't_ be automatically cleaned up during processing. The log you show above seems to show the expected behavior: The container exits, then the error handler cleans up, then the PVC is destroyed.

That said, there could be a bug somewhere in Brigade.

The only timeout on a job is the one you mentioned (`Job.timeout`), and there are no timers on workers or on PVCs. One thing you could try is to see if you can run a second job when the first one fails, and connect that to the PVC.

```javascript
job.run().catch( (err) => {
  checkPVC = new Job("checkpvc", "alpine:3.7")
  checkPVC.storage.enabled = true
  checkPVC.tasks = [
    "ls /mnt/brigade/share"
  ]
   checkPVC.run().then(res => {
    console.log(res.toString())
   })
})
```
That would indicate whether the PVC is being destroyed early, or if it's being detached early (but not yet destroyed), which might help us find the problem.
Also, what kind of volume is backing the PVC?

**Comment by radu-matei** [comment]
Any updates on this, @smm190 ?

Thanks!
