### ISSUE TITLE
how to set environment in brigade worker?

### ISSUE THREAD

**Issue by veeramarni** [brigadecore/brigade#477]
Is it possible to pass environment variables to a custom worker? We would like to have `worker` to notify through a messaging bus about the current step in addition to what brigade does. We can do it in the `event` callback function but we think it would optimal if brigade worker connects to the messaging broker before it handles the events. 

brigade.js 
---
```
const client = nats.connect({
     'url': process.env.NATS_URL,
     'user': process.env.NATS_USER,
     'pass': process.env.NATS_PW,
});

client.ready(() => {
    events.on('ourevent', async (event, project) => {
        let payload = JSON.parse(event.payload);
 ......
})

```

**Comment by technosophos** [comment]
Currently, the controller does not let you pass arbitrary env vars to the worker. The following alternatives might work for you, though:

- You can put the data in the `secrets` section of the project
- You can override the vcsImage and write that info to a config file (but not to env vars)
- If you are using a custom gateway, you can send them in the payload

**Comment by veeramarni** [comment]
We are already using `custom gateway`. But the payload will only receive when the even triggered like you see in my earlier code. 

So do you suggest we do following instead? 


```
    events.on('ourevent', async (event, project) => {
        let payload = JSON.parse(event.payload);
    const client = nats.connect({
       'url':payload.NATS_URL,
       'user': payload.NATS_USER,
       'pass': payload.NATS_PW,
    });

    client.ready(() => {
   // send notification
    })

.....
    })

```

**Comment by technosophos** [comment]
Yeah, that is the approach I would advocate.

**Comment by radu-matei** [comment]
Starting with #494 there is a `brigade.json` used to pass custom dependencies for the worker. 
This functionality only uses the `dependencies` node in the file - would it make sense to use it to pass environment variables?

Keep in mind that the file will be present in source control, so this approach doesn't currently work with private information.

What do you think?

**Comment by ESTrainer** [comment]
Unless the source control is a private repo we cannot pass secrets in it, so i don't think it would be that useful. I was wondering if the Worker has its own helm chart so we can pass secrets through it, would be a better option.

**Comment by technosophos** [comment]
The worker is created by the brigade-controller, which directly creates it via API. There are a few values that get passed from the main Brigade chart into the worker, but that's it.

Is the situation that you want the same secrets for _every_ worker? That is a situation we might need to add a feature to support.

**Comment by veeramarni** [comment]
When we add dependencies to `brigade.json` will it download the dependencies everytime? If that is the case it is better to upgrade worker's Dockerfile?

**Comment by radu-matei** [comment]
@veeramarni - when using the `brigade.json` file, the worker is the standard one (the same one used for all builds). This means that yes, the dependencies are downloaded on every build.

If the dependency download time and frequency of that specific build call for it, then yes, it might make sense to have a custom worker - but if the build is infrequent or downloading the dependencies is not an issue, you can stick with using the `brigade.json` file.

Does it make sense?

**Comment by veeramarni** [comment]
@radu-matei sorry for my late reply. Regarding environment variables in `brigade.json` would make sense for basic variables like `logLevel` etc.

**Comment by krancour** [comment]
This was fixed in the `v2` branch ages ago. Closing.
