### ISSUE TITLE
Project Secrets value as number does not unmarshal as string

### ISSUE THREAD

**Issue by lukepatrick** [brigadecore/brigade#486]
If I set a Project secret as a number:
`--set secrets.temp="1"` or `--set secrets.temp=1`
these will store as a json number in Kubernetes.

Brigade will try to pull the Secret and unmarshal as a string, getting the error
`json: cannot unmarshal number into Go value of type string`

**Comment by technosophos** [comment]
I think that is probably an error in the project chart, which should send all values through the `quote` function. IIRC, we try to treat all secrets as `map[string]string` because they typically get supplied to the job as environment variables.

**Comment by lukepatrick** [comment]
go from
```go
  {{ if .Values.secrets }}
  secrets: '{{ .Values.secrets | toJson }}'
  {{- end }}
```
to something like
```go
  {{ if .Values.secrets }}
     {{ range $k, $v := .Values.secrets}}
     secrets.{{ $k }}: {{ $v | quote }}
     {{- end }}
  {{- end }}
```

**Comment by technosophos** [comment]
Oh... hmmm... that is an interesting one. I forgot that we allowed arbitrarily deeply nested secrets. I wonder if anyone is using them that way.

**Comment by lukepatrick** [comment]
I believe "arbitrarily deeply nested secrets" wouldn't work with `map[string]string`, we would get the same unmarshal error as before (a list or object "into Go value of type string"). 

We could to the chart solution above, make the chart consistent with the core code; or change code to allow `map[string]interface{}` for more complex secrets.

**Comment by technosophos** [comment]
Which Brigade component was giving that initial error? I'm trying to figure out how inconsistent we are with our handling of this.

**Comment by lukepatrick** [comment]
The path was installing a Project with the above set values and I would cause empty 404's from the API.
Specifically at these lines
https://github.com/Azure/brigade/blob/master/pkg/storage/kube/project.go#L74-L79

**Comment by lukepatrick** [comment]
note - same issue as #470

**Comment by successive-dev** [comment]
I have a bunch of secrets in my cluster, is there any way to know which brigade secret is broken.

**Comment by radu-matei** [comment]
@successive-dev - how were the secrets created?
The chart for secrets, or `brig`?
