### ISSUE TITLE
Support for Broadcast events

### ISSUE THREAD

**Issue by f0** [brigadecore/brigade#500]
it would be usefull if a special "broadcast" event was supported.
This could be used to trigger "child" Projects without the need to know them all.
So any Project can listen to the broadcast event and react if it's fired
e.g rebuild a container image when the base image changes

**Comment by technosophos** [comment]
The idea, if I understand it from the discussion we had on chat, is that one `brigade.js`/project could somehow send an event that another project could pick up.

**Comment by f0** [comment]
@technosophos yep you got it right

**Comment by krancour** [comment]
This is well covered by the [2.0 proposal](https://github.com/brigadecore/brigade/tree/master/2.0-PROPOSAL), which has been ratified and is now guiding the 2.0 development effort. It probably doesn't make sense to track this as a discrete issue anymore.
