### ISSUE TITLE
Don't delete storage PVC until all Jobs fail

### ISSUE THREAD

**Issue by TimJones** [brigadecore/brigade#516]
I have a build that uses Job storage for downloading vendor libraries.
Once downloaded into storage, units tests, and application builds can to ran, as well as (in the case of GitHub PRs) status updates.

If I need to run a `brig exec` to test this setup, storage PVC gets created OK, but as soon as any of the GitHub status-pending jobs fail, it deletes the PVC and continues to try and run the rest of the pipeline leaving me with pods forever in Pending trying to mount the non-existent PVC.

It would be helpful if the deletion of storage PVCs happens at the end of the pipeline run.

**Comment by technosophos** [comment]
That sounds like a bug in the error handler. Do you happen to have a bare-bones example JS file that I can use to test with?

**Comment by radu-matei** [comment]
Ping, @TimJones

**Comment by radu-matei** [comment]
We haven't encountered this error so far - but feel free to re-open if you happen to hit it again.

Thanks!
