### ISSUE TITLE
typescript hook definition and event-time compilation capabilities

### ISSUE THREAD

**Issue by tommysullivan** [brigadecore/brigade#527]
New Feature Request:
 As a brigade user
In order to reap the benefits of typescript in my hooks / pipelines definition files
I use brigade's typescript interfaces and event-time hook compilation capabilities

---

I use es6 imports to bring in interfaces needed to define various brigade event hook definitions, and then when events happen that otherwise depend on the plain javascript definition of the above, the brigade runtime typescript compiles my stuff.

Perhaps brigade exposes some type of lifecycle hook that could be used to do arbitrary preprocessing, which in turn could be used to typescript compile the hooks into the expected output location for brigade framework to then process.

**Comment by radu-matei** [comment]
I really like this approach, and I've been thinking about it for a while now.
However, I don't think this should come by default with the Brigade worker - mainly because it automatically needs the TypeScript compiler, which would increase the worker size, and not everyone will need this.

I think we would end up having a separate container image for the worker and maybe a conditional hook in `prestart.js` (if `tsc` is available...)?
What do you think?

**Comment by radu-matei** [comment]
So the TypeScript compile step would have to happen in `prestart.js` - but after we have copied `brigade.ts` in its final location, so any local dependencies from the VCS are found by the TypeScript compiler.

**Comment by tommysullivan** [comment]
cool, i still support this ticket but Im using some other tools now, gitlab ci and pulumi, i'll probably divest from this but good luck i think it would be really sweet.

**Comment by brandonkal** [comment]
Deno runtime support would be really slick to provide native TypeScript support especially as it can handle dependencies on its own.

**Comment by krancour** [comment]
Per the [2.0 proposal](https://github.com/brigadecore/brigade/tree/master/2.0-PROPOSAL#job-sidecars), 2.0 will drastically improve support for alternative workers, but introducing new (official) ones is deferred to a subsequent 2.x release. For now, I'm dropping the 2.0 label and adding a 2.1 label.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.

Note that v2 has _full_ TypeScript support.
