### ISSUE TITLE
Stopping a Running Build

### ISSUE THREAD

**Issue by philmay** [brigadecore/brigade#563]
We are using Brigade to implement custom data processing pipelines that respond to the arrival of new data-sets via a custom gateway that listens for "new data-set arrival" hooks. We're also creating a Web UI and command-line tool to interact with our pipelines and view status/progress/logs. With this setup, we'd like to be able to send requests to stop a Brigade build when pipeline progress seems to have stopped.

Brigade already handles build stop/cleanup when a job times out. What we'd like to be able to do is to tell Brigade to do build stop/cleanup without having to wait for a timeout to occur (basically a forced timeout). Are there ways to do this, and if so, is there a preferred approach? Also, more generally speaking, is there a way to pass new events into a running worker?

This capability is not a high priority for us, but it would be somewhat helpful. Do you know if anyone else has expressed interest in this type of thing?

Thanks!

**Comment by technosophos** [comment]
The preferred way is to kill the current job (or one of the current jobs), which will cause the worker to do its cleanup.

I would like to add a `brig build cancel` command, but haven't thought through the details of how this would work.

**Comment by philmay** [comment]
Thanks! 

We'll look at killing a job and how to build that into our Web UI and command-line tool, as that seems like a good way to go. Being able to cancel a build via `brig` would also be a nice feature to have eventually.

Is there any way to push new events into a running worker once your custom `brigade.js` has begun executing?

**Comment by radu-matei** [comment]
+1 for killing builds with `brig`.

**Comment by dgkanatsios** [comment]
Just did a small test via `brig run`, once you kill a job Pod, the worker will stay in a Pending state. Could `brig build cancel` kill job Pods as well as worker Pods and do a manual cleanup?

**Comment by radu-matei** [comment]
I think it should:

- kill the worker
- kill all job pods
- (delete PVCs?)

**Comment by dgkanatsios** [comment]
and probably leave a relevant status on the Build Secret, e.g. "Cancelled by user"

**Comment by dgkanatsios** [comment]
so, we currently have `brig build delete BUILD_ID --force` which will delete the Build even if it's running ([code](https://github.com/Azure/brigade/blob/master/pkg/storage/kube/build.go#L43)). This deletes relevant Pods and Secrets. Would this be enough?

If not, a way this could be implemented (haven't thought this through 100% though) is to do a kubectl exec (via client-go) and send a SIGTERM/SIGKILL to PID 1 process. Compared to `brig build delete`, this would have the advantage of no Pod/Secret deletion, so keeping the Pod logs (up to the SIGTERM time). However, user would need to do manual cleanup (Pod/Secret deletion) unless we update vacuum to do that.
WDYT?

**Comment by radu-matei** [comment]
I think this use case is covered by `brig build delete <id> --force`.
If not, feel free to reopen.

Thanks for suggesting this!

**Comment by danmx** [comment]
@radu-matei it would be good to cancel a job without deleting artefacts like e.g. logs

**Comment by krancour** [comment]
@danmx at last I had looked into it, there isn't a reliable way to stop a pod without deleting it.

This could possibly be solved by #1037, however, because deleting a build wouldn't take all the logs along with it.
