### ISSUE TITLE
shared storage & cache storage not working

### ISSUE THREAD

**Issue by Strandedpirate** [brigadecore/brigade#582]
I'm running on an ACS 1.8.1 cluster and when I enable either storage or cache for a Job the PVC gets stuck in pending status and the pod is eventually marked as unscheduled. I let the PVC's for both run for 5+ hours and it neither was ever provisioned. 

Is there a minimum k8s version the server needs to be running for these features or a specific addon that needs to be enabled?

```
λ kubectl get pv,pvc,sc --all-namespaces
NAMESPACE   NAME                                            STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
default     pvc/brigade-worker-01cm39fy71w78dmefzfefwg7fg   Pending                                       default        5h

NAME                               PROVISIONER                AGE
storageclasses/default (default)   kubernetes.io/azure-disk   15d
storageclasses/managed-premium     kubernetes.io/azure-disk   15d
storageclasses/managed-standard    kubernetes.io/azure-disk   15d
```

```
λ kubectl get pv,pvc,sc --all-namespaces
NAMESPACE   NAME                                                          STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
default     pvc/bitbucket-org-buildasign-designer-build-brigade-service   Pending                                       default
    18h

NAME                               PROVISIONER                AGE
storageclasses/default (default)   kubernetes.io/azure-disk   15d
storageclasses/managed-premium     kubernetes.io/azure-disk   15d
storageclasses/managed-standard    kubernetes.io/azure-disk   15d
```

```
λ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T10:09:24Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:16:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by vaibhavpals** [comment]
I think [this](https://github.com/Azure/brigade/issues/282) would help.
I'll recommend you try using azurefile

**Comment by technosophos** [comment]
AzureFile works well (though it can be a little slow -- like, 2-3 minutes). The NFS one is nice because it can create and destroy volumes so quickly, but I have lingering doubts about whether it's good in a production environment.

**Comment by technosophos** [comment]
Oh! That is good to know. Was it just generally unstable or where there particular problems?

**Comment by wstrange** [comment]
As I recall, If the nfs server restarted (for example, if we used preemptible nodes, or node maintenance happened) the server lost it's state, and the client nodes would experience stale NFS mounts. To recover at that point we had to redeploy everything.

the nfs-client provisioner seems much more reliable - but it relies on an external NFS servce. That costs $, and is a hassle for folks to set up.   

In our case we are trying to come up with a solution that we can recommend to our customers running on k8s. We want to minimize the deployment complexity as much as we can.  ReadWriteMany PVCs add to this complexity.

**Comment by technosophos** [comment]
Oh! That is good to know. We still haven't quite figured out how to accomplish the parallelism of jobs while doing ReadWriteOnce.

**Comment by krancour** [comment]
@FreakTheMighty 

> Things were running fine with storage enabled, but once I enabled caching for one of the jobs, it ran a few times then gets stuck waiting for a volume

The fact that the problem started right then strikes me as coincidental. Are you able to get logs from the PV controller?

My _hunch_ is that the VM used by Docker Desktop is running low on disk space.

**Comment by FreakTheMighty** [comment]
@krancour I think you're hunch is correct :/, thank you.

**Comment by krancour** [comment]
@FreakTheMighty happy to help. (I _miiiiight_ have run into this a time or two before. 😉)

Also, the original issue here is close to two years old and I don't see anything actionable here, so I'm going to close this.
