### ISSUE TITLE
[bug]: brig dashboard fails: panic: close of closed channel

### ISSUE THREAD

**Issue by thezaa** [brigadecore/brigade#648]
**brig dashboard kashti-xxxxxxxxxxx-xxxx -n brigade**

2018/10/02 22:00:29 Connecting to kashti at http://localhost:8081...
2018/10/02 22:00:30 Connected! When you are finished with this session, enter CTRL+C.
panic: close of closed channel

goroutine 1 [running]:
github.com/Azure/brigade/pkg/portforwarder.(*Tunnel).Close(0xc0003b3420)
        /root/go/src/github.com/Azure/brigade/pkg/portforwarder/portforwarder.go:78 +0x41
github.com/Azure/brigade/brig/cmd/brig/commands.glob..func4(0x1b16ee0, 0xc00026ef30, 0x1, 0x3, 0x120fd80, 0xc0003bb3a0)
        /root/go/src/github.com/Azure/brigade/brig/cmd/brig/commands/dashboard.go:62 +0x296
github.com/Azure/brigade/vendor/github.com/spf13/cobra.(*Command).execute(0x1b16ee0, 0xc00026ee10, 0x3, 0x3, 0x1b16ee0, 0xc00026ee10)
        /root/go/src/github.com/Azure/brigade/vendor/github.com/spf13/cobra/command.go:599 +0x3e8
github.com/Azure/brigade/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1b16440, 0xebd3ef, 0x1b16440, 0xc000143f58)
        /root/go/src/github.com/Azure/brigade/vendor/github.com/spf13/cobra/command.go:689 +0x2cc
github.com/Azure/brigade/vendor/github.com/spf13/cobra.(*Command).Execute(0x1b16440, 0xebd46e, 0xc000143f88)
        /root/go/src/github.com/Azure/brigade/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
        /root/go/src/github.com/Azure/brigade/brig/cmd/brig/main.go:11 +0x31
root@qa-jpxlhwdopbgaudui-master:~# ^C

**Comment by radu-matei** [comment]
Hey, @thezaa, thanks for reporting this!
Could you please paste here the entire command used to start the dashboard?

How did you deploy Kashti, and what namespace is used for Kashti?
Also, what version of Brigade + Kashti are you running?

Thanks!

**Comment by thezaa** [comment]
**helm install -n kashti ./charts/kashti --namespace brigade** to deploy kashti in namespce brigade
 
brig version
v0.9.0-63-g1257f32


**When i Run 
brig dashboard -n brigade (or) brig dashboard kashti(pod name) -n brigade**

Im getting tihs error:

 Connecting to kashti at http://localhost:8081...
2018/10/03 15:16:43 Connected! When you are finished with this session, enter CTRL+C.
panic: close of closed channel
goroutine 1 [running]:
github.com/Azure/brigade/pkg/portforwarder.(*Tunnel).Close(0xc0000f5420)
        /root/go/src/github.com/Azure/brigade/pkg/portforwarder/portforwarder.go:78 +0x41
github.com/Azure/brigade/brig/cmd/brig/commands.glob..func4(0x1b16ee0, 0xc00028a560, 0x0, 0x2, 0x120fd80, 0xc000451f20)
        /root/go/src/github.com/Azure/brigade/brig/cmd/brig/commands/dashboard.go:62 +0x296
github.com/Azure/brigade/vendor/github.com/spf13/cobra.(*Command).execute(0x1b16ee0, 0xc00028a2c0, 0x2, 0x2, 0x1b16ee0, 0xc00028a2c0)
        /root/go/src/github.com/Azure/brigade/vendor/github.com/spf13/cobra/command.go:599 +0x3e8
github.com/Azure/brigade/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1b16440, 0xebd3ef, 0x1b16440, 0xc000143f58)
        /root/go/src/github.com/Azure/brigade/vendor/github.com/spf13/cobra/command.go:689 +0x2cc
github.com/Azure/brigade/vendor/github.com/spf13/cobra.(*Command).Execute(0x1b16440, 0xebd46e, 0xc000143f88)
        /root/go/src/github.com/Azure/brigade/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
        /root/go/src/github.com/Azure/brigade/brig/cmd/brig/main.go:11 +0x31

**Comment by thezaa** [comment]
**it shows unknown namespace kashti**

i had deployed kashti in namespace=brigade

**Comment by bacongobbler** [comment]
From [looking](https://github.com/Azure/brigade/blob/231f3e3f8637b8eebc4d71d5d8955cca541c4e85/brig/cmd/brig/commands/app.go#L41) at [the code](https://github.com/Azure/brigade/blob/231f3e3f8637b8eebc4d71d5d8955cca541c4e85/brig/cmd/brig/commands/dashboard.go#L83), I think the command is `brig dashboard --namespace brigade`. Can you try that?

**Comment by radu-matei** [comment]
@bacongobbler - yeah, you are right... Actually I removed that flag a while back in #599

**Comment by thezaa** [comment]
**It is showing the same error**

**brig dashboard --namespace brigade**


  Connecting to kashti at http://localhost:8081...
2018/10/03 18:40:18 Connected! When you are finished with this session, enter CTRL+C.
panic: close of closed channel

goroutine 1 [running]:
github.com/Azure/brigade/pkg/portforwarder.(*Tunnel).Close(0xc000421420)
        /root/go/src/github.com/Azure/brigade/pkg/portforwarder/portforwarder.go:78 +0x41
github.com/Azure/brigade/brig/cmd/brig/commands.glob..func4(0x1b16ee0, 0xc00026c500, 0x0, 0x2, 0x120fd80, 0xc0003e3c60)
        /root/go/src/github.com/Azure/brigade/brig/cmd/brig/commands/dashboard.go:62 +0x296
github.com/Azure/brigade/vendor/github.com/spf13/cobra.(*Command).execute(0x1b16ee0, 0xc00026c2a0, 0x2, 0x2, 0x1b16ee0, 0xc00026c2a0)
        /root/go/src/github.com/Azure/brigade/vendor/github.com/spf13/cobra/command.go:599 +0x3e8
github.com/Azure/brigade/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1b16440, 0xebd3ef, 0x1b16440, 0xc00013df58)
        /root/go/src/github.com/Azure/brigade/vendor/github.com/spf13/cobra/command.go:689 +0x2cc
github.com/Azure/brigade/vendor/github.com/spf13/cobra.(*Command).Execute(0x1b16440, 0xebd46e, 0xc00013df88)
        /root/go/src/github.com/Azure/brigade/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
        /root/go/src/github.com/Azure/brigade/brig/cmd/brig/main.go:11 +0x31

**Comment by thezaa** [comment]
@radu-matei 

**I tried passing --open-dashboard=false**

it shows connected, but unable to access dashboard in the browser with http://localhost:8081.

**Comment by radu-matei** [comment]
Update on this issue:

I'm also seeing this issue on `master` when running from WSL (which is expected, and the fix for it is to update https://github.com/bacongobbler/browser to the lastest commit from master).

Opening a separate issue for this. 

@thezaa what OS were you using here?

**Comment by radu-matei** [comment]
Ping @thezaa - do you still see this issue?
Thanks!

**Comment by radu-matei** [comment]
I haven't experienced this since.
If you still encounter this, please, be sure to reopen.

Thanks!
