### ISSUE TITLE
Github Action Style Workflow Syntax

### ISSUE THREAD

**Issue by hharnisc** [brigadecore/brigade#666]
One limitation of Github actions is that they can only be used on private repositories (see https://developer.github.com/actions/creating-workflows/creating-a-new-workflow/#hello-world-workflow-example)

At Buffer we have a bunch of public repositories where actions would be very useful. 

I'd like to propose the idea of brigade accepting an HCL file (or similar) as the configuration for the brigade pipeline as a first step. Possibly creating some sort of editor as a longer term goal.

**Comment by hharnisc** [comment]
This still seems very useful, I only closed this because GithubActions said that the private repo was just a beta thing and didn't want to add noise here.

If there's anything I can do to help out here, let me know :raised_hands: I've got some ideas on how this could work.

**Comment by radu-matei** [comment]
Hey, @hharnisc !
First of all, I think we should keep in mind the discussion from #669 as well.

That being said, I am particularly excited about this feature, and I've been thinking a lot at the idea of using HCL to define Brigade pipelines - while declaring a job and its properties should be pretty straightforward, we also need to take into account the actual pipeline ordering.


It would be nice to discuss this further in one of our developer calls (details in the #brigade channel on the [Kubernetes Slack team](https://kubernetes.slack.com/)).
Would you be available to discussing this in detail, and work together on the implementation?

Thanks!

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
