### ISSUE TITLE
brigade.js installation to brigade 

### ISSUE THREAD

**Issue by arunramachandran15** [brigadecore/brigade#677]
I wrote a custom api  gateway to trigger event which sends slack message via brigade.js. All brigade.js does is to send a slack notification. Obviously now I dont need any github repo as I am just using Slack docker image.

Now where should I keep brigade.js to deploy into Brigade in cluster?
While creating Brigade-project what is the clone-url that I need to give?
What happens if I keep clone-url empty ? and how can i send brigade.js to cluster?

What will be brigade project folder structure?

https://azure.github.io/brigade/intro/tutorial04.html
Here it is mentioned to keep brigade.js file in the root of the repo.

How can I handle this scenario in my case where no application repo is available.

Thanks.

**Comment by arunramachandran15** [comment]
Project list:
```
$ brig project list
NAME            ID                                                              REPO
node-demo       brigade-878e1cf8935c772c02d513d2eb9a84ba5b8f6d0642409a0142e0b8  github.com/arunramachandran15/node-demo
```
Trying to install brigade.js from local folder:
```
$ brig run --file brigade.js --namespace default node-demo
Event created. Waiting for worker pod named "brigade-worker-01ctnj7ykpwt970raqv9y1vm3t".
Error: timeout waiting for build 01ctnj7ykpwt970raqv9y1vm3t to start
```
Project values.yaml:
```
project: "node-demo"
repository: "github.com/arunramachandran15/node-demo"
cloneURL: ""

allowPrivilegedJobs: "true"
kubernetes: {}
worker: {}
```
Logs for the last build:
```
$ brig build logs --last --jobs --
Error: could not find worker for build 01ctnj7ykpwt970raqv9y1vm3t: no pod exists with label build=01ctnj7ykpwt970raqv9y1vm3t,component=build,heritage=brigade
```
I created the above project using brig create. 

2. And brig list command doesn't show projects created using 
` helm install -n dev-node-demo brigade/brigade-project -f values.yaml`

But shows up in helm list :
`$ helm list
NAME                    REVISION        UPDATED                         STATUS          CHART                   APP VERSION     NAMESPACE
crabby-hog              1               Thu Oct 25 10:52:45 2018        DEPLOYED        brigade-0.9.0           v0.9.0          kube-system
dev-node-demo           1               Thu Oct 25 11:32:47 2018        DEPLOYED        brigade-project-0.18.0                  default
foolhardy-parrot        1               Wed Oct 24 13:58:11 2018        DEPLOYED        kashti-0.1.0                            default
mygateway               1               Tue Oct 23 18:14:09 2018        DEPLOYED        mygateway-0.1.0                         default
`
Could anybody kindly help me in figuring out what am missing here.

**Comment by vdice** [comment]
Hi @arunramachandran15 , indeed, it is true that if the `cloneURL` is empty but the `vcsSidecar` image is left as the default (`deis/git-sidecar:latest`), the worker pod will always fail on account of this sidecar container failing, as you've noted above.  (Perhaps there was logic intended at some time such that _if_ `cloneURL` was empty, this sidecar container itself or logic therein would handle and perhaps no-op, but apparently this isn't the case today.)

I believe the recommended solution today is to replace the `vcsSidecar` value with a custom image (that could just be a no-op) as described in https://github.com/Azure/brigade/issues/272#issuecomment-387129152 .  Try this out and let us know how it works.  Thanks!

**Comment by arunramachandran15** [comment]
Hi @vdice. Thankyou, Your comments helped me in understanding brigade vcs. As per your comments and reference issues I made 2 brigade projects. 

But still I am facing few issues with both approach. I have attached the logs from both github and cr gateway pods.

Brigade.js file : https://github.com/arunramachandran15/uuid-generator/blob/master/brigade.js


1. With Github
Error : 
`Creating Build failed: Get https://api.github.com/repos/arunramachandran15/uuid-generator/contents/?ref=9831c468d5ec97bcc71ea4ecf9beab99a4092a: dial tcp: i/o timeout
Error setting status to failure: Post https://api.github.com/repos/arunramachandran15/uuid-generator/statuses/9831c468d5ec97bcc71ea4ecf9beab99a4092a: dial tcp: i/o timeout`

Helm values : 
`project: "arunramachandran15/uuid-generator"
repository: "github.com/arunramachandran15/uuid-generator"
cloneURL: "https://github.com/arunramachandran15/uuid-generator.git"
sharedSecret: "MySuperSecret"
github:
  token: "e1893e4fa91bd58b162e80215e8a3558605983d" (token changed)` 

 
2. With Dockerhub

Here name of the secret is invalid ending with "-" character.
Error: 
`Fetching commit  for brigade-878e1cf8935c772c02d513d2eb9a84ba5b8f6d0642409a0142e0b8
[GIN] 2018/10/27 - 19:47:04 | 200 |   13.874336ms |       10.44.0.0 |  POST     /events/webhook/brigade-878e1cf8935c772c02d513d2eb9a84ba5b8f6d0642409a0142e0b8
failed dockerimagepush event: Secret "brigade-worker-01ctvh1m978g1ppsrwhqs1m8dr-" is invalid: metadata.name: Invalid value: "brigade-worker-01ctvh1m978g1ppsrwhqs1m8dr-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
`

Helm values:  
`project: "node-demo"
repository: "github.com/arunramachandran15/node-demo"
cloneURL: ""
secrets:
  SLACK_WEBHOOK: "FOR SLACK NOTIFICATION"
vcsSidecar: "arun15/node-demo:latest"
allowPrivilegedJobs: "true"
kubernetes: {}
worker: {}`

Please let me know if any more info required.
Thanks

**Comment by arunramachandran15** [comment]
> Hi @vdice. Thankyou, Your comments helped me in understanding brigade vcs. Brig run command worked with local file as namespace was causing issue. Now as per your comments and reference issues I made 2 brigade projects to get brigade file from vcs.
> 
> But still I am facing few issues with both the vcs approach. I have attached the logs from both github and cr gateway pods.
> 
> Brigade.js file : https://github.com/arunramachandran15/uuid-generator/blob/master/brigade.js
> 
> 1. With Github
>    Error :
>    `Creating Build failed: Get https://api.github.com/repos/arunramachandran15/uuid-generator/contents/?ref=9831c468d5ec97bcc71ea4ecf9beab99a4092a: dial tcp: i/o timeout Error setting status to failure: Post https://api.github.com/repos/arunramachandran15/uuid-generator/statuses/9831c468d5ec97bcc71ea4ecf9beab99a4092a: dial tcp: i/o timeout`
> 
> Helm values :
> `project: "arunramachandran15/uuid-generator" repository: "github.com/arunramachandran15/uuid-generator" cloneURL: "https://github.com/arunramachandran15/uuid-generator.git" sharedSecret: "MySuperSecret" github: token: "e1893e4fa91bd58b162e80215e8a3558605983d" (token changed)`
> 
> 1. With Dockerhub
> 
> Here name of the secret is invalid ending with "-" character.
> Error:
> `Fetching commit for brigade-878e1cf8935c772c02d513d2eb9a84ba5b8f6d0642409a0142e0b8 [GIN] 2018/10/27 - 19:47:04 | 200 | 13.874336ms | 10.44.0.0 | POST /events/webhook/brigade-878e1cf8935c772c02d513d2eb9a84ba5b8f6d0642409a0142e0b8 failed dockerimagepush event: Secret "brigade-worker-01ctvh1m978g1ppsrwhqs1m8dr-" is invalid: metadata.name: Invalid value: "brigade-worker-01ctvh1m978g1ppsrwhqs1m8dr-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') `
> 
> Helm values:
> `project: "node-demo" repository: "github.com/arunramachandran15/node-demo" cloneURL: "" secrets: SLACK_WEBHOOK: "FOR SLACK NOTIFICATION" vcsSidecar: "arun15/node-demo:latest" allowPrivilegedJobs: "true" kubernetes: {} worker: {}`
> 
> Please let me know if any more info required.
> Thanks

Accidently closed the issue.

**Comment by radu-matei** [comment]
Hey, @arunramachandran15!
Do you still have this issue? Feel free to reopen if so.

Thanks!
