### ISSUE TITLE
Request: do not automatically append build id from pod/job names

### ISSUE THREAD

**Issue by Strandedpirate** [brigadecore/brigade#680]
Requesting that the build id not be automatically appended to pod names because it's taking 26 chars of the 63 character limit.

I'm sure a lot of code is banking on the build id being a part of the pods name but it could be simply added as a label and referred to from there.

**Comment by technosophos** [comment]
I'll have to check on the uniqueness constraints, but we might be able to do this

**Comment by radu-matei** [comment]
Pod names must be unique in Kubernetes:

> For example, you can only have one Pod named “myapp-1234”. ([source](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/))

That being said, we could look into maybe leaving a truncated id in the pod name, and full build id as a label.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
