### ISSUE TITLE
Support for taint toleration

### ISSUE THREAD

**Issue by andrewrynhard** [brigadecore/brigade#685]
I would like to run dedicated nodes for brigade jobs, but there seems to be no way to tolerate a taint.

**Comment by technosophos** [comment]
For jobs, you can pin to nodes via the `Job.host` object.

https://github.com/Azure/brigade/blob/master/docs/topics/javascript.md#the-jobhost-class

If there are specific additional features you'd like to see added there, let me know. I'll see what we can do

**Comment by andrewrynhard** [comment]
> For jobs, you can pin to nodes via the `Job.host` object.
> 
> https://github.com/Azure/brigade/blob/master/docs/topics/javascript.md#the-jobhost-class
> 
> If there are specific additional features you'd like to see added there, let me know. I'll see what we can do

In my cluster, I have certain nodes that have been tainted with `dedicated=ci:NoSchedule`, to tolerate this a pod must have something like
```
  tolerations:
  - key: dedicated
    operator: Equal
    value: ci
    effect: NoSchedule
```
I would like to be able to set tolerations on the job's pod spec for this use case.

**Comment by stafot** [comment]
@technosophos The link you shared is now broken. [Correct link](https://github.com/brigadecore/brigade/blob/master/docs/content/topics/javascript.md#the-job-class) 
Feel free to update your comment and delete mine.

**Comment by krancour** [comment]
I updated his comment with the new link location.

Thanks @stafot !

**Comment by stafot** [comment]
Thanks @krancour!

**Comment by krancour** [comment]
This is well covered by the [2.0 proposal](https://github.com/brigadecore/brigade/tree/master/2.0-PROPOSAL), which has been ratified and is now guiding the 2.0 development effort. It probably doesn't make sense to track this as a discrete issue anymore.
