### ISSUE TITLE
Bug? with mount share and multiple consumer Jobs

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#692]
I've encountered the following issue when testing some brigade pipeline changes.

It looks like anytime a pipeline has multiple pods with `storage.enabled=true` consuming from the same shared mount, if one pod exits on an error, the second (and I'd theorize perhaps every other additional consumer) automatically fails as well with something along the lines of `mkdir: cannot create directory '/mnt/brigade/share/<shared assets>': Stale file handle`.

It seems this scenario is only hit when at least one pod exits with a legitimate, non-Brigade related error.  Therefore, arguably, the pipeline failing because of the additional mount failures is perhaps moot.  Indeed, when I fixed the particular error I had, the pipeline was back to normal.  

However, I think this potential issue still deserves a look.

**Comment by radu-matei** [comment]
related? #465

**Comment by vdice** [comment]
@radu-matei good call; it sounds like it is related/same issue.  Let's see if we can craft a minimal repro brigade.js to confirm...

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
