### ISSUE TITLE
disable shared storage?

### ISSUE THREAD

**Issue by vincentzhou2013** [brigadecore/brigade#706]
Is there a way to disable shared storage? we deployed brigade on a enterprise Openshift, which has PVC quota.  the project itself doesn't pull anything from git ( we used a custom sidecar just for a brigade.js) and like to know if there is a way to disable the PVC usage. Thanks.

**Comment by dgkanatsios** [comment]
Did you try setting
jobName.storage.enabled to false in your brigade.js file?

**Comment by radu-matei** [comment]
Ping @vincentzhou2013.

**Comment by radu-matei** [comment]
Closing, but feel free to reopen if you think this is an issue. 
Thanks!
