### ISSUE TITLE
Add Container Spec definition from Node K8s Client to Brigade.js

### ISSUE THREAD

**Issue by dgkanatsios** [brigadecore/brigade#735]
Currently, the way a Brigade user modifies the spec for the actual Job Pods is that they have to modify the Job class (well, its instance) described in Job.ts (thereafter called Brigade Job). There are some Kubernetes container spec properties like image, name, args, env, resource requests and limits etc. These values are assigned when we call the JobRunner contructor and then sent to K8s to create the actual Job pod (thereafter called K8s Job).

At the moment there are two open issues (#685,#361,#844) to extend this Job object in Job.ts in Brigadier. In order to do that, we would need to add a new field on Brigade Job on Brigadier and then use it on K8s Job on JobRunner constructor on the Worker. 
However, in due time, there will be new fields introduced in Kubernetes Pod definition, so, there will be a need to again extend Brigade Job. 

Instead, what we could do is (somehow, I'm not sure how we could optimally do it) package the Kubernetes Container Spec object definition (from K8s Node client) in brigade.js. For example, the Job class could have a PodSpec property of type "V1Container". This way
- a Brigade user could modify all needed container fields, without the need for us to code them
- if we regularly sync/pull the latest Node client definition, we are future proof 
- we could delete some existing code that just copies values from Brigade Job to K8s Job

Thoughts? cc @radu-matei @technosophos @vdice

**Comment by vdice** [comment]
Indeed, in general, I like this approach: Support all manner of custom needs via user-end  configuration/implementation as opposed to trying to support every scenario in code.  I'd say this warrants a code spike to see how the proposal would look.

**Comment by dgkanatsios** [comment]
I had another thought about that. Instead of packaging the Kubernetes Pod Spec definition (and creating another dependency), we could probably tackle this in another way. Make the Job object accept a map/dictionary of string values, which will be set by the Worker on the actual Pod. 

E.g. 
- "key1" is a field on the Pod
- "key2" is a field on a fictional "obj1" on the Pod
- "key3" is a field on the container
- "key4" is a field on a fictional "obj2" on the container 

`map[string]string := [{"key1":"value1","obj1.key2":"value2","key3":"container.value3","key4":"container.obj2.value4"}]`

The above would maybe need a semantic to determine what `container` (or other fields) do mean. However, it would allow the user to arbitrarily set any values on the Pod spec they wish.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
