### ISSUE TITLE
[CI]: proposal: separate check for linters, and add TypeScript linters

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#739]
I just spent a couple of minutes in the checks for a PR looking for the output of the linters. 

While this is by no means a priority (and maybe not even something we want to add), I would certainly appreciate a separate check for all linters (and also add some TypeScript linters - or have I missed them, maybe?).

We could also use the required/optional types of checks GitHub offers to allow merging if we really need, even if linters fail (not a fan of doing this, though).

Thoughts?
If we want to got this way, I volunteer to implement it 😅

**Comment by dgkanatsios** [comment]
as mentioned in #728, I agree 100% for usage of TS linters

**Comment by radu-matei** [comment]
This is a fairly easy to implement, let's give it another look.

**Comment by krancour** [comment]
I agree that wherever possible we should favor smaller, more discrete jobs. verifying vendored code, running linter, and running tests could be broken into separate jobs for both Go and JS.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
