### ISSUE TITLE
Examples and tutorials for common Brigade scenarios

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#748]
Add examples/explanations for the following:

  - [ ] ETL/Big Data
  - [ ] ML/AI
  - [ ] CI/CD
  - [ ] "Utility" cases

related: #747, #459 (temporary services with Brigade), #550 (GitHub bot)

**Comment by chzbrgr71** [comment]
If I were to create one of these, what is the proper folder in the docs?

**Comment by radu-matei** [comment]
I think you can create a new directory under `docs/examples` called maybe `tutorials`?

**Comment by radu-matei** [comment]
cc @kooba for a tutorial on creating preview environments for pull requests.

**Comment by kooba** [comment]
👍 @radu-matei I'm working on another tutorial for `nameko-grpc` at the moment. As soon as I'm done with that I'll jump on this tutorial.

**Comment by vdice** [comment]
Doc/tutorial updates are still ongoing; removing the v1.1 label.

**Comment by vdice** [comment]
Removing from 1.3; we can consider for a future milestone if/when PRs appear.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
