### ISSUE TITLE
Ability to run jobs in a seperate namespace

### ISSUE THREAD

**Issue by rmb938** [brigadecore/brigade#755]
I would like the ability to run jobs in a separate namespace, similar to the Gitlab CI Runnier https://docs.gitlab.com/runner/install/kubernetes.html

Add a `--job-namespace` flag on the controller which is passed to the worker via `BRIGADE_JOB_NAMESPACE` and the worker would spin up jobs in that namespace.

An example would be to have brigade deployed into a namespace called `brigade` and have the workers launch jobs in the namespace `brigade-jobs`.

I do this with my Gitlab CI runner deployments so jobs can be isolated away from the CI/CD control plane.

**Comment by radu-matei** [comment]
If we go ahead with this, some other changes would need to happen as well:

- you would need a new role binding for the Brigade controller role so it could create the worker pod in the `brigade-jobs` namespace
- the Brigade API role binding would also need read permission for the new namespace, thus another role binding
- the Brigade worker and vacuum would need the permission to create resources in their new namespace.

Did I miss anything here?
Thanks!

**Comment by rmb938** [comment]
Well if we follow the gitlab ci structure the worker pod would stay in the `brigade` namespace while the jobs it spins up would go into the `brigade-jobs` namespace.

**Comment by squillace** [comment]
if we do that, do it correctly: roles/bindings/perms and so on.

**Comment by krancour** [comment]
This is well covered by the [2.0 proposal](https://github.com/brigadecore/brigade/tree/master/2.0-PROPOSAL), which has been ratified and is now guiding the 2.0 development effort. It probably doesn't make sense to track this as a discrete issue anymore.
