### ISSUE TITLE
Document how we use Brigade to test Brigade

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#763]
I was going over the work @vdice has been doing in `brigade.js` for this project and it is really, really nice!

It would be great if we documented how we are using certain features (including, but not limited to):

- using the Brigade Checks API and the new gateway, and how we send notifications back to GitHub
- building and pushing container images (in-cluster and external builder)
- creating GitHub releases and pushing release artifacts
- send notifications to Slack (although this particular piece is in _every_  single Brigade example and demo...)

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
