### ISSUE TITLE
Feature request: brig run should directly accept the payload as flag

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#774]
This is useful when running from CI environments and the payload needs information about the current build:

```
$ brig run --json-payload "<my-json-formatted-payload>"
```
For example, I'd like to be able to do the following from a Makefile (most likely wrong quotes there, but along the lines of):

```
brig run --json-payload {"image": "node-demo:$(TAG)"}
```

**Comment by vdice** [comment]
@radu-matei I'm unclear how this suggested feature differs from the `  -p, --payload string   The path to a payload file` flag already provided on `brig run`?

**Comment by radu-matei** [comment]
The current `-p` flag points to a file path with the payload. It might be useful to be able to directly construct the payload inline, without writing it to a file.

**Comment by shubham1172** [comment]
Is it cool if I take this up? @radu-matei

**Comment by shubham1172** [comment]
Can I work on this? @radu-matei

**Comment by radu-matei** [comment]
Sure, feel free to tackle this, and let me know if I can help!
Thanks!
