### ISSUE TITLE
Controller leader election

### ISSUE THREAD

**Issue by rmb938** [brigadecore/brigade#775]
It would be useful to add leader election to the brigade controller. This will allow multiple controllers to be ran without stepping on each other as well as supporting HA.

This would also allow a rolling deployment of the brigade controller while jobs are in flight.

**Comment by radu-matei** [comment]
cc @adamreese, @technosophos

**Comment by technosophos** [comment]
I would like that feature, but would prefer to do it after 1.0

**Comment by dgkanatsios** [comment]
[This](https://github.com/kubernetes-sigs/controller-runtime/pull/118) that contains relevant implementation for controller-runtime might come in handy when we revisit that

**Comment by dgkanatsios** [comment]
Just a heads-up that I've started experimenting with this on a small project of mine that includes a custom controller. For reference, [here's](https://github.com/kubernetes/client-go/tree/master/tools/leaderelection) the `leaderelection` library on client-go, [here's](https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/example/main.go) the provided example and [here's](https://github.com/dgkanatsios/AksNodePublicIPController/blob/leader-election/main.go#L83) the implemented code on my project that tries to lock a ConfigMap (preferred approach) and start the controller.
Still testing this implementation, as soon as I feel confident with this approach I'll try to integrate it with Brigade. In the meantime, [feel free to take a look](https://github.com/dgkanatsios/AksNodePublicIPController/blob/leader-election/main.go#L83) and let me know of your thoughts.

**Comment by krancour** [comment]
Removing the 2.0 label as this issue is no long relevant to 2.0, at least not directly so.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
