### ISSUE TITLE
secretKeyRef not usable in v0.19 (`brigade-worker` and `brig` CLI incompatible)

### ISSUE THREAD

**Issue by anth0d** [brigadecore/brigade#778]
**pre-reqs** 
```
kubectl create secret generic test-secret --from-literal=test=HELLO
brig project create # just pick defaults
```

**the issue:** brig doesn't support specifying whether to allow `secretKeyRef`

**brigade.js**
```
const { events, Job } = require("brigadier");

events.on('exec', (e, proj) => {
  const name = `test-${Date.now()}`;
  j = new Job(name, 'ubuntu:latest', ['env | grep TEST']);
  j.streamLogs = true;
  j.env = {
    MY_TEST_SECRET: {
      secretKeyRef: {
        name: 'test-secret',
        key: 'test',
        optional: true
      },
      // TODO - (also if you use Typescript you can't really specify secretKeyRefs because the env var value type is `string | V1EnvVarSource` which is a bad type)
      // configMapKeyRef: new V1ConfigMapKeySelector,
      // fieldRef: new V1ObjectFieldSelector,
      // resourceFieldRef: new V1ResourceFieldSelector
    }
  };
  j.run().then(results => {
    console.dir(results);
    j.logs().then(console.dir);
  }).catch(err => console.error);
  console.log('done');
});

```

**Output**
```
brig run -f brigade.js deis/empty-testbed
Event created. Waiting for worker pod named "brigade-worker-01d1h826fy5exgrmc8m4gzra14".
Build: 01d1h826fy5exgrmc8m4gzra14, Worker: brigade-worker-01d1h826fy5exgrmc8m4gzra14
prestart: no dependencies file found
prestart: loading script from /etc/brigade/script
[brigade] brigade-worker version: 0.19.0
[brigade:k8s] Using secretKeyRef is not allowed in this project, not setting environment variable MY_TEST_SECRET
done
```

Output of `brig version`:
```
v0.19.0
```

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-10T11:44:36Z", GoVersion:"go1.11", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud Provider/Platform (AKS, GKE, Minikube etc.):
```
Minikube
```

**Comment by radu-matei** [comment]
Hi, and thanks for opening the issue!

The first question I have is what versions of the worker and controller are you using?

**Comment by radu-matei** [comment]
I believe that if you have at least the first version of `brig` where this was introduced, this should work.

Feel free to reopen if this is not the case.
Thanks!

**Comment by stafot** [comment]
Having the same problem/output with `brig v1.4.0` and `AWS EKS 1.16`

**Comment by krancour** [comment]
@stafot are you sure that is allowed at the project level? It has to explicitly be allowed at the project level so that some rando can't come by and submit a PR that changes your `brigade.js` to bind to your secrets and spit them out.

**Comment by stafot** [comment]
@krancour 
Thanks, yes sorted. Although I fixed by manually editing the k8s resource. Didn't find yet how to set it properly from the beginning.

**Comment by krancour** [comment]
@stafot glad to hear you're up and running again.

> Although I fixed by manually editing the k8s resource.

Ya.... people do that. You're not alone.

I assume you created the project using `brig project create`? A question about enabling this or not is buried under the "advanced" settings.

We're committed to greatly improving this UX in 2.0.

**Comment by stafot** [comment]
@krancour thanks for this info. Glad to hear about the ux improvement.

**Comment by ShahNewazKhan** [comment]
Hello, I created my `brigade project` using the `helm chart` how do I enable `secretKeyRef` for the project from the helm chart?

**Comment by vdice** [comment]
Hi @ShahNewazKhan , the [brigade-project chart](https://github.com/brigadecore/charts/tree/21eaaae55fd84006d941b6d3044997f0944758d4/charts/brigade-project) doesn't currently have support for creating generic Kubernetes secrets.  (Recall that a Brigade project is a Kubernetes secret itself -- and the chart is just a templated version of this secret.)

Would you be able to elaborate on your use case and I can try to advise?
