### ISSUE TITLE
Migrate to brigadecore GitHub org

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#789]
This issue tracks the migration of the Brigade project to a new GitHub org.

Projects from the Azure org:

- [x]  https://github.com/Azure/brigade
- [x] https://github.com/Azure/brigadier
- [x] https://github.com/Azure/kashti
- [x] https://github.com/Azure/brigade-charts
- [x] https://github.com/Azure/brigade-k8s-gateway

(As per #746, https://github.com/Azure/brigade-github-app will be part of the main Brigade repo).

Other projects migrated to the new org:

- [x] https://github.com/brigadecore/brigade-utils/

The list of [related projects](https://github.com/Azure/brigade/blob/master/README.md#related-projects) from the readme also contains lots of really useful projects - now it might be a good opportunity to move them to a central org for better discovery (this should be entirely up to the respective authors - cc @technosophos, @slok, @lukepatrick).

For any other projects that makes sense to live under the new org, feel free to comment below.

Other things we need on the new org:

- [x] a Brigade instance for CI - I think the least disruptive way would be to give access to the same instance for the new org (what do you think, @vdice?)
- [ ] mailing list for developers and users

Last edited: @radu-matei on 5/3/19

cc @vdice

**Comment by slok** [comment]
Good for me to move [brigadeterm](https://github.com/slok/brigadeterm) and [brigade-exporter](https://github.com/slok/brigade-exporter) to a more official and centralized org.

**Comment by radu-matei** [comment]
Update: started testing around with the `brigadecore` organization, initially moved https://github.com/brigadecore/brigade-utils/ and we are good to go with the new org.

As we start moving repos there, we will also going to need to set up a Brigade instance for CI - I'll update the original issue with this as well.

**Comment by lukepatrick** [comment]
I would be good moving brigade related projects to a central org.

**Comment by vdice** [comment]
@radu-matei the repos listed in the description have now moved to the [brigadecore](https://github.com/brigadecore/) and so I believe we are able to close this one out.

I left the mailing list item unchecked -- do we have those set up yet?

**Comment by radu-matei** [comment]
@vdice -- we have a maintainer mailing list, and I'll ask CNCF about a user mailing list this week. I think we can safely close this issue, thanks, everyone!
