### ISSUE TITLE
This recording has been archived

### ISSUE THREAD

**Issue by vanto** [brigadecore/brigade#799]
The asciicinema screen recording (linked from the README) is not available anymore.

**Comment by radu-matei** [comment]
Ah, thanks a lot for pointing it out!

**Comment by radu-matei** [comment]
We should create a new intro video / ASCII cinema / GIF that shows brig term, Kashti.

**Comment by vdice** [comment]
Removing from 1.3 to tidy up this forthcoming release, though of course a new intro video as mentioned by @radu-matei would be great!

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
