### ISSUE TITLE
Proposal: add ability to run jobs locally

### ISSUE THREAD

**Issue by bacongobbler** [brigadecore/brigade#8]
<a href="https://github.com/arschles"><img src="https://avatars1.githubusercontent.com/u/70865?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arschles](https://github.com/arschles)**
_2017-04-21 21:03:04_

----

Since each job has tasks that are run in sequence inside a container, it should be possible to run jobs locally, assuming the local machine has Docker installed. For example, the job excerpted from this repository's `acid.js` file:

```javascript
// Create a new job
job1 = new Job("acid-test");

// Since this is Go, we want a go runner.
job1.image = "technosophos/acid-go:latest";

// Set a few environment variables.
job1.env = {
    "DEST_PATH": localPath,
    "GOPATH": gopath
};

// Run three tasks in order.
job1.tasks = [
  "go get github.com/Masterminds/glide",
  "glide install",
  "make test-unit"
];
```

Roughly translates to this command:

```console
docker run --rm --name acid-test -e DEST_PATH=something -e GOPATH=somethingelse technosophos/acid-go:latest sh -c 'go get github.com/Masterminds/glide; glide install; make test-unit'
```

Is it possible to add a CLI that knows how to "drive" an `acid.js` file against a local Docker daemon, instead of Kubernetes?

This functionality would be very useful for a user to verify a CI run locally, and I could think of 2 "cons" to this approach:

1. If we want to add additional features later, and it needs to be server-side (inside Kubernetes), we might be painting ourselves into a corner by requiring support for on-laptop builds
2. We might be venturing into territory where we are building a new build system, not building a Kubernetes-native CI system

**Comment by bacongobbler** [comment]
**Comment by [jchauncey](https://github.com/jchauncey)**
_2017-04-22 01:05:08_

----

So I have experimented in the past with turning developer machines into build nodes for CI and it actually isn't that bad of an idea. It also allows people to pin a job on to their machine to watch what happens. 

<Ignore this comment while I am sure it would be a cool idea and I meant what I said it does not apply to this issue =p>

**Comment by bacongobbler** [comment]
**Comment by [arschles](https://github.com/arschles)**
_2017-04-22 14:33:26_

----

That's a cool idea, but this issue is specifically about providing a CLI to users so that they can simulate a CI build locally, again so they can see what would happen on a bona-fide CI run.

**Comment by bacongobbler** [comment]
**Comment by [jchauncey](https://github.com/jchauncey)**
_2017-04-22 17:18:44_

----

There seems to be two parts to the system.

1 - The server which is responsible for managing state and kicking of jobs.
2 - The runner which is responsible for the actual execution of the `Jobs` and `Tasks`.

If you built a `runner` image that could pick up an `acid.js` file from a volume mount it would allow for running a build locally since it could also use your local kubernetes context for creating the pods.

This would allow projects to have a make target that could run their acid job against a local running minikube or even their own cluster. This would be super useful for things like e2e testing where it may take a long time to run but you want to simulate the real environment. 

I would stay away from building a CLI specific to acid and instead just build docker/moby images that can be run independently of the system itself. This allows us to quickly iterate and provide new functionality without people having to worry about updating CLIs.

This would allow me to just do -

```
docker run -v .:/some/path quay.io/deis/acid-runner:v1.0.0
```

The main entry point to this image takes the local mounted src and scans for the acid.js file and run its doing everything it should.

You could then have the same image be able to clone a repo if you provided a few env vars:

```
docker run -e GITHUB_AUTH_TOKEN=sometoken quay.io/deis/acid-runner:v1.0.0
```

**Comment by bacongobbler** [comment]
**Comment by [technosophos](https://github.com/technosophos)**
_2017-07-04 00:15:58_

----

We took an initial look at this and here are the results of our looking:

1. Running directly against Docker is only straightforward in the easy case. As soon as more features are used, it requires adding an entire middleware layer to simulate Kubernetes-like behavior. BUT, we have not ruled it out.
2. Even if Docker doesn't work directly, it might be possible to launch from a local client directly to minikube, which would then support the full feature-set out of the box. A small CLI would make it relatively straightforward to do this against Minikube or any other vanilla Kubernetes installation.

Clearly, both alternatives would be MUCH better than what we do with CircleCI right now, which is repeatedly push new circle files and then shell into the container to debug.

**Comment by bacongobbler** [comment]
**Comment by [bacongobbler](https://github.com/bacongobbler)**
_2017-07-04 01:41:55_

----

> A small CLI

I think I have an idea for that certain CLI ;)

**Comment by radu-matei** [comment]
This is probably suited for something like https://github.com/lovethedrake (which also uses Brigade).
cc @krancour
