### ISSUE TITLE
Document using Brigade without a git repo

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#806]
If you look at the documentation, it might appear that you MUST have a git repo if you want to use Brigade. While the best practice has been to use a repo to store at least the `brigade.js` file, we should also show how to setup and use a project without ever using a git provider.

**Comment by dgkanatsios** [comment]
I think this scenario is a good match/aligned with a Generic Gateway tutorial, since one could "hit" the GW endpoint and activate a Build, without and VCS interaction whatsoever.
