### ISSUE TITLE
Admission Controller when creating projects manually

### ISSUE THREAD

**Issue by rmb938** [brigadecore/brigade#807]
When creating brigade projects manually (i.e creating the secret manually) via terraform, ect... it would be nice to have some sort of validation against the secret to make sure it's setup correctly. This probably could be done via an admission controller. https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

**Comment by radu-matei** [comment]
And I think we can re-use the logic from `brig project create` for it.

**Comment by dgkanatsios** [comment]
Writing an admission webhook can be quite tricky, maybe we could examine something like OpenPolicyAgent https://github.com/open-policy-agent/gatekeeper, maybe it can be customized to suit our purposes.

**Comment by rmb938** [comment]
@dgkanatsios How so? An admission controller is just an http server that accepts an input object and outputs true or false, with the client-go library it is very straight forward and can be about 200 lines of code. The only difficult part is generating certificates because they only can be https.

**Comment by dgkanatsios** [comment]
> @dgkanatsios The only difficult part is generating certificates because they only can be https.

Exactly this. I've written one [here](https://github.com/dgkanatsios/azuregameserversscalingkubernetes/blob/master/pkg/apiserver/webhookserver/run.go) and the most difficult task was to get the https working. I didn't even attempt to let the user generate them :) In any case, if we can find pre-made code for that, that would be lovely I think.

**Comment by rmb938** [comment]
Sure I see how that could be a difficult task for the user if they are not familiar with how to do it and how things are deployed.

This is somewhat of an advanced feature so I guess just having documentation about using gatekeeper and having a sample policy may be good enough? :man_shrugging:

**Comment by dgkanatsios** [comment]
probably... I haven't taken a deep look at the gatekeeper TBH, not sure if it does support our scenario. But it would be definitely be a good idea to validate those `non-brig-created` Projects.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.

fwiw, in v2 there's a JSON schema that's used to validate project definitions (which are not k8s resources, but rather resources belonging to Brigade's own API).
