### ISSUE TITLE
brig check command

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#815]
It would be really helpful to have a `brig check` command, similar to the [Linkerd Check](https://linkerd.io/2/reference/cli/check/) command, that makes sure you have access to the cluster, and that all components required for Brigade are running properly.

**Comment by dgkanatsios** [comment]
Nice one. From a design point of view, I suppose that this utility could check some (if not all) of:
- connection to the cluster
- existence of the Brigade API server deployment with >=1 running Replicas
- existence of the Brigade controller's deployment with >=1 running Replicas
- existence of the vacuum CronJob 
- check for RBAC rules (`kubectl auth can-i`)

Anything else?
