### ISSUE TITLE
If host.os is set to Windows, override bash script with a Windows alternative.

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#823]
Right now, regardless of the operating system of the job specification, the entrypoint of the container is a bash script -- meaning it cannot run Windows containers.

**Comment by krancour** [comment]
Removing the 2.0 label because other changes in 2.0 have rendered this moot.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
