### ISSUE TITLE
[docs]: setup redirect rules for *.md internal links

### ISSUE THREAD

**Issue by flynnduism** [brigadecore/brigade#840]
In transitioning from GitHub repo-hosted docs to a Hugo docs website, there are conflicts that can appear in how urls are structured. @dgkanatsios has tackled a bunch of this via #831   

Ideally it would be good to have urls that work in either format, so you can successfully browse through the markdown on GitHub.com as well as on docs.brigade.sh

Example of this can be [seen here](https://github.com/Azure/brigade/blob/master/docs/content/topics/_index.md)

---

Ideally it would be great to configure the site (whether via Hugo params or Netlify build config) to do some sort of redirection for specific internal urls.

**Comment by flynnduism** [comment]
The netlify.toml can handle this by adding extra config. See [helm example](https://github.com/helm/helm-www/blob/master/netlify.toml#L11L19) here.

* [Redirect Rules for All; How to configure redirects for your static site](https://www.netlify.com/blog/2019/01/16/redirect-rules-for-all-how-to-configure-redirects-for-your-static-site/#structured-configuration-with-netlify-toml)
* [Netlify Docs: Redirects ](https://www.netlify.com/docs/redirects/)

**Comment by joeizy** [comment]
Not sure if you are referring to the same issue or I should create a new one but there are several links throughout the docs site https://docs.brigade.sh/ which result in a `Not Found` page. One example is the links to the individual gateway doc pages (`Container Registry Gateway`, `GitHub Gateway`, and `Generic Gateway`) from the [Gateways Topic Page](https://docs.brigade.sh/topics/gateways/). 

The links work correctly when browsing from the [GitHub Repo](https://github.com/brigadecore/brigade/blob/master/docs/content/topics/gateways.md)

**Comment by flynnduism** [comment]
That's correct @joeizy - there's a mismatch in some urls. Next item on my list to work on!

**Comment by dgkanatsios** [comment]
some images towards the bottom on this page do not load as well: https://docs.brigade.sh/topics/design/
