### ISSUE TITLE
Allow setting AllowedProcMountTypes to unmask

### ISSUE THREAD

**Issue by floriankoch** [brigadecore/brigade#844]
To allow unprivileged builds e.g with img or buildah, unmasked acces to /proc is needed
in kubernetes 1.13 is a new setting for this 
AllowedProcMountTypes

it should be possible to ativate this via an option  similar to enable.docker
e.g enable.unmaskedproc

**Comment by dgkanatsios** [comment]
Not sure if I grok this correctly, what disallows you to create a [Pod Security Policy](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#example) with the required [AllowedProcMountTypes](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#allowedprocmounttypes)?

**Comment by f0** [comment]
@dgkanatsios   afaik it needs to be set in the worker pod spec  or not?

**Comment by floriankoch** [comment]
@dgkanatsios afaik it needs to be set in the worker pod spec or not?
So wee ned a psp and set this in the pod spec , the same as with privileged, you need a psp and a setting in the pod spec

**Comment by dgkanatsios** [comment]
To be honest I haven't checked this feature before. From a quick search I can't find if it needs to be set in the Pod Spec, all the [code references](https://github.com/kubernetes/kubernetes/search?q=allowedprocmounttypes&unscoped_q=allowedprocmounttypes) are related to Pod Security Policy.
Are you aware whether this needs to be set in the Pod Spec?

**Comment by floriankoch** [comment]
@dgkanatsios   its specified in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#securitycontext-v1-core  and its in the container spec - not the pod spec as i thought

**Comment by dgkanatsios** [comment]
Thanks, so we need to extend the Job object on [Brigadier](https://github.com/Azure/brigadier) and modify the Worker here to support this. This is related to #735.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
