### ISSUE TITLE
Publish to registry(ies?) that supply desired telemetry

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#856]
Brigade currently publishes its images to the [brigadecore](https://hub.docker.com/u/brigadecore) DockerHub org.  All Helm charts and documentation reference these images for pulling down.

However, we may require telemetry not provided by this registry and so may wish to publish to another registry that can provide this.  As a background on this request, see https://github.com/brigadecore/brigade/pull/849.

Let's add AC on what telemetry this project would like to see and then list some potential candidates that can fulfill these requirements.

**Comment by radu-matei** [comment]
cc @squillace

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
