### ISSUE TITLE
[docs] custom sort order of menu

### ISSUE THREAD

**Issue by flynnduism** [brigadecore/brigade#859]
As @dgkanatsios pointed out in #851 - the docs site menu is a pain to re-order. It auto generates **alphabetically** based on the markdown contents of each folder.

![Screen Shot 2019-03-28 at 11 47 17 AM](https://user-images.githubusercontent.com/686194/55184405-472e6580-514f-11e9-958b-2fad2cc7cb9f.png)

---

Ways to improve it:

1. hard code a custom menu into the site `config.toml`, which ignores titles, weight, etc
2. add a custom `weight` value to the hugo front matter [info here](https://gohugo.io/templates/lists/#default-weight-date-linktitle-filepath)
3. prefix filenames with a number, `001-` `002-` etc

I'd vote for 1. because it means a single file controls the menu, and you don't have to go about re-indexing every markdown files when you want to re-order the menu links.

**Comment by dgkanatsios** [comment]
+1 for `config.toml`, seems like the most elegant solution. Order in [Getting Started](https://docs.brigade.sh/intro/) is good now (even with `A Brigade Quickstart` whereas order in the [topics](https://docs.brigade.sh/topics/) would definitely need some love.
