### ISSUE TITLE
Enable FOSSA for license scanning

### ISSUE THREAD

**Issue by caniszczyk** [brigadecore/brigade#861]
https://fossa.com

CNCF has a deal with FOSSA, just enable it for your repo and let me know when it's done.

**Comment by radu-matei** [comment]
Enabled - see https://app.fossa.com/projects/git%2Bgithub.com%2Fbrigadecore%2Fbrigade/refs/branch/master/0f46d85fed13d699e332efe5acfc2a06c76f9cab/preview

**Comment by radu-matei** [comment]
Also see https://github.com/brigadecore/brigade/pull/874

**Comment by krancour** [comment]
Seems this was completed and ought to have been closed.
