### ISSUE TITLE
Adopt CII Best Practices Badge

### ISSUE THREAD

**Issue by caniszczyk** [brigadecore/brigade#862]
Get a silver badge: https://bestpractices.coreinfrastructure.org/en

**Comment by radu-matei** [comment]
Opened #873 to address this.

**Comment by dgkanatsios** [comment]
Close?

**Comment by vdice** [comment]
To echo @dgkanatsios , this issue looks like it can be closed, correct @radu-matei ?

**Comment by radu-matei** [comment]
Not yet, we should get a Silver badge, and we're currently in progress.
We should leave this open until we actually have a Silver badge.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
