### ISSUE TITLE
Suggested way for setting max parallel build

### ISSUE THREAD

**Issue by ysaakpr** [brigadecore/brigade#866]
Found that, Brigade is one of very easy to use CI/CD tool, because of the language selection and simplicity. 

In my project, I want to ensure that for some projects, no parallel execution allowed, mostly the deployment process, and in case there are multiple builds triggered for a project, I want only one at a time to process, Are there any suggested way to do the same.

So I am looking for the following features,
1. Setting max number of concurrency for a project
2. Ability to skip build waiting in the queue, and take the recent build only
Eg: build#1 is in progress, max concurrency is set 1, and now build#2,build#3,build#4 triggered, but they all are waiting in the queue for build#1 to finish, but once build#1 is over, I want the build#4 to start, and build#2 and build#3 should just get ignored, otherwise, OR Ability to update the last unprocessed build by any incoming build till it starts processing. Need to check the impact on multi-branch pipelines

Very interested to contribute, in case someone can approve these features and feasibility and viability of these.

**Comment by dgkanatsios** [comment]
Related discussion on #172

**Comment by krancour** [comment]
This is well covered by the [2.0 proposal](https://github.com/brigadecore/brigade/tree/master/2.0-PROPOSAL), which has been ratified and is now guiding the 2.0 development effort. It probably doesn't make sense to track this as a discrete issue anymore.
