### ISSUE TITLE
Race condition when installing brigade.json dependencies

### ISSUE THREAD

**Issue by chris-chambers** [brigadecore/brigade#867]
Output of `brig version`: `v1.0.0`

Output of `kubectl version`:
```
Client Version: v1.8.15
Server Version: v1.8.15-1+9f66f5c998b397
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): `AWS, custom`

---

When installing dependencies from `brigade.json`, the `addYarn` function returns a promise, but `addDeps` calls `addYarn` in a loop and does not wait on these promises to resolve.  This leads to multiple racing `yarn` processes that clobber each others' efforts.

To reproduce this, create a brigade project with a `brigade.json` that has multiple dependencies.

```json
{
  "dependencies": {
    "is-thirteen": "2.0.0",
    "moment": "2.24.0",
    "ramda": "0.26.1"
  }
}
```

Then, in `brigade.js`, try to `require` each:

```javascript
require('is-thirteen');
require('moment');
require('ramda');
```

Since it's a race condition, it's not always possible to observe, but in my tests it happens frequently.  It's also possible to connect to the running worker node and see that some modules are not installed into `node_modules`.

---

https://github.com/brigadecore/brigade/blob/ae56a2ab4bc93e663ab16a0e2034256ec3916647/brigade-worker/prestart.js#L53-L72

The simplest fix for this would be to use `child_process.execSync` rather than using `child-process-promise`, here:

https://github.com/brigadecore/brigade/blob/ae56a2ab4bc93e663ab16a0e2034256ec3916647/brigade-worker/prestart.js#L67

**Comment by chris-chambers** [comment]
Oh, it would also be possible to invoke `yarn` just once with all the dependencies to install.  This would make installing faster, but might reduce the quality of error messages.

**Comment by mumoshu** [comment]
@chris-chambers Thanks for reporting, and good catch!

I think it's fine to invoke `yarn` just once with all the deps. It will still produce an useful error message like the below on invalid dep, for example:

```console
yarn add moment is-thirteen invalidnpmmodule1
yarn add v1.15.2
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/invalidnpmmodule1: Not found".
```

**Comment by radu-matei** [comment]
Yes, nice catch -- and a single `yarn install` is acceptable, with the error above.

**Comment by radu-matei** [comment]
Thanks again for reporting AND fixing this!
