### ISSUE TITLE
Module resolution in local dependencies is counter-intuitive

### ISSUE THREAD

**Issue by chris-chambers** [brigadecore/brigade#868]
Inside [local dependencies](https://docs.brigade.sh/topics/dependencies/#using-local-dependencies-from-the-project-repository), `require` behaves counter-intuitively.

There are two problems:

### Brigadier Aliases
In `prestart.js`, `require` is replaced by a custom function that allows several aliases of `brigadier` to be resolved.  But, this aliasing is not available in any required local dependencies.

### Module Resolution in Local Deps
In all local dependencies, `require` sees `modules.path` as:
```javascript
[ '/vcs/node_modules', '/node_modules' ]
```

But, `yarn` installs dependencies into `/home/src/node_modules`.  The module search path from within `brigade.js` is correct, since it is copied-and-modified into `/home/src/dist`.  But local dependencies are left in-place in `/vcs/`, so they aren't able to resolve modules in `/home/src/node_modules`.

---

I'm working around both these issues using the `module-alias` module, and configuring it like:

```javascript
const modAlias = require('module-alias');

// Add the search paths for the current module (brigade.js) so they are
// available to all modules, everywhere.
module.paths.forEach(modAlias.addPath);

// Globally perform the same brigade aliasing that prestart.js does.
modAlias.addAlias('brigade', __dirname + '/brigadier.js');
modAlias.addAlias('brigadier', __dirname + '/brigadier.js');
modAlias.addAlias('@brigadecore/brigadier', __dirname + '/brigadier.js');

// Enable module-alias
modAlias();
```

The semantics of this may not be perfect, but I think something like this is pretty reasonable, given the desire to leave local dependencies in `/vcs`.  In fact, I think with a change like this, `brigade.js` could also be left in place, rather than being copied and modified.

**Comment by chris-chambers** [comment]
To repro the first:

**brigade.js**
```javascript
require('./brigade-local.js');
```

**brigade-local.js**
```javascript
require('@brigadecore/brigadier'); // will throw
```

---

And the second:

**brigade.json**
```javascript
{
  "dependencies": {
    "is-thirteen": "2.0.0"
  }
}
```

**brigade.js**
```javascript
require('./brigade-local.js');
```

**brigade-local.js**
```javascript
require('is-thirteen'); // will throw
```

**Comment by radu-matei** [comment]
Oh, thanks for catching this!

I think I like the proposed solution here -- I'm going to research a bit about how `module-alias` works, and other implications -- and we'll most likely discuss this over the dev standup which is Tuesdays, 9:30 AM PST (you're more than welcome to join).

I'll update the issue after I have a better understanding of how it would actually work -- also, let me know if you want to work on this, I'd be more than happy to pair a bit and walk you through how parts of the Brigade worker work together).

Thanks!

**Comment by chris-chambers** [comment]
I've been looking through `module-alias` for any potential landmines, but it looks like they cover the cases I can think of correctly (transitive dependencies could be weird, but they seem to limit the aliasing to "top-level modules were not installed", which means nothing inside `node_modules` would see the extra paths).

How would I join your standup?  I may have time to drop by tomorrow.  In the meantime, I'll play around with `prestart.js` and see if I can cleanly integrate these ideas.  If I get anywhere with it, I'll link to the patch here.

**Comment by radu-matei** [comment]
Ok, that sounds great!

Brigade Developer Standup - Tuesdays, 9:30 AM PST - https://zoom.us/j/280806496

Also, if you’re on the Kubernetes Slack, the #brigade channel.
