### ISSUE TITLE
Fix failing CI badge

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#877]

**Comment by dgkanatsios** [comment]
I see "Pass" right now, or I'm missing something?

https://camo.githubusercontent.com/59bb282978dee2a5dc5064a5f3e5bba569404bd5/687474703a2f2f6261646765732e746563686e6f736f70686f732e6d652f76312f6769746875622f6275696c642f417a7572652f627269676164652f62616467652e7376673f6272616e63683d6d6173746572

**Comment by radu-matei** [comment]
There is another badge whose original content is no longer available.
This means we no longer have a build badge in the readme.

@vdice - do you know how we had the badge set up?

**Comment by vdice** [comment]
@radu-matei I believe we were using an older domain that @technosophos created a while back but that may not be maintained any longer.  I'll assign this to myself and work on creating a new domain and new app release of https://github.com/technosophos/gh-build-badge for use by this and perhaps other brigadecore projects to display build statuses, as needed.
