### ISSUE TITLE
Use Go modules

### ISSUE THREAD

**Issue by dgkanatsios** [brigadecore/brigade#882]
Now that Go module support has been merged into the upstream Kubernetes ([1](https://github.com/kubernetes/kubernetes/pull/74877), [2](https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/2019-03-19-go-modules.md)), maybe we could discuss how to manage Brigade's vendor folder with Go modules.

**Comment by radu-matei** [comment]
I believe this was added in #1075
