### ISSUE TITLE
document worker image requirements better

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#886]
This section covers custom worker images: https://docs.brigade.sh/topics/workers/

But it also seems to make an assumption that customizing a worker image is only accomplished by extending an existing image and adding in additional JS libraries and really only covers this scenario.

I've been creating a new worker from scratch (as part of an experiment to integrate with a new pipeline model) and it's been difficult for me to understand the expected inputs, outputs, and behaviors. If these expectations were documented somewhere, we open the door for a greater variety of custom workers that can bring their own unique innovations to the table.

**Comment by krancour** [comment]
@radu-matei can you assign this issue to me, please?

**Comment by krancour** [comment]
Starting a short list of things as I uncover them. I'll circle back and document later. Just don't want to lose these:

1. Document the environment variables that the brigade controller will inject into the worker. These are an implicit interface between controller and worker.
1. Document how custom workers should name and label any pods (and other things?) that it creates to ensure other Brigade and Kashti processes interact with them as expected. For instance, a pod needs to be labeled a certain way to count as a "job" in the eyes of the vacuum process, Kashti, etc.

Will add to this list as I uncover things.

**Comment by radu-matei** [comment]
@krancour - I added this issue to the 1.2 milestone - feel free to remove it if you think it won't be done in time, or is not in scope.

**Comment by radu-matei** [comment]
Closed in #968
