### ISSUE TITLE
proposal: project level event filters

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#890]
I see a lot of builds running that ultimately do nothing because the brigade.js they execute doesn't respond to any events. This can get _really_ noisy.

As a for instance, suppose that I am using Brigade for CI and building on checksuite:* events. Builds will still be triggered for PR open, assign, synchronize, close, etc. This leads to a massive accumulation of builds that didn't do anything which isn't good for the signal:noise ratio.

If the option existed to whitelist (or blacklist?) events at the project level, this would cut down on the noise.

**Comment by dgkanatsios** [comment]
There is the `vacuum` utility (details [here](https://docs.brigade.sh/intro/quickstart/) towards the bottom) that has a duty to cleanup completed Jobs (after they happen, though), so I do get your point.

Can't you configure your VCS to not send these `checksuite:*` events?

**Comment by krancour** [comment]
The specific problem here is that I want the GH gateway to receive GH events (such as prs) so that it can forward checksuite requests and then emit those to brigade-- since those are the events I am really interested in. But the GH will still emit the pull request events that I am uninterested in. If I unsubscribed to either prs or check suite requests, the gateway wouldn't get what it needs.

**Comment by krancour** [comment]
I will prototype something to see what this looks like.

**Comment by radu-matei** [comment]
I seem to recall that we discussed this during last week's meeting - a project-level property that would contain events to respond to / ignore should also maintain backwards compatibility.

**Comment by radu-matei** [comment]
related - https://github.com/brigadecore/brigade-github-app/issues/37

**Comment by krancour** [comment]
Most of the noise was coming from the gthub gateway and this has been addressed by that project (see https://github.com/brigadecore/brigade-github-app/pull/74), so I'm going to close this.
