### ISSUE TITLE
Question: Event name clashes?

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#891]
Is it potentially problematic that two gateways could emit different events by the same name?

I am imagining, for instance, the Github gateway and a hypothetical Bitbucket gateway _both_ emitting events like `push` and `pull_request` (among others). Given that the event payloads are likely to be different from one another, it should not be taken for granted that a handler that can respond to a given event emitted by one gateway could successfully respond to an event by the same name emitted by the other gateway.

Should events, perhaps, be qualified by who or what emitted them?

**Comment by radu-matei** [comment]
Since events are triggered for a specific project, this might be a smaller issue - that being said, it could happen.
