### ISSUE TITLE
Cache PVC using repository not project name which often (for us) exceeds 63 char limit

### ISSUE THREAD

**Issue by LittleColin** [brigadecore/brigade#895]
When setting myJob.cache.enabled = true, the PVC created uses the project's _repository_ not just the project name. This is probably not too much of an issue when using github.com as it's relatively short, but we have custom git instances that have much longer names. This combined with the org and the repo name easily exceeds the allowed PVC name of 63 characters making the cache unusable for us.

Looking at the code, it reads as though the project name not the repository name was intended:

https://github.com/brigadecore/brigade/blob/8445f8a9a6bf3d89725407b9e8537066728873cc/brigade-worker/src/k8s.ts#L463

But as can be seen in [this ](https://github.com/brigadecore/brigade/issues/224) disrelated issue raised by @technosophos, you can see it is using the full repository DNS name: 

**github-com-Azure-kashti-prod**

Whether this was intended or not, is it possible to change it to just use the project name and/or allow it to be overridden in the project settings?

FWIW We are using brigade 0.21.0 (but latest code for 1.0.0 looks the same).

**Comment by radu-matei** [comment]
I haven't had a chance to properly look at how the project name propagates, and need to have a closer look, but I in most cases the project name itself contains the repo:


https://github.com/brigadecore/brigade/blob/master/brig/cmd/brig/commands/project_create.go#L58

What happens if you explicitly omit the repo from the project name (remember to set the clone URL correctly)?

That being said, I don't see any downsides in being able to configure the cache name.

**Comment by LittleColin** [comment]
Thanks for the reply. Just to be clear I'm not including the DNS of the SCM in the project name. Based on the example in the docs [tutorial 3](https://docs.brigade.sh/intro/tutorial03/) there are three properties:

$ brig project create
? **Project Name** bacongobbler/uuid-generator
? **Full repository name** github.com/bacongobbler/uuid-generator
? **Clone URL** (https://github.com/your/repo.git) https://github.com/bacongobbler/uuid-generator.git

The cache PVC is using the Full repository name (i.e. including github.com) with special chars replaced with hyphen so in this case the PVC would be:
**github-com-bacongobbler-uuid-generator-jobname**

Whereas I believe it should/could just be:
**bacongobbler-uuid-generator-jobname**

i.e. using the project name without the DNS of the SCM - that would give us a fighting chance of keeping within 63 chars.

I can try and set full repository name to just the project name if you think it might work - I wasn't sure why there was both a Full repository name in addition to a Clone URL. I'll let you know how I get on.

**Comment by LittleColin** [comment]
@radu-matei I can confirm that changing "Full repository name" to match the Project Name worked for us. Therefore (based on example), the values are:

- Project Name bacongobbler/uuid-generator
- Full repository name bacongobbler/uuid-generator
- Clone URL (https://github.com/your/repo.git) https://github.com/bacongobbler/uuid-generator.git

I guess the issue could be closed but perhaps there's a documentation update needed? Or perhaps clarity on why we need both a Full repository name and Project Name if they can be the same?

**Comment by radu-matei** [comment]
Glad to hear you have something working - that being said, I think we should leave this open until we actually propagate the ability to set the name.

(I'd be glad to help you get started if you'd like to contribute it)
