### ISSUE TITLE
"VCS sidecar" is a misnomer

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#899]
The thing currently referenced both in documentation and code as the "VCS sidecar" isn't properly a sidecar, but rather an init container.

I'm not trying to be overly pedantic by raising this; rather there is some part of me that was thrown off by this misnomer when I was trying to learn Brigade and I cannot help but wonder wether it may have the same effect for others.

If there were a consensus that this doesn't matter or that no one else cares, I'd be happy to close this.

**Comment by krancour** [comment]
When discussed during the weekly meeting, it was agreed that there are some places, such as in Helm charts, where we cannot correct this misnomer without incurring a breaking change.

The agreed upon solution is that we will acknowledge the misnomer in the documentation and call out the fact that what is colloquially known as the "VCS sidecare" is _actually_ an init container.

**Comment by krancour** [comment]
@radu-matei assign to me, please?

**Comment by radu-matei** [comment]
Since this will be a documentation fix, at least for now, and since it doesn't necessarily require a fix to be merged in time for the 1.1 release, do we want to defer this after 1.1?

**Comment by krancour** [comment]
Defer.

**Comment by adinunzio84** [comment]
Could you avoid breaking changes by allowing either (or both) to be set, and if the older one is set (even if the newer one is also set), it would default to the old behavior? Basically, like an alias

**Comment by krancour** [comment]
@adinuzio84 that seems like an unwarranted level of complication to correct a misnomer. I'm harboring some small degree of doubt that we can't just change this without incurring a breaking change. I'll investigate. But as noted above, in the worst case, this will degrade to a doc-only change.

**Comment by krancour** [comment]
Given that I think we only intended to correct this in 2.0 and 2.0 is a fresh start, there's nothing _to_ correct. I'm going to close this.
