### ISSUE TITLE
Intended timeout behavior?

### ISSUE THREAD

**Issue by gfrankel1997** [brigadecore/brigade#902]
What is the intended behavior when a Build times out? Brigade does throw an error which can be caught, but the Job continues to run.

Actual Behavior: Brigade Job continues to run after timeout
Expected Behavior: Brigade Job is stopped

Output of `brig version`:
```v1.0.0-23-g1b849be```

Output of `kubectl version`:
```Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}```
```Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
AKS

**Comment by radu-matei** [comment]
I've been giving this some thought over the past couple of days, and I think we should at least expose an option on the job object whether the worker should kill it if timeout is reached.

There might be cases where you want the job to finish (release resources, for example), but I think a good default would be to terminate the job pod.

What do you think about adding a flag for this?

**Comment by gfrankel1997** [comment]
@radu-matei Logically (and in most other systems) when something times out, it terminates. That's what I expected the default to be, but I definitely see the point in having the option. I like the idea of adding a flag for this.

**Comment by radu-matei** [comment]
cc @mumoshu - WDYT?

**Comment by mumoshu** [comment]
@radu-matei I think we can consider this as a bug fix and I agree that it should kill the job pod on timeout by default.

Implementation-wise, adding a flag would be nice, yes.

**Comment by radu-matei** [comment]
I think we should add a flag for this either way - what I'm struggling with is deciding whether we should enable it by default or not - if we consider it is a bug, then we could enable it by default, but we would break behaviour. If we don't, we just add the flag, but disable this by default.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
