### ISSUE TITLE
Brigade should log thrown error message

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#913]
Consider the following example brigade.js file:

```
const { events } = require("brigadier")

events.on("exec", function() {
  throw new Error("This should be logged when failing the event handler.")
})
```

When this file is used to run `brig run <test project>`, although the pipeline fails as intended, the error message isn't logged:

```
 $ brig run test -f test-project/throw-error.js
Event created. Waiting for worker pod named "brigade-worker-01dast93c17zp0h3ftvqh6n9q1".
Build: 01dast93c17zp0h3ftvqh6n9q1, Worker: brigade-worker-01dast93c17zp0h3ftvqh6n9q1
prestart: no dependencies file found
[brigade] brigade-worker version: 1.0.0
error Command failed with exit code 1.
build failed. (Build ID: 01dast93c17zp0h3ftvqh6n9q1)
```

I'm wondering if we can fix this such that the error message is logged by the worker.

**Comment by technosophos** [comment]
I think that `app.ts` has a `process.on("error"` and a `process.on("uncaughtRejection"`. Maybe there is some other event like `uncaughtException` that we need to catch or something.

**Comment by vdice** [comment]
@radu-matei did you mention you were working on the fix for this?  I'll assign you to the ticket; feel free to unassign if incorrect.

**Comment by radu-matei** [comment]
Yes, I have a local fix that I'm going to PR shortly.
