### ISSUE TITLE
Releases should be signed

### ISSUE THREAD

**Issue by pixie79** [brigadecore/brigade#924]
All releases should have a GPG signed SHA256sum file that can validate the release.

**Comment by radu-matei** [comment]
Hello!
That would be a really good idea, and I think we can look at the process the Helm project adopted for this.

@vdice - do you think we can tackle this in time for the 1.1 release, or do we want to defer after?

**Comment by vdice** [comment]
I'd say defer -- though, as always, pull requests welcome in the meantime!

**Comment by krancour** [comment]
This should be easy enough to do for the pre-built brig CLI for Mac, Linux, Win on amd64. I'm less clear on what signature or verification mechanisms are available for Docker images (which are the bulk of what we publish upon release) or Helm charts (part of a separate project, but no less important).

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
