### ISSUE TITLE
Ability to send brigade.json with `brig run`

### ISSUE THREAD

**Issue by Mister101** [brigadecore/brigade#928]
This is a feature request.

I am prototyping some things that have external dependencies. I saw that I need to have `brigade.json` in my repository in order for the build to pick it up and install them.

Since the dependencies are downloaded on every build anyway (not just when the project is created), would it be possible to add a flag to `brig run` similar to `--file` but for the `brigade.json` file?

**Comment by radu-matei** [comment]
Sure, that is a valid request, and would be really helpful for prototyping, as well as for enabling projects that don’t have a repo associated with them to use dependencies. 

Are you interested in contributing this feature?
I’d be more than happy to help you get started. 

(That being said, I just want to point out that you can also create a custom worker for your project and have the dependencies added in the container image)

**Comment by adinunzio84** [comment]
It will probably be a little while before I am able to contribute this, but if noone else does by then, I can try. In the meantime, I just created a repository. I created this request when I was going through the process and figured it would probably help others prototyping as well.

**Comment by radu-matei** [comment]
As I said, you don't actually _have_ to create a repo - you can create a new worker image, and add the dependencies there and use that worker image for your project, [as described in the documentation](https://docs.brigade.sh/topics/workers/).

**Comment by adinunzio84** [comment]
Yep, I did consider that, thanks. Seemed like the same amount of work either way so I just went with the repo approach.

**Comment by radu-matei** [comment]
ref #774
