### ISSUE TITLE
Better docs for docker-in-docker

### ISSUE THREAD

**Issue by jdolitsky** [brigadecore/brigade#934]
I was lost in the woods for a while, using
```
job.privileged = true;
```

to run `docker:dind`. After a while, it turned out I needed to use advanced options during `brig project create`:

```
? Allow host mounts Yes
? Allow privileged jobs Yes
```

**Comment by vdice** [comment]
Ah, good call.  Indeed, we at least need to instruct on setting `? Allow privileged jobs Yes` for the project in question.  

Meanwhile, `? Allow host mounts Yes` should _not_ be needed for d-in-d.  If convenient, could you help confirm?  (For docker-on-docker cases where the host's daemon is mounted in, then it would be.)
