### ISSUE TITLE
Improve error reporting in brig

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#938]
For newly created events, if anything wrong is happening in the init container, you don't get any visibility into what is wrong - same goes for other types of failures, which forces the users to go searching through logs.

We could compile a list of common failures that can happen, and surface the relevant logs directly though `brig`.

**Comment by mumoshu** [comment]
> We could compile a list of common failures that can happen, and surface the relevant logs directly though brig.

@radu-matei Can we start by just making `brig` stream last N lines(10 or so) of the init container logs if it failed?

Or do you have something more user-friendly in your mind? I'd appreciate an example of "a list of common failures" to see how granular each list item would be!

**Comment by mumoshu** [comment]
@radu-matei I've submitted the MVP of this feature in #967 that just stream a brig flag to stream all the init container logs. Would you mind taking a look?

Maybe we can gradually enhance it by perhaps enabling it by default, adding a nice header line before the init container logs.

**Comment by radu-matei** [comment]
^^ Tested and LGTM-ed, I think we can go ahead and merge it. I would keep this issue open though, until we are satisfied with the overall error reporting in `brig`, what do you think?

**Comment by mumoshu** [comment]
I agree that we should keep this open 👍 

Also posting a link to my comment https://github.com/brigadecore/brigade/pull/967#discussion_r310600394 as a basis for discussion.

Enabling `--init` by default sounds good. But output from vcs-sidecar seems a bit verbose. Can we e.g. prevent every bash script line being printed when there's no error? (Not sure how though

**Comment by vdice** [comment]
Removing from 1.3; we can consider for a future milestone if/when PRs appear.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
