### ISSUE TITLE
brig [resource] get inconsistency in output

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#939]
`brig build get` outputs YAML:

```
$ brig build get 01ddrty3jt9ns3t7q1zt9t8aym
id: 01ddrty3jt9ns3t7q1zt9t8aym
projectid: brigade-4912ed475391ddbfa05fd2d6e14f59b0fa0acbfe839ebb7d99412a
type: exec
provider: brigade-cli
revision:
  commit: ""
  ref: master
payload: []
script: []
worker:
  id: brigade-worker-01ddrty3jt9ns3t7q1zt9t8aym
  buildid: 01ddrty3jt9ns3t7q1zt9t8aym
  projectid: brigade-4912ed475391ddbfa05fd2d6e14f59b0fa0acbfe839ebb7d99412a
  starttime: 2019-06-20T00:40:27+03:00
  endtime: 2019-06-20T00:41:29+03:00
  exitcode: 0
  status: Succeeded
loglevel: ""
```

`brig project get` returns JSON:

```
$ brig project get no-vcs
{
  "metadata": {
    "name": "brigade-4912ed475391ddbfa05fd2d6e14f59b0fa0acbfe839ebb7d99412a",
    "creationTimestamp": null,
    "labels": {
      "app": "brigade",
      "component": "project",
      "heritage": "brigade"
    },
    "annotations": {
      "projectName": "no-vcs"
    }
  },
  "stringData": {
    "allowHostMounts": "false",
    "allowPrivilegedJobs": "false",
    "brigadejsPath": "",
    "buildStorageSize": "50Mi",
    "cloneURL": "",
    "defaultScript": ""
    "defaultScriptName": "",
    "genericGatewaySecret": "qmd3f",
    "github.baseURL": "",
    "github.token": "",
    "github.uploadURL": "",
    "imagePullSecrets": "",
    "initGitSubmodules": "false",
    "kubernetes.allowSecretKeyRef": "false",
    "kubernetes.buildStorageClass": "",
    "kubernetes.cacheStorageClass": "",
    "namespace": "brigade",
    "repository": "",
    "secrets": "{}",
    "serviceAccount": "",
    "sharedSecret": "",
    "sshKey": "",
    "vcsSidecar": "",
    "worker.name": "",
    "worker.pullPolicy": "IfNotPresent",
    "worker.registry": "",
    "worker.tag": "",
    "workerCommand": ""
  },
  "type": "brigade.sh/project"
}
```

We need to be consistent in the return type, and also have flags for choosing the output.

**Comment by radu-matei** [comment]
#996 added support for an `--output` flag on `brig list` and `brig get` commands.

However, there is still inconsistency in the default output:

- `brig project list` and `brig build list` output a table
- `brig project get` now has a flag for JSON, but by default returns a table


Proposal:

- all `get` and `list` commands print a table by default (we need to select the most relevant information here to show)
- there are flags for JSON and YAML across `brig`.

Thoughts?

**Comment by vdice** [comment]
👍 Proposal mentioned above sounds good to me!

**Comment by mumoshu** [comment]
The proposal sounds great 👍

**Comment by krancour** [comment]
Proposal sounds good, but it _is_ a breaking change-- you never know who has incorporated brig commands into some scripts and may suffer from the default output formats changing. I'm going to take the liberty of applying the 2.0 label to this.

**Comment by radu-matei** [comment]
I think we may have discussed this in one of the public meetings - sure, we should enable the _default_ behaviour as part of 2.0 - but I think we could add the respective `--output` flags and implementations, and control the default behaviour with an environment variable.

This way, tools and scripts with a dependency on the output type can continue to use it, and we also get the new output without always passing the flags.

What do you think?

**Comment by krancour** [comment]
@radu-matei I think that sounds great. Should this maybe be split into two separate issues then?

**Comment by vdice** [comment]
Removing from 1.3; we can consider for a future milestone if/when PRs appear.

**Comment by krancour** [comment]
2.0 consistently permits output of `table`, `json`, or `yaml` to be selected by the user. Commands consistently default to `table`.
