### ISSUE TITLE
Pull request event in github giving error 403

### ISSUE THREAD

**Issue by prshntsingh** [brigadecore/brigade#944]
I am facing an issue with pull request event in brigade, the github webhook is not getting delivered and giving error 403.

this issue comes only with PRs which has action:opened or synchronize, for other actions in PR like review requested it works fine. For other events like Push etc it works fine.

I have attached relevant SS, I am using brigade v1.0.0, for v0.19.0 it was working fine.

![Screenshot (74)](https://user-images.githubusercontent.com/19731697/60491234-f423fb80-9cc5-11e9-911e-3baf5b1dc47e.png)

![Screenshot (75)](https://user-images.githubusercontent.com/19731697/60491247-f8e8af80-9cc5-11e9-88de-d66d8c8c072b.png)

@radu-matei please have a look

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
