### ISSUE TITLE
Docs - Improve per-project specification section

### ISSUE THREAD

**Issue by eyjohn** [brigadecore/brigade#956]
As a fairly new user of Kubernetes, helm, and co. I found it difficult to understand that I need to install a new "helm" chart for every project that I create via the `brig` command.

The [brigade tutorial](https://docs.brigade.sh/intro/tutorial03/) simply points to the `README.md` in this repo after running `brig project create` and step [6. Add Brigade projects for each GitHub project](https://github.com/brigadecore/brigade-github-app#6-add-brigade-projects-for-each-github-project) doesn't really offer a lot of clarification.

Please note that the term `Project` feels a bit ambiguous to a new user since GitHub project, Brigade project, or installing a helm chart can all be interpreted as different types of project.

It would be great to have a clear list of expected actions when configuring a new GitHub project, something on the lines of:
1. Run `brig project create`: [Tutorial](https://docs.brigade.sh/intro/tutorial03/) covers this well 
2. Configure and install the brigade-project chart for every project you create: Ideally a more comprehensive version of [6. Add Brigade projects for each GitHub project](https://github.com/brigadecore/brigade-github-app#6-add-brigade-projects-for-each-github-project)
3. Project-specific setup: `brigade.js` template, for example, a simple no-op one which can just log something.

Thanks!

**Comment by dgkanatsios** [comment]
Thanks for the feedback!

Actually, you don’t need to install a new helm chart for each project you create. If you run brig project create and follow the interactive prompts, you’re good to go! 
I assume that you want to create a Brigade project that will “do stuff” in correlation to a GitHub repo, right? You will need to create a “VCS” project through brig.

Take also a look in the quickstart, you might find that helpful -> https://docs.brigade.sh/intro/quickstart/

**Comment by dgkanatsios** [comment]
I also noticed that the main links here https://docs.brigade.sh/intro/ do not contain the QuickStart, which probably is confusing. Keeping a note to fix that, thanks!

**Comment by eyjohn** [comment]
Thanks for the clarification, coincidently I discovered this when I tried to install my helm chart only to realize the secret was already somehow deployed.

Since both of these actions achieve the same result, it might be worthwhile highlighting in https://github.com/brigadecore/brigade-github-app#6-add-brigade-projects-for-each-github-project (or any other place `helm inspect values brigade/brigade-project` is indicated) that you do not need to do this if you are using the `brig` command.

**Comment by AndiDog** [comment]
Declarative setup of projects was the first thing I looked for when comparing CI tools. Argo CD nicely gives examples how to declaratively configure its configuration: https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/. I like how you provide a Helm chart for that purpose, but if people want to use another form of creating projects, they should be told in the documentation that it's possible. Simply put, it would already suffice to add after the first mention of `brig project create` that a Helm chart exists, and [projects can be created declaratively](https://github.com/brigadecore/charts/blob/master/charts/brigade-project/templates/secret.yaml).

**Comment by vdice** [comment]
Removing from 1.3; this appears to be mainly a docs issue so doesn't need to be tied to a given milestone at this time.

**Comment by krancour** [comment]
Closing due to staleness. Please do re-open if appropriate.
