### ISSUE TITLE
Update Brigade Worker build pipeline to use NPM?

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/brigade#958]
As more and more Node package vulnerabilities are reported, one fix would be to run a package audit as part of the build pipeline, and while both `npm` and `yarn` currently have an `audit` command, that reports back known vulnerabilities, `npm` also comes with `npm audit fix`, which auto-updates the vulnerable packages.

As per https://github.com/yarnpkg/yarn/issues/7075, this is not implemented yet in `yarn`.

Looking into this issue more, I don't find any functionality we currently use with `yarn` that we couldn't use with `npm`, so the decision would ultimately be one of preference between the two tools.

That being said, if we decide to use `npm`, the change would also cover the runtime aspect, not only the build pipeline. Here's a list of places where we use `yarn`:

- `package.json`
- `Makefile`
- controller (setting `yarn start` as entrypoint for the worker, although this just executes `node`)
- `brigade.json` in the worker adds dependencies using `yarn`

I'm putting together a PR to see the extent of the changes from `yarn` to `npm`, but this is very much an open discussion - WIP: https://github.com/radu-matei/brigade/tree/remove-node-modules

**Comment by dgkanatsios** [comment]
We shouldn't forget to replace 'yarn' with 'npm' on docs as well

**Comment by radu-matei** [comment]
That being said, we can also first add a `yarn audit` on the build pipeline, and manually update dependencies. This would require the fewest changes.
