### ISSUE TITLE
Allow specifying VCS brigade.js branch

### ISSUE THREAD

**Issue by eyjohn** [brigadecore/brigade#961]
I wanted to propose/discuss an alternative model for solving the security concerns highlighted in https://github.com/brigadecore/brigade/issues/319, https://github.com/brigadecore/brigade/issues/731 and https://github.com/brigadecore/brigade/issues/120.

The latest open issue https://github.com/brigadecore/brigade/issues/731 seems to build on top of https://github.com/brigadecore/brigade/pull/226 which provides a "trusted" author model for restricting who triggers webhooks. 

I wanted to instead suggest a branch-based structure where you can specify from which branch to retrieve the `brigade.js` file from. As such I could create a new branch called "brigade" and configure my BrigadejsBranch (or `BrigadejsVcsBranch`) just as I can the `BrigadejsPath` at the project level: https://github.com/brigadecore/brigade/blob/3879c9dcbad5363d8c6fee64669bd45016db3439/pkg/brigade/project.go#L54

You can then rely on Github Branch Restrictions to restrict who can actually push to this branch.
This could satisfy the requirement in https://github.com/brigadecore/brigade/issues/731 to default to master (or any other named branch) for any webhooks for retrieving the brigade.js file. 

This does leave an open question of how to test changes to the `brigade.js` file itself. A couple of approaches come to mind:
- Don't validate the change to brigade.js, a user can then enter a PR to master to validate it works.
- Evaluate the "target" branch for any actions (I guess mostly applies to PRs) at which point we can rely on `allowedAuthorRoles` for restricting who can take this action, in the case that the target is the designated branch, use this for pulling `brigade.js` rather than the base branch.

At this point, this change needs a bit more thought before it can be implemented, but I wanted to start a discussion.

Thanks!

**Comment by krancour** [comment]
I seem to recall having this discussion with someone a couple months ago and now I cannot seem to find that particular thread for reference... but this approach would add new complexity without actually addressing the vulnerability.

The existing risk is that someone could maliciously (or accidentally) open a PR that modifies `brigade.js` in a way, that for instance, dumps credentials into the logs. If that one file were the only avenue of attack, your proposed approach would work great, but in many, many cases, if not the majority, Brigade jobs are going to invoke other executable somethings-- shell scripts, make targets, etc. Literally any one of those (anything that executes with access to the environment variables, usually) is a vector for such an attack.

Preventing malicious modifications to `brigade.js`, ultimately, does not have the desired impact unless there is some way to shut down the threat of malicious modifications to many, many other files that won't be placed or named consistently across projects.

**Comment by eyjohn** [comment]
This is a great point, and I think documenting this in https://docs.brigade.sh/topics/security/ with this level of clarity would be ideal.

Unfortunately, this does lead to the conclusion that a brigade setup for projects which are using secrets (either for CD or resource access) is unsafe to expose to non-trusted users in the current form and as such running tests on PRs without a trusted author sign-off is not realistic.

Given this, I wonder whether the approach suggested in https://github.com/brigadecore/brigade/issues/120#issuecomment-343505551 of `disableSecrets` for untrusted users is the way to go here. It could enable projects to be written in a secret aware mode. I.e. some Jobs that run secret-less can continue to be executed. Jobs that try reference secrets simply won't have them and shouldn't be run.

We can then run the secret-less jobs upon a PR from anyone, but still, allow an authorised user to "upgrade" such a PR through a review/label to execute with secrets.

(I appreciate that this discussion has moved on beyond my initial suggestion so happy to move it to the other issue/forum if you prefer and close this one)

**Comment by krancour** [comment]
> Unfortunately, this does lead to the conclusion that a brigade setup for projects which are using secrets (either for CD or resource access) is unsafe to expose to non-trusted users in the current form and as such running tests on PRs without a trusted author sign-off is not realistic.

That is true. But it also a problem that _every_ CI/CD system grapples with.

> Given this, I wonder whether the approach suggested in #120 (comment) of disableSecrets for untrusted users is the way to go here. It could enable projects to be written in a secret aware mode. I.e. some Jobs that run secret-less can continue to be executed. Jobs that try reference secrets simply won't have them and shouldn't be run.

That's similar to how Circle deals with things, and iirc, Travis as well. By default, they don't inject secrets into builds _from forks_. That is too limiting, imo. I like this idea of injecting or withholding the secrets on the basis of level of trust rather than simply on the basis of being a fork or not. I _really_ like that suggestion.

> We can then run the secret-less jobs upon a PR from anyone, but still, allow an authorised user to "upgrade" such a PR through a review/label to execute with secrets.

I also love this idea. Thinking out loud about its implications...

User-defined builds/jobs (i.e. defined by `brigade.js`) shouldn't be able to respond to such labels or "slash comments" and then modify user permissions in response. That implementation would leave us vulnerable because a malicious actor could still escalate his/her permissions using the very attack vector we're attempting to close off here.

Considering the above, the safer alternative would involve baking support for those permission escalation event triggers right into the fabric of brigade itself and/or the githhub gateway. This seems like a non-trivial change, but I'd argue it would be worth it.

**Comment by eyjohn** [comment]
> That is true. But it also a problem that every CI/CD system grapples with.

Didn't mean to single out brigade here :) 

> User-defined builds/jobs (i.e. defined by brigade.js) shouldn't be able to respond to such labels or "slash comments" and then modify user permissions in response. That implementation would leave us vulnerable because a malicious actor could still escalate his/her permissions using the very attack vector we're attempting to close off here.

Agreed, I guess this makes more sense on a per action bound to a specific commit basis. Labels here are a bit ambiguous as they persist beyond the specific action, and indicate that your "upgraded" privilege opens us to the attack you describe.

Ideally, we would allow a trusted user to trigger a webhook against a specific commit (such as through a review action?) which would enable secrets for just that action. If a new commit is made then the PR remains un-privileged (no secrets) unless a trusted user takes an action again.

**Comment by krancour** [comment]
You're right. And going a step further, something like `/ok-to-test` (like in Prow) from a trusted user should be a _one-time_ approval to build the PR and that should reset if the PR is amended.

I believe a reasonable implementation probably only involves changes to the github gateway:

1. When pull request events that would typically either trigger a build _or_, if enabled, trigger "check suite forwarding" is received, _do not_ emit that event into Brigade and defer the check suite forwarding until...

1. Respond to PR comment events. When something like `/ok-to-test` is in the body of a comment from a trusted user, _then_ do the check suite forwarding.

What do we think of this?

**Comment by eyjohn** [comment]
I like the concept but I wanted to revisit some of the specific decisions in more detail.

### Event Handling (Linked vs Unlinked Events)

The way I interpreted the post above was that we evaluate multiple events together to deduce interactions, what I'll refer to as "linked" events. For example, we can get brigade to be aware of pull_requests and review events and to "delay" the pull request event from being emitted until a review/comment event from a trusted user. I imagine brigade will need to expose a way to control (or hard-code) combination of event relationships onto which this behaviour is applied.

Another approach would be to consider events as unrelated and simply rely on the trusted status of the user to decide whether to push the individual event through. This allows brigade to remain unaware of any cross-event relationships. This would defer the implementation of deciding whether to trigger a build/check on a PR comment or Review comment/action to the `brigade.js` authors.

Personally, the latter option IMO keeps brigade simpler whilst still providing users with a high level of control.

### Blocking events vs secrets

The previous post indicates that actions from untrusted users are blocked, but another option is to simply disable secrets but still emit the events. This allows secret-less jobs to continue to run.

I do like the idea that the latter option could allow jobs to be run without trusted user actions. 
I am hoping that between the lockdown of secrets, and possibly by locking down brigade.js as I initially suggested, that this would make it feasible for untrusted users to run these jobs. Although I'm not sure whether this would be considered insecure for other reasons?

**Comment by krancour** [comment]
To be clear, what I was proposing was stateless and didn't actually "link" events together.

The gw would simply _not_ emit certain events (like `pull_request:open`) under certain conditions (the PR was authored by an untrusted user). (Also it wouldn't do check suite forwarding.) A subsequent `issue_comment` event with `/ok-to-test` in the body should have sufficient metadata to identify the PR in question. This can be thought of as a proxy for the original event, which was suppressed (and immediately forgotten). Only then does the check suite forwarding that was skipped previously occur.

I _think_ we're both saying the same thing?

> The previous post indicates that actions from untrusted users are blocked, but another option is to simply disable secrets but still emit the events. This allows secret-less jobs to continue to run.

If we want to avoid breaking changes (and I think we do), the correct thing to do is require this new feature to be explicitly enabled with a configuration flag. So, no project will even have this behavior unless they ask for it. If it _is_ enabled, our implementation can be smart about not blocking builds if there are no secrets defined.

**Comment by eyjohn** [comment]
> I think we're both saying the same thing?

It seems we are, apologies for the misinterpretation.

>  A subsequent issue_comment event with /ok-to-test in the body should have sufficient metadata to identify the PR in question

I guess this would be configured in `brigade.js`, i.e. something like
```js
events.on("issue_comment", (e,p) => {
  if (e.body == "/ok-to-test") {
    // Do test job
  }
});
```

If that's the case, this is already possible following: https://github.com/brigadecore/brigade/pull/226 presuming the `allowedAuthors` is set correctly?

---

> I mean.... I could open a PR that launches 100 long-running containers that all mine bitcoin......

Heh, this is indeed something that crossed my mind when I posted earlier. I guess this is where `brigade.js` lock-down workflow is appealing. I.e. an untrusted user could both lose access to secrets
AND not be able to load their own containers, but only be executed within the containers already defined.

That's not to say that they can't do damage, but it could be constrained to the container and any network access that the container is granted (if any). 

Another more general approach to resource management could be to use a quota/limit system so as to restrict the number of resources that can be utilised, perhaps distinguishing between trusted and untrusted users. For example, an untrusted user is allowed no more than 5 execution time at 100m CPU.  Although at this point, I fear we're going down the path of some rather specialised features for a public-facing CI.

**Comment by krancour** [comment]
> I guess this would be configured in brigade.js, i.e. something like

Yes... but what we actually want is for the gw to perform the check suite forwarding here that it _didn't_ perform for the earlier event (the PR being opened or amended). Remember... we're not trying to actually get the `brigade.js` listening for comments. What we're trying to do is have it listen for `check_suite` events of some kinds-- same as before-- but have the gw use a comment to basically "block" those events until a trusted user lets them through.

re: the rest-- `brigade.js` lockdown, resource quotas, etc...

> I guess this is where brigade.js lock-down workflow is appealing.

Circling back on an earlier part of the discussion, locking down `brigade.js` won't matter if the untrusted user can still modify a make target used in any of the jobs.

> Another more general approach to resource management could be to use a quota/limit system so as to restrict the number of resources that can be utilised, perhaps distinguishing between trusted and untrusted users.

imho, there's no amount of resource that is safe to give an untrusted user if a trusted user hasn't approved it.

If we err on the side of simplicity here, I think what we've been discussing is a relatively narrowly scoped change with a big payoff. Should we start there? Since we're mainly talking about gw changes, we should probably move this discussion over there. I'd be happy to create a proposal over there.

**Comment by krancour** [comment]
Let's consider this superceded by https://github.com/brigadecore/brigade-github-app/issues/75

**Comment by eyjohn** [comment]
Thanks for the input! Yea the case for untrusted users is indeed more complex than I initially thought and in hindsight, it's probably not worth it.

Happy to continue the discussion in https://github.com/brigadecore/brigade-github-app/issues/75 about the blocking behaviour.
