### ISSUE TITLE
Write a brig-specific doc

### ISSUE THREAD

**Issue by mumoshu** [brigadecore/brigade#970]
Extracted from https://github.com/brigadecore/brigade/pull/967#pullrequestreview-270999945

Brigade seems to lack a dedicated documentation for `brig` - Brigade's command-line tool for interacting with Brigade. The more we add features to `brig`, the more likely we want it.

cc/ @vdice

**Comment by radu-matei** [comment]
Moving the content from `brig/README.md` into the documentation would also open up #83 
I think we can start with simply moving it to the docs, then enhance it as we go.

**Comment by radu-matei** [comment]
Started the work here - https://docs.brigade.sh/topics/brig/

Feel free to open follow-up PRs to improve that document :)
