### ISSUE TITLE
Proposal: Add cloneURL field to the Build struct

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#973]
Today I was working on adding Bitbucket support to [brigdrake](https://github.com/lovethedrake/brigdrake) (which is really only a custom worker). I had trouble getting pull request workflows to work across forks. I did some digging...

The [brigade-bitbucket-gateway](https://github.com/lukepatrick/brigade-bitbucket-gateway) was emitting events/builds into Brigade with revision ref referencing a commit _from the fork_, however, when spawning the worker, the Brigade controller unconditionally sets the `BRIGADE_REMOTE_URL` environment variable of the "vcs sidecar" to the `cloneURL` field _from the project--_ i.e. the vcs sidecar _always_ references the upstream. The commit in question does not exist there. The vcs sidecar fails. Whoops!

(Aside: Nothing like this happens with the brigade-github-app gateway because the way GitHub handles pull requests, behind the scenes, is fundamentally different from how Bitbucket does.)

The fix I'd like to PR to the [brigade-bitbucket-gateway](https://github.com/lukepatrick/brigade-bitbucket-gateway) involves adding the clone URL for the fork to the event/build that it emits into Brigade, but for that to actually have any effect, some changes are required to Brigade itself...

What I'd like to propose is adding an _optional_ `cloneURL` field to the `Build` struct. When this is set, the Brigade controller will honor it when setting the `BRIGADE_REMOTE_URL` on the worker's vcs sidecar. If left unset, it will fall back to the value in the `cloneURL` field of the `Project`.

Last, note that this may happen to improve Brigade's Bitbucket integration significantly, but in general, this undoes a narrow assumption about _where_ the source code for a given build should be obtained from and puts more control over this into the hands of the gateways that are scheduling the builds. Generally, they will know more than Brigade itself about the right place (e.g. a fork) to get the code from.

**Comment by vdice** [comment]
This sounds good to me.  It makes sense to place more knowledge/power into a particular gateway in terms of references/urls associated with the repositories that it handles/emits events for.  It being optional secures backwards compatibility.
