### ISSUE TITLE
Mismatch between intro documenation and helm chart (ClusterIP vs LoadBalancer)

### ISSUE THREAD

**Issue by yngvark** [brigadecore/brigade#983]
Hi

I'm completely new to brigade, and I'm simply following the instructions on
https://docs.brigade.sh/intro/install/

Documentation says:

> We would upgrade our brigade-server release like so:

```
$ helm upgrade brigade-server brigade/brigade --set brigade-github-app.enabled=true
```

and then states that I should see the `brigade-server-brigade-github-app` service as type LoadBalancer. However, to me it is of type ClusterIP.

```
$ kubectl get svc
NAME                                TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
brigade-server-brigade-api          ClusterIP   10.56.9.53     <none>        7745/TCP    18m
brigade-server-brigade-github-app   ClusterIP   10.56.4.114    <none>        80/TCP      7m30s
brigade-server-kashti               ClusterIP   10.56.15.194   <none>        80/TCP      18m
tiller-deploy                       ClusterIP   10.56.11.206   <none>        44134/TCP   56m
```

So, documentation is not aligned with the Helm Chart.

Output of `brig version`:
`v1.1.0`

Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.9", GitCommit:"16236ce91790d4c75b79f6ce96841db1c843e7d2", GitTreeState:"clean", BuildDate:"2019-03-25T06:40:24Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.7-gke.24", GitCommit:"2ce02ef1754a457ba464ab87dba9090d90cf0468", GitTreeState:"clean", BuildDate:"2019-08-12T22:05:28Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.):
GKE

**Comment by radu-matei** [comment]
Hi, and thanks a lot for opening the issue!
You're right, that snipped should not show a public IP, as by default we don't have any `LoadBalancer` type services in our charts.

That being said, if you're looking for ingress (because the part you pasted is from the section introducing ingress), be sure to also check out this document - https://docs.brigade.sh/topics/ingress/

We will update the part of the document - until then, is there something specifically we can help with? Have you managed to deploy correctly?
Thanks, and apologies for the inconvenience!

**Comment by yngvark** [comment]
No, everything is fine. I have just completed some tutorial steps, and although I encountered a few inaccuries in the docs, I figured out everything, and I'm so far very happy with Brigade. It looks like quite an improvement to what I use today, Jenkins with its Kubernetes Plugin.

**Comment by radu-matei** [comment]
Good to hear - could you also point out the other discrepancies in the documentation?
That's one area we should absolutely improve, and all help is welcome!

Thanks a lot!

**Comment by yngvark** [comment]
I had to do this fairly quickly and didn't take time to note down other issues, but I will keep it in mind in the future :+1:
